-- Part B (batch 3/4): import specifiche in public.product_specs. Match SOLO per nome.
-- 'ordine' 0-based per prodotto (precalcolato). Righe 'Nessun dato' escluse. Integrity guard MD5.
do $mig$
declare
  expected text := '610b625215fcd2ad1b4f807459332fbe';
  got text;
  n_ins int;
begin
  create temp table _stg_specs on commit drop as select n, f, v, (o)::int as o from jsonb_to_recordset($j$[{"n":"Isopropanolo (IPA)","f":"Shelf life","v":"Stabile per almeno 12 mesi in condizioni corrette di stoccaggio","o":16},
{"n":"Krypton","f":"Peso molecolare","v":"83,798 g/mol","o":0},
{"n":"Krypton","f":"Purezza gas disponibile","v":"Research Plus 99,999%; Research 99,995%; Window 99,9%","o":1},
{"n":"Krypton","f":"Infiammabilità","v":"Non infiammabile","o":2},
{"n":"Krypton","f":"Aspetto","v":"Gas incolore, inodore","o":3},
{"n":"Krypton","f":"Punto di fusione/congelamento","v":"-157,2°C","o":4},
{"n":"Krypton","f":"Punto di ebollizione","v":"-153°C","o":5},
{"n":"Krypton","f":"Densità relativa gas (aria=1)","v":"2,9","o":6},
{"n":"Krypton","f":"Densità relativa liquido (acqua=1)","v":"2,4","o":7},
{"n":"Krypton","f":"Solubilità in acqua","v":"221 mg/l","o":8},
{"n":"Krypton","f":"Temperatura critica","v":"-63,8°C","o":9},
{"n":"Lattice naturale adesivo","f":"Descrizione/Tipo","v":"Lattice di gomma naturale pre-vulcanizzato per colata e stampi","o":0},
{"n":"Lattice naturale adesivo","f":"Contenuto di gomma (Rubber)","v":"60% in peso","o":1},
{"n":"Lattice naturale adesivo","f":"Altri componenti","v":"Idrossido di ammonio <0,3%; Ammoniaca <0,005%; Tetrametiltiuram disolfuro <0,049%","o":2},
{"n":"Lattice naturale adesivo","f":"Aspetto/Colore","v":"Liquido bianco latteo","o":3},
{"n":"Lattice naturale adesivo","f":"Odore","v":"Ammoniaca","o":4},
{"n":"Lattice naturale adesivo","f":"Punto di ebollizione","v":"100°C","o":5},
{"n":"Lattice naturale adesivo","f":"Densità di vapore","v":"0,63","o":6},
{"n":"Lattice naturale adesivo","f":"Solubilità in acqua","v":"Miscibile","o":7},
{"n":"Lattice naturale adesivo","f":"Condizioni di stoccaggio","v":"55°F – 85°F (13–29°C); proteggere dal congelamento","o":8},
{"n":"Lattice naturale adesivo","f":"Shelf life","v":"Lunga durata di conservazione","o":9},
{"n":"Lattosio","f":"Peso molecolare","v":"360,31 g/mol","o":0},
{"n":"Lattosio","f":"Punto di fusione","v":"219°C (426°F)","o":1},
{"n":"Lattosio","f":"Aspetto","v":"Solido","o":2},
{"n":"Lattosio","f":"Composizione","v":"Nessun ingrediente pericoloso rilevato","o":3},
{"n":"Lattosio","f":"Classe di stoccaggio","v":"11 – Solidi combustibili","o":4},
{"n":"Lecitina di soia","f":"Formula molecolare","v":"C42H80NO8P","o":0},
{"n":"Lecitina di soia","f":"Peso molecolare","v":"758,06 g/mol","o":1},
{"n":"Lecitina di soia","f":"Composizione","v":"Lecitina di soia >95%","o":2},
{"n":"Lecitina di soia","f":"pH","v":"6,8 (soluzione acquosa 1%)","o":3},
{"n":"Lecitina di soia","f":"Solubilità in acqua","v":"Praticamente insolubile","o":4},
{"n":"Lecitina di soia","f":"Aspetto","v":"Solido, colore beige, inodore","o":5},
{"n":"Lignina","f":"Nome chimico","v":"Lignina alcalina","o":0},
{"n":"Lignina","f":"Aspetto","v":"Solido","o":1},
{"n":"Lignina","f":"Condizioni di stoccaggio","v":"2-8 °C, luogo asciutto","o":2},
{"n":"Lisozima","f":"Fonte","v":"Purificato da albume d'uovo di gallina","o":0},
{"n":"Lisozima","f":"Peso molecolare","v":"14.307 Da (calcolato da sequenza aminoacidica)","o":1},
{"n":"Lisozima","f":"Attività enzimatica","v":"≥ 39.000 unità/mg proteina","o":2},
{"n":"Lisozima","f":"Punto isoelettrico (pI)","v":"11,35","o":3},
{"n":"Lisozima","f":"pH ottimale","v":"6,0 - 9,0","o":4},
{"n":"Lisozima","f":"Solubilità","v":"10 mg/mL in acqua, soluzione limpida/leggermente opalescente","o":5},
{"n":"Lisozima","f":"Shelf life","v":"Soluzione acquosa: ≥1 mese a 2-8°C; prodotto solido: temperatura ambiente","o":6},
{"n":"Litopone","f":"Formula molecolare","v":"BaSO4 · ZnS","o":0},
{"n":"Litopone","f":"Peso molecolare","v":"330,84 g/mol","o":1},
{"n":"Litopone","f":"Aspetto","v":"Polvere bianca","o":2},
{"n":"Litopone","f":"Densità","v":"4,2 g/cm3","o":3},
{"n":"Litopone","f":"Punto di fusione","v":"N/A (non applicabile)","o":4},
{"n":"Magnesio (lingotti)","f":"Formula molecolare","v":"Mg","o":0},
{"n":"Magnesio (lingotti)","f":"Peso molecolare","v":"24,31 g/mol","o":1},
{"n":"Magnesio (lingotti)","f":"Purezza","v":"5N (99,999%)","o":2},
{"n":"Magnesio (lingotti)","f":"Aspetto","v":"Grigio","o":3},
{"n":"Magnesio (lingotti)","f":"Punto di fusione","v":"650 °C","o":4},
{"n":"Magnesio (lingotti)","f":"Punto di ebollizione","v":"1090 °C","o":5},
{"n":"Magnesio (lingotti)","f":"Densità","v":"1738 kg/m3","o":6},
{"n":"Maltodestrina","f":"Purezza","v":"Maltodestrina ≥96%","o":0},
{"n":"Maltodestrina","f":"Aspetto","v":"Polvere solida bianca, inodore","o":1},
{"n":"Maltodestrina","f":"pH","v":"~4,8 (soluzione al 50%)","o":2},
{"n":"Maltodestrina","f":"Densità relativa","v":"~0,50","o":3},
{"n":"Maltodestrina","f":"Solubilità in acqua","v":"~600 g/l a 20 °C","o":4},
{"n":"Maltodestrina","f":"Contenuto d'acqua (umidità)","v":"~4,2% (ISO 589)","o":5},
{"n":"Maltodestrina","f":"Granulometria (valore mediano)","v":"~100 µm (NFX 11-666)","o":6},
{"n":"Maltodestrina","f":"Temperatura di decomposizione","v":"> 200 °C","o":7},
{"n":"Maltosio","f":"Formula molecolare","v":"C12H22O11 · H2O (monoidrato)","o":0},
{"n":"Maltosio","f":"Peso molecolare","v":"360,29 g/mol (monoidrato)","o":1},
{"n":"Maltosio","f":"Punto di fusione","v":"130 °C","o":2},
{"n":"Maltosio","f":"Solubilità in acqua","v":"1080 g/L (20 °C)","o":3},
{"n":"Maltosio","f":"Aspetto","v":"Solido bianco","o":4},
{"n":"Manganese elettrolitico","f":"Formula molecolare","v":"Mn","o":0},
{"n":"Manganese elettrolitico","f":"Peso molecolare","v":"54,94 g/mol","o":1},
{"n":"Manganese elettrolitico","f":"Purezza","v":"3N (99,9%)","o":2},
{"n":"Manganese elettrolitico","f":"Aspetto","v":"Argenteo","o":3},
{"n":"Manganese elettrolitico","f":"Punto di fusione","v":"1244 °C","o":4},
{"n":"Manganese elettrolitico","f":"Punto di ebollizione","v":"1962 °C","o":5},
{"n":"Manganese elettrolitico","f":"Densità","v":"7,21-7,44 g/cm3","o":6},
{"n":"Metabisolfito di potassio","f":"Descrizione","v":"Polvere cristallina bianca, grado alimentare (E224)","o":0},
{"n":"Metabisolfito di potassio","f":"Packaging disponibile","v":"Sacchi 25 kg","o":1},
{"n":"Metabisolfito di potassio","f":"Shelf life","v":"6 mesi dalla data di produzione","o":2},
{"n":"Metabisolfito di potassio","f":"Temperatura di stoccaggio","v":"Max 30 °C, ambiente raccomandato","o":3},
{"n":"Metabisolfito di potassio","f":"Dosaggio applicativo","v":"1,75 g/hL forniscono 10 ppm SO2","o":4},
{"n":"Metabisolfito di sodio","f":"Composizione","v":"Sodio metabisolfito 99,1%; sodio solfito 0,4%; sodio solfato 0,5%","o":0},
{"n":"Metabisolfito di sodio","f":"Shelf life","v":"3 anni dalla data di produzione (contenitore originale)","o":1},
{"n":"Metabisolfito di sodio","f":"Conformità normativa","v":"Reg. (UE) 231/2012, FCC XII, Ph.Eur. 10, NF 38, ANSI PH4.276/ISO 3627, UNI EN 12121:2013","o":2},
{"n":"Metabisolfito di sodio","f":"Packaging disponibile","v":"Sacchi 50 lb, supersack","o":3},
{"n":"Metabisolfito di sodio","f":"Contenuto d'acqua (umidità)","v":"< 0,1 g/100g","o":4},
{"n":"Metano (gas naturale)","f":"Purezza (gradi disponibili)","v":"Chemical 2.5 ≥99,5%; Instrument 3.5 ≥99,95%; Detector 4.5 ≥99,995%; Scientific 5.5 ≥99,9995%","o":0},
{"n":"Metano (gas naturale)","f":"Acqua (impurità)","v":"≤5 ppm (grado 2.5-3.5); ≤1 ppm (grado 5.5)","o":1},
{"n":"Metano (gas naturale)","f":"Ossigeno (impurità)","v":"≤30 ppm (2.5) fino a ≤5 ppm (4.5/5.5)","o":2},
{"n":"Metano (gas naturale)","f":"Azoto (impurità)","v":"≤200 ppm (2.5) fino a ≤5 ppm (5.5)","o":3},
{"n":"Metano (gas naturale)","f":"Pressione di riempimento bombola","v":"200 bar","o":4},
{"n":"Metanolo","f":"Formula molecolare","v":"CH3OH","o":0},
{"n":"Metanolo","f":"Peso molecolare","v":"32,04 g/mol","o":1},
{"n":"Metanolo","f":"Purezza","v":"99,85% wt min","o":2},
{"n":"Metanolo","f":"Acqua (impurità)","v":"0,100% wt max","o":3},
{"n":"Metanolo","f":"Cloruri (impurità, come Cl-)","v":"0,5 mg/kg max","o":4},
{"n":"Metanolo","f":"Densità (specific gravity 20/20°C)","v":"0,7910 - 0,7930","o":5},
{"n":"Metanolo","f":"Punto di congelamento","v":"-97,8 °C","o":6},
{"n":"Metanolo","f":"Punto di ebollizione","v":"64,6 °C","o":7},
{"n":"Metanolo","f":"Punto di infiammabilità","v":"12 °C (closed cup)","o":8},
{"n":"Metanolo","f":"Solubilità","v":"Miscibile al 100% con acqua","o":9},
{"n":"Metilcellulosa","f":"Peso molecolare (grado M0512)","v":"~88.000","o":0},
{"n":"Metilcellulosa","f":"Viscosità (soluzione 2%, 20°C, grado M0512)","v":"~4000 cPs","o":1},
{"n":"Metilcellulosa","f":"Grado di sostituzione metossilica","v":"27,5-31,5% in peso","o":2},
{"n":"Metilcellulosa","f":"Grado di sostituzione (D.S.)","v":"1,5-1,9","o":3},
{"n":"Metilcellulosa","f":"Temperatura di gelificazione","v":"~48 °C (soluzione 2% w/w), decresce fino a ~30°C per soluzione 10%","o":4},
{"n":"Metilcellulosa","f":"Solubilità","v":"Fino a 10% in acqua per gradi a bassa viscosità; 2-3% per gradi ad alta viscosità","o":5},
{"n":"Metiletilchetone (MEK)","f":"Purezza","v":"≥99,5% m/m (GC)","o":0},
{"n":"Metiletilchetone (MEK)","f":"Peso molecolare","v":"72 g/mol","o":1},
{"n":"Metiletilchetone (MEK)","f":"Densità (20°C)","v":"0,805 kg/l","o":2},
{"n":"Metiletilchetone (MEK)","f":"Punto di ebollizione","v":"80 °C","o":3},
{"n":"Metiletilchetone (MEK)","f":"Punto di infiammabilità (Abel)","v":"-6 °C","o":4},
{"n":"Metiletilchetone (MEK)","f":"Contenuto d'acqua","v":"0,03% m/m max","o":5},
{"n":"Metiletilchetone (MEK)","f":"Colore (Pt-Co)","v":"< 5","o":6},
{"n":"Metiletilchetone (MEK)","f":"Punto di congelamento","v":"-86 °C","o":7},
{"n":"Metiletilchetone (MEK)","f":"Viscosità (20°C)","v":"0,42 mPa·s","o":8},
{"n":"Metiletilchetone (MEK)","f":"Conformità normativa","v":"ASTM D740 Tipo I e II, DIN 53247","o":9},
{"n":"Metilisobutilchetone (MIBK)","f":"Formula molecolare","v":"C6H12O","o":0},
{"n":"Metilisobutilchetone (MIBK)","f":"Peso molecolare","v":"100,2 g/mol","o":1},
{"n":"Metilisobutilchetone (MIBK)","f":"Aspetto","v":"Liquido incolore","o":2},
{"n":"Metilisobutilchetone (MIBK)","f":"Punto di congelamento","v":"-84,7 °C","o":3},
{"n":"Metilisobutilchetone (MIBK)","f":"Punto di ebollizione (760 mmHg)","v":"115 °C","o":4},
{"n":"Metilisobutilchetone (MIBK)","f":"Punto di infiammabilità (closed cup)","v":"14 °C","o":5},
{"n":"Metilisobutilchetone (MIBK)","f":"Densità (20°C)","v":"0,802 kg/l","o":6},
{"n":"Metilisobutilchetone (MIBK)","f":"Solubilità in acqua (20°C)","v":"2,0% (acqua in MIBK: 2,4%)","o":7},
{"n":"Metilisobutilchetone (MIBK)","f":"Viscosità cinematica (25°C)","v":"0,59 cP","o":8},
{"n":"Metilmetacrilato (MMA)","f":"Purezza (composizione)","v":"Metilmetacrilato ≥99,8-100,0%","o":0},
{"n":"Metilmetacrilato (MMA)","f":"Peso molecolare","v":"100,12 g/mol","o":1},
{"n":"Metilmetacrilato (MMA)","f":"Punto di fusione","v":"-48 °C","o":2},
{"n":"Metilmetacrilato (MMA)","f":"Punto di ebollizione","v":"100,36 °C (1013,25 hPa)","o":3},
{"n":"Metilmetacrilato (MMA)","f":"Punto di infiammabilità (closed cup)","v":"10 °C","o":4},
{"n":"Metilmetacrilato (MMA)","f":"Densità (20°C)","v":"0,94 g/cm3","o":5},
{"n":"Metilmetacrilato (MMA)","f":"Viscosità dinamica (20°C)","v":"0,53 mPa·s","o":6},
{"n":"Metilmetacrilato (MMA)","f":"Solubilità in acqua (20°C)","v":"15,3 g/l","o":7},
{"n":"Metilmetacrilato (MMA)","f":"Shelf life (stabilità in stoccaggio)","v":"12 mesi a T < 35 °C","o":8},
{"n":"Molibdato di sodio","f":"Aspetto","v":"Polvere fine bianca","o":0},
{"n":"Molibdato di sodio","f":"Purezza","v":"Na2MoO4 ≥99,1%","o":1},
{"n":"Molibdato di sodio","f":"Contenuto Molibdeno (Mo)","v":"≥46,2%","o":2},
{"n":"Molibdato di sodio","f":"Contenuto d'acqua","v":"≤0,25%","o":3},
{"n":"Molibdato di sodio","f":"Metalli pesanti (come Pb)","v":"≤0,001%","o":4},
{"n":"Molibdato di sodio","f":"Cloruri","v":"≤0,01%","o":5},
{"n":"Molibdato di sodio","f":"pH (soluzione 5%)","v":"7,5 - 10,0","o":6},
{"n":"Molibdato di sodio","f":"Punto di fusione","v":"686 °C","o":7},
{"n":"Molibdato di sodio","f":"Solubilità in acqua","v":"63 g/100ml a 20 °C","o":8},
{"n":"Molibdato di sodio","f":"Densità apparente","v":"70 lbs/ft3","o":9},
{"n":"Molibdato di sodio","f":"Shelf life","v":"Almeno 1 anno in contenitore chiuso","o":10},
{"n":"Mono e digliceridi degli acidi grassi","f":"Colore","v":"Bianco-avorio","o":0},
{"n":"Mono e digliceridi degli acidi grassi","f":"Monoestere totale","v":"Min. 95%","o":1},
{"n":"Mono e digliceridi degli acidi grassi","f":"Perdita all'essiccamento (umidità)","v":"Max. 2%","o":2},
{"n":"Mono e digliceridi degli acidi grassi","f":"Indice di acidità","v":"Max. 6%","o":3},
{"n":"Mono e digliceridi degli acidi grassi","f":"Glicerolo libero","v":"Max. 7%","o":4},
{"n":"Mono e digliceridi degli acidi grassi","f":"Glicerolo totale","v":"16-33%","o":5},
{"n":"Mono e digliceridi degli acidi grassi","f":"Residuo all'incenerimento (ceneri solfatate)","v":"Max. 0,5%","o":6},
{"n":"Mono e digliceridi degli acidi grassi","f":"Arsenico","v":"Max. 3 ppm","o":7},
{"n":"Mono e digliceridi degli acidi grassi","f":"Metalli pesanti (come Pb)","v":"Max. 2 ppm","o":8},
{"n":"Mono e digliceridi degli acidi grassi","f":"Solubilità","v":"Insolubile in acqua, solubile in etanolo/toluene a 50°C","o":9},
{"n":"Mono e digliceridi degli acidi grassi","f":"Conformità normativa","v":"Reg. CE 1333/2008 (E471)","o":10},
{"n":"Mono e digliceridi degli acidi grassi","f":"Packaging disponibile","v":"Sacchi 25 kg; buste alluminate 1-3 kg","o":11},
{"n":"Mono e digliceridi degli acidi grassi","f":"Shelf life","v":"24 mesi dalla data di produzione","o":12},
{"n":"Monossido di carbonio","f":"Peso molecolare","v":"28,010 g/mol","o":0},
{"n":"Monossido di carbonio","f":"Limiti di infiammabilità in aria","v":"12,5% - 74%","o":1},
{"n":"Monossido di carbonio","f":"Purezza (gradi disponibili)","v":"Research Plus 99,999%; Semiconductor 99,997%; Research 99,99%; UHP 99,9%; CP 99,3%","o":2},
{"n":"n-Butanolo","f":"Purezza","v":"Min. 99,8% wt (base umida)","o":0},
{"n":"n-Butanolo","f":"Contenuto d'acqua","v":"Max. 0,075%","o":1},
{"n":"n-Butanolo","f":"Acidità (come acido acetico)","v":"Max. 0,005%","o":2},
{"n":"n-Butanolo","f":"Colore (APHA/Hazen)","v":"Max. 10","o":3},
{"n":"n-Butanolo","f":"Residuo non volatile","v":"Max. 10 mg/100ml","o":4},
{"n":"n-Butanolo","f":"Densità (specific gravity 20/20°C)","v":"Tipico 0,809-0,811","o":5},
{"n":"n-Butanolo","f":"Aspetto","v":"Limpido e brillante","o":6},
{"n":"n-Eptano","f":"Densità (15°C)","v":"0,717 kg/L","o":0},
{"n":"n-Eptano","f":"Punto di ebollizione (distillazione, IBP-Dry Point)","v":"95-99 °C","o":1},
{"n":"n-Eptano","f":"Punto di infiammabilità (Abel)","v":"-7 °C","o":2},
{"n":"n-Eptano","f":"Peso molecolare","v":"99 g/mol (calcolato)","o":3},
{"n":"n-Eptano","f":"Viscosità (25°C)","v":"0,64 mm2/s","o":4},
{"n":"n-Eptano","f":"Contenuto n-Eptano","v":"39% m/m","o":5},
{"n":"n-Eptano","f":"Zolfo (impurità)","v":"< 0,5 mg/kg","o":6},
{"n":"n-Eptano","f":"Punto di scorrimento (pour point)","v":"< -50 °C","o":7},
{"n":"n-Esano","f":"Composizione","v":"n-Esano 80-100%","o":0},
{"n":"n-Esano","f":"Peso molecolare","v":"86,18 g/mol","o":1},
{"n":"n-Esano","f":"Punto di fusione","v":"-95 °C","o":2},
{"n":"n-Esano","f":"Punto di ebollizione","v":"69 °C","o":3},
{"n":"n-Esano","f":"Punto di infiammabilità (closed cup)","v":"-22 °C","o":4},
{"n":"n-Esano","f":"Densità (25°C)","v":"0,659 g/mL","o":5},
{"n":"n-Esano","f":"Solubilità in acqua (25°C)","v":"0,01 g/l","o":6},
{"n":"n-Esano","f":"Viscosità dinamica (25°C)","v":"0,3 mPa·s","o":7},
{"n":"n-Esano","f":"pH","v":"7,0","o":8},
{"n":"N-Metilpirrolidone (NMP)","f":"Composizione","v":"NMP 80-100%","o":0},
{"n":"N-Metilpirrolidone (NMP)","f":"Peso molecolare","v":"99,13 g/mol","o":1},
{"n":"N-Metilpirrolidone (NMP)","f":"pH","v":"8,5-10,0 (100 g/l, 20°C)","o":2},
{"n":"N-Metilpirrolidone (NMP)","f":"Punto di fusione","v":"-24 °C","o":3},
{"n":"N-Metilpirrolidone (NMP)","f":"Punto di ebollizione","v":"202 °C","o":4},
{"n":"N-Metilpirrolidone (NMP)","f":"Punto di infiammabilità (Pensky-Martens closed cup)","v":"91 °C","o":5},
{"n":"N-Metilpirrolidone (NMP)","f":"Densità (25°C)","v":"1,028 g/mL","o":6},
{"n":"N-Metilpirrolidone (NMP)","f":"Solubilità in acqua (20°C)","v":"1000 g/l","o":7},
{"n":"N-Metilpirrolidone (NMP)","f":"Viscosità dinamica (25°C)","v":"1,661 mPa·s","o":8},
{"n":"N-Metilpirrolidone (NMP)","f":"Indice di rifrazione (25°C)","v":"1,469","o":9},
{"n":"Natamicina","f":"Origine","v":"Antifungino naturale prodotto per fermentazione di Streptomyces natalensis; Non-GMO","o":0},
{"n":"Natamicina","f":"Concentrazione natamicina (NATAMAX standard/SALT/G)","v":"≥50,0% p/p su base secca","o":1},
{"n":"Natamicina","f":"Concentrazione natamicina (NATAMAX B / SF)","v":"≥95,0% p/p su base secca","o":2},
{"n":"Natamicina","f":"Concentrazione natamicina (NATAMAX B PLUS)","v":"≥12,5% p/p su base secca","o":3},
{"n":"Natamicina","f":"Concentrazione natamicina (NATAMAX SALT DA)","v":"≥6,5% p/p su base secca","o":4},
{"n":"Natamicina","f":"Concentrazione natamicina (NATAMAX GEL)","v":"≥8,0% p/p su base secca","o":5},
{"n":"Natamicina","f":"Range di efficacia pH","v":"3 - 9","o":6},
{"n":"Natamicina","f":"Dosaggio efficace tipico","v":"1 - 40 ppm","o":7},
{"n":"Natamicina","f":"Conformità normativa","v":"JECFA (FAO/WHO), Codex GSFA (INS235), GRAS (FDA, USA), E235 (UE), Food Chemicals Codex (FCC)","o":8},
{"n":"Neon","f":"Peso molecolare","v":"20,1797","o":0},
{"n":"Neon","f":"Volume specifico","v":"19,17 cf/lb a 70°F e 1 ATM","o":1},
{"n":"Neon","f":"Infiammabilità","v":"Non infiammabile","o":2},
{"n":"Neon","f":"Purezza (grado Semiconductor/Research)","v":"99,999%","o":3},
{"n":"Neon","f":"Purezza (grado Ultra High Purity)","v":"99,996%","o":4},
{"n":"Neon","f":"Impurezze max (grado UHP)","v":"O2 2 ppm, H2O 2 ppm, THC 0,5 ppm, CO 0,5 ppm, CO2 0,5 ppm, Ar 1 ppm, N2 10 ppm, He 30 ppm","o":5},
{"n":"Nerofumo (carbon black)","f":"Metodi di caratterizzazione","v":"Superficie BET (ISO 4652/ASTM D6556), Adsorbimento iodio (ISO 1304/ASTM D1510), Oil Absorption Number OAN (ISO 4656/ASTM D2414), Materia volatile a 950°C (DIN 53552), pH (ISO 787-9/ASTM D1512), Tint strength (ISO 5435/ASTM D3265)","o":0},
{"n":"Nerofumo (carbon black)","f":"Range tipico gamma Specialty Carbon Black (Orion)","v":"Tint strength 13-155%, Materia volatile 0,2-20%, OAN 38-410 cc/100g, pH 2,5-11, Superficie BET 9-1150 m²/g, Diametro particella primaria media 11-280 nm","o":1},
{"n":"Niacinamide (vitamina B3)","f":"Formula molecolare","v":"C6H6N2O","o":0},
{"n":"Niacinamide (vitamina B3)","f":"Peso molecolare","v":"122,1 g/mol","o":1},
{"n":"Niacinamide (vitamina B3)","f":"Assay","v":"99,0-101,0% p/p","o":2},
{"n":"Niacinamide (vitamina B3)","f":"Sostanze correlate (3-cianopiridina)","v":"≤0,10% p/p","o":3},
{"n":"Niacinamide (vitamina B3)","f":"Impurezza totale","v":"≤0,2% p/p","o":4},
{"n":"Niacinamide (vitamina B3)","f":"Acido nicotinico","v":"max 200 ppm","o":5},
{"n":"Niacinamide (vitamina B3)","f":"pH (soluzione)","v":"6,0-7,5","o":6},
{"n":"Niacinamide (vitamina B3)","f":"Punto di fusione","v":"128,0-131,0°C","o":7},
{"n":"Niacinamide (vitamina B3)","f":"Granulometria","v":"≥50 μm min 90,0%; ≥250 μm max 8,0%","o":8},
{"n":"Niacinamide (vitamina B3)","f":"Residuo all'incenerimento (ceneri solfatate)","v":"max 0,10% p/p","o":9},
{"n":"Niacinamide (vitamina B3)","f":"Metalli pesanti","v":"max 20 ppm","o":10},
{"n":"Niacinamide (vitamina B3)","f":"Piombo","v":"max 2 ppm","o":11},
{"n":"Niacinamide (vitamina B3)","f":"Cloruri","v":"max 70 mg/kg","o":12},
{"n":"Niacinamide (vitamina B3)","f":"Solfati","v":"max 190 mg/kg","o":13},
{"n":"Niacinamide (vitamina B3)","f":"Perdita all'essiccamento","v":"max 0,5% p/p","o":14},
{"n":"Niacinamide (vitamina B3)","f":"Solubilità","v":"Liberamente solubile in acqua (691,0 g/L a 20°C) e alcol; solubile in glicerolo; molto poco solubile in etere/cloroformio","o":15},
{"n":"Niacinamide (vitamina B3)","f":"Conformità farmacopea","v":"USP, FCC, Ph. Eur.","o":16},
{"n":"Niacinamide (vitamina B3)","f":"Shelf life","v":"36 mesi","o":17},
{"n":"Nichel (catodi)","f":"Contenuto Nichel","v":"99,9%","o":0},
{"n":"Nichel (catodi)","f":"Aspetto","v":"Solido, colore grigio argento, inodore","o":1},
{"n":"Nichel (catodi)","f":"Punto di fusione","v":"1455°C","o":2},
{"n":"Nichel (catodi)","f":"Punto di ebollizione","v":"2730°C","o":3},
{"n":"Nichel (catodi)","f":"Densità","v":"4-5 g/cm3","o":4},
{"n":"Nitrato ammonico di calcio (CAN)","f":"Azoto totale (N)","v":"27,0%","o":0},
{"n":"Nitrato ammonico di calcio (CAN)","f":"Azoto nitrico (NO3)","v":"13,5%","o":1},
{"n":"Nitrato ammonico di calcio (CAN)","f":"Azoto ammoniacale (NH4)","v":"13,5%","o":2},
{"n":"Nitrato ammonico di calcio (CAN)","f":"Calcio (Ca)","v":"4,0%","o":3},
{"n":"Nitrato ammonico di calcio (CAN)","f":"Magnesio (Mg)","v":"1,0%","o":4},
{"n":"Nitrato ammonico di calcio (CAN)","f":"Stabilizzante","v":"Dolomite 20%","o":5},
{"n":"Nitrato ammonico di calcio (CAN)","f":"Diametro medio granulo","v":"3,6 mm (SGN 360)","o":6},
{"n":"Nitrato ammonico di calcio (CAN)","f":"Densità apparente","v":"Sfusa 61 lb/ft3; compattata 64 lb/ft3","o":7},
{"n":"Nitrato di ammonio","f":"Purezza (Ammonium Nitrate)","v":"98,8-99,8% p/p","o":0},
{"n":"Nitrato di ammonio","f":"Contenuto d'acqua","v":"max <0,15%","o":1},
{"n":"Nitrato di ammonio","f":"Densità apparente (come prodotto)","v":"0,78-0,82 g/cc (48,5-51,0 lb/ft3)","o":2},
{"n":"Nitrato di ammonio","f":"Densità apparente (come ricevuto)","v":"0,80-0,86 g/cc (50,0-53,0 lb/ft3)","o":3},
{"n":"Nitrato di ammonio","f":"Assorbimento olio","v":">6,0% p/p","o":4},
{"n":"Nitrato di ammonio","f":"Granulometria","v":"U.S. Standard 6-20, >98%","o":5},
{"n":"Nitrato di ammonio","f":"Organici totali","v":"<0,2%","o":6},
{"n":"Nitrato di ammonio","f":"Forma","v":"Prilli porosi grado industriale","o":7},
{"n":"Nitrato di calcio","f":"Forma","v":"Granulare","o":0},
{"n":"Nitrato di calcio","f":"Azoto totale","v":"min 15,5% (tipico 15,52%)","o":1},
{"n":"Nitrato di calcio","f":"Azoto nitrico","v":"min 14,4% (tipico 14,41%)","o":2},
{"n":"Nitrato di calcio","f":"Azoto ammoniacale","v":"min 1,1% (tipico 1,12%)","o":3},
{"n":"Nitrato di calcio","f":"Ossido di calcio (CaO)","v":"min 26,0% (tipico 26,1%)","o":4},
{"n":"Nitrato di calcio","f":"Calcio (Ca)","v":"min 18,8% (tipico 18,83%)","o":5},
{"n":"Nitrato di calcio","f":"Insolubile in acqua","v":"max 0,1% (tipico 0,09%)","o":6},
{"n":"Nitrato di calcio","f":"Ferro","v":"max 0,02% (tipico 0,0046%)","o":7},
{"n":"Nitrato di calcio","f":"PO4","v":"max 0,051% (tipico 0,049%)","o":8},
{"n":"Nitrato di calcio","f":"Cloruri","v":"max 0,02% (tipico 0,018%)","o":9},
{"n":"Nitrato di calcio","f":"Umidità","v":"max 2,0% (tipico 0,46%)","o":10},
{"n":"Nitrato di calcio","f":"pH","v":"5-7 (tipico 5,7)","o":11},
{"n":"Nitrato di calcio","f":"Granulometria","v":"90% 2-4mm; 10% 1-2mm","o":12},
{"n":"Nitrato di calcio","f":"Metalli pesanti (As, Cd, Pb, Cr, Hg, Ni, Cu, Zn)","v":"tutti <1 mg/kg","o":13},
{"n":"Nitrato di calcio","f":"Conformità normativa","v":"REACH","o":14},
{"n":"Nitrato di cellulosa","f":"Aspetto","v":"Polvere/pellet bianco irregolare","o":0},
{"n":"Nitrato di cellulosa","f":"Densità specifica","v":"1,65-1,67 g/cm3 (in acqua)","o":1},
{"n":"Nitrato di cellulosa","f":"Contenuto volatili","v":"28-32%","o":2},
{"n":"Nitrato di cellulosa","f":"Contenuto solidi","v":"68-72% p/p (50-60% v/v)","o":3},
{"n":"Nitrato di cellulosa","f":"Contenuto VOC","v":"23-27%","o":4},
{"n":"Nitrato di cellulosa","f":"Contenuto d'acqua","v":"≤5%","o":5},
{"n":"Nitrato di cellulosa","f":"Contenuto azoto","v":"10,7-11,2%","o":6},
{"n":"Nitrato di cellulosa","f":"Punto di accensione","v":"≥180°C","o":7},
{"n":"Nitrato di cellulosa","f":"Acidità (grado SS)","v":"≤0,03-0,04% a seconda del grado","o":8},
{"n":"Nitrato di cellulosa","f":"Viscosità (grado SS)","v":"da 1,6-2,9 sec fino a 15-20 sec a seconda del grado","o":9},
{"n":"Nitrato di cellulosa","f":"Formulazione","v":"Umidificato con 30% isopropanolo (IPA)","o":10},
{"n":"Nitrato di magnesio","f":"Formula molecolare","v":"Mg(NO3)2","o":0},
{"n":"Nitrato di magnesio","f":"Peso molecolare","v":"148,31 g/mol","o":1},
{"n":"Nitrato di magnesio","f":"Purezza","v":"99% (2N)","o":2},
{"n":"Nitrato di magnesio","f":"Aspetto","v":"Cristalli bianchi","o":3},
{"n":"Nitrato di magnesio","f":"Punto di fusione","v":"89°C","o":4},
{"n":"Nitrato di magnesio","f":"Punto di ebollizione","v":"330°C (decomposizione)","o":5},
{"n":"Nitrato di magnesio","f":"Densità","v":"1,46 g/cm3","o":6},
{"n":"Nitrato di potassio","f":"Formula chimica","v":"KNO3","o":0},
{"n":"Nitrato di potassio","f":"Aspetto","v":"Cristalli bianchi, solido solubile","o":1},
{"n":"Nitrato di potassio","f":"Purezza KNO3","v":"98,0% min","o":2},
{"n":"Nitrato di potassio","f":"Azoto (N)","v":"13,5-13,6%","o":3},
{"n":"Nitrato di potassio","f":"Potassio (K2O)","v":"46,0%","o":4},
{"n":"Nitrato di potassio","f":"Solubilità (acqua 20°C)","v":"315 g/L","o":5},
{"n":"Nitrato di potassio","f":"pH (soluzione 1%)","v":"7,0-9,0","o":6},
{"n":"Nitrato di potassio","f":"Conducibilità elettrica (1 g/L, 20°C)","v":"1325 µS/cm","o":7},
{"n":"Nitrato di potassio","f":"Insolubile","v":"max 0,05%","o":8},
{"n":"Nitrito di sodio","f":"Composizione","v":"Soluzione acquosa di sodio nitrito e sodio nitrato","o":0},
{"n":"Nitrito di sodio","f":"Aspetto","v":"Liquido inodore, limpido, giallo pallido","o":1},
{"n":"Nitrito di sodio","f":"pH (soluzione 1%)","v":"9,0","o":2},
{"n":"Nitrito di sodio","f":"Peso specifico a 21°C","v":"1,35-1,43","o":3},
{"n":"Nitrito di sodio","f":"Punto di congelamento","v":"circa -1°C","o":4},
{"n":"Nitrito di sodio","f":"Densità","v":"11,3-11,9 lb/gal (US)","o":5},
{"n":"Nitrito di sodio","f":"Totale sodio nitrito + nitrato","v":"46-53%","o":6},
{"n":"Nitrocellulosa","f":"Aspetto","v":"Solido, bianco/biancastro","o":0},
{"n":"Nitrocellulosa","f":"Assay (contenuto azoto)","v":"10,9-11,2% p/p","o":1},
{"n":"Nitrocellulosa","f":"Applicazione","v":"Supporto per test diagnostici (membrane lateral flow)","o":2},
{"n":"Nonilfenolo etossilato (NPE)","f":"Formula","v":"(C2H4O)nC15H24O","o":0},
{"n":"Nonilfenolo etossilato (NPE)","f":"Aspetto","v":"Liquido limpido, da incolore a giallastro","o":1},
{"n":"Nonilfenolo etossilato (NPE)","f":"pH (soluzione 1% acquosa)","v":"5-7","o":2},
{"n":"Nonilfenolo etossilato (NPE)","f":"Punto di ebollizione","v":">250°C","o":3},
{"n":"Nonilfenolo etossilato (NPE)","f":"Densità relativa","v":"1,045-1,065","o":4},
{"n":"Nonilfenolo etossilato (NPE)","f":"Punto di infiammabilità","v":"217°C (ASTM D7094)","o":5},
{"n":"Nonilfenolo etossilato (NPE)","f":"Solubilità","v":"Solubile in acqua","o":6},
{"n":"Nonilfenolo etossilato (NPE)","f":"Tensione di vapore","v":"<0,0013 kPa a 20°C","o":7},
{"n":"Nutriente per lieviti (fosfato biammonico)","f":"Composizione","v":"Fosfato diammonico","o":0},
{"n":"Nutriente per lieviti (fosfato biammonico)","f":"Dosaggio","v":"20-30 g/hL (fermentazione primaria e secondaria)","o":1},
{"n":"Nutriente per lieviti (fosfato biammonico)","f":"Dose massima legale UE","v":"100 g/hL (fermentazione primaria); 30 g/hL (rifermentazione spumanti)","o":2},
{"n":"Nutriente per lieviti (fosfato biammonico)","f":"Resa in YAN","v":"10 g/hL DAP forniscono 21 mg/L di YAN","o":3},
{"n":"Nutriente per lieviti (fosfato biammonico)","f":"Packaging disponibile","v":"25 kg","o":4},
{"n":"Nutriente per lieviti (fosfato biammonico)","f":"Conformità normativa","v":"Codex Œnologique International, Reg. (UE) 2019/934, TTB 27 CFR 24.246 (max 8 lb/1000 gal negli USA)","o":5},
{"n":"Octenidina dicloridrato","f":"Formula strutturale","v":"C36H62N4 · 2HCl","o":0},
{"n":"Octenidina dicloridrato","f":"Peso molecolare","v":"623,8 g/mol","o":1},
{"n":"Octenidina dicloridrato","f":"Stato fisico","v":"Solido","o":2},
{"n":"Octenidina dicloridrato","f":"Punto di fusione","v":"214°C","o":3},
{"n":"Octenidina dicloridrato","f":"Solubilità","v":"DMF 10 mg/ml; DMSO 5 mg/ml; Etanolo 30 mg/ml; Etanolo:PBS pH 7,2 (1:7) 0,12 mg/ml","o":4},
{"n":"Octenidina dicloridrato","f":"Infiammabilità","v":"Prodotto non infiammabile","o":5},
{"n":"Octocrylene","f":"Nome chimico","v":"Acido 2-ciano-3,3-difenilacrilico 2'-etilesil estere","o":0},
{"n":"Octocrylene","f":"Formula molecolare","v":"C24H27NO2","o":1},
{"n":"Octocrylene","f":"Peso molecolare","v":"361 g/mol","o":2},
{"n":"Octocrylene","f":"Aspetto","v":"Liquido viscoso giallo chiaro","o":3},
{"n":"Octocrylene","f":"Solubilità (25°C)","v":"39,0% in Uvinul A Plus Granular; 7,3% in Tinosorb S; 4,2% in Uvinul T150","o":4},
{"n":"Octocrylene","f":"Concentrazione approvata in prodotti cosmetici","v":"Fino al 10% (UE, Svizzera, India, Taiwan, Cina, USA, Canada, ecc.; max 12% in Sud America)","o":5},
{"n":"Octocrylene","f":"Shelf life","v":"Minimo 1 anno in contenitore sigillato originale","o":6},
{"n":"Olio di cocco","f":"Nome botanico","v":"Cocos nucifera L.","o":0},
{"n":"Olio di cocco","f":"Aspetto","v":"Liquido mobile da incolore a giallo pallido","o":1},
{"n":"Olio di cocco","f":"Punto di infiammabilità (vaso chiuso)","v":">100°C","o":2},
{"n":"Olio di cocco","f":"Indice di rifrazione (@40°C)","v":"1,439-1,459","o":3},
{"n":"Olio di cocco","f":"Densità relativa (@40°C)","v":"0,908-0,921","o":4},
{"n":"Olio di cocco","f":"Solubilità","v":"Solubile in alcol, insolubile in acqua","o":5},
{"n":"Olio di cocco","f":"Composizione acidi grassi (GC)","v":"Acido miristico 15-20%, caprilico 5-11%, oleico 4-10%, caprico 4-9%","o":6},
{"n":"Olio di cocco","f":"Shelf life","v":"12 mesi","o":7},
{"n":"Olio di colza","f":"Colore (Lovibond 5¼\")","v":"max 15Y-1,5R","o":0},
{"n":"Olio di colza","f":"Acidi grassi liberi (come acido oleico)","v":"max 0,1%","o":1},
{"n":"Olio di colza","f":"Indice di iodio","v":"105-126 g I2/100g","o":2},
{"n":"Olio di colza","f":"Umidità","v":"max 0,1%","o":3},
{"n":"Olio di colza","f":"Indice di perossido","v":"max 1,0 meq/kg","o":4},
{"n":"Olio di colza","f":"Indice di saponificazione","v":"187,0-195,0 mg KOH/g","o":5},
{"n":"Olio di colza","f":"Punto di infiammabilità","v":">280°C","o":6},
{"n":"Olio di colza","f":"Fosforo","v":"max 5 mg/kg","o":7},
{"n":"Olio di colza","f":"Indice di rifrazione (@20°C)","v":"1,465-1,475","o":8},
{"n":"Olio di colza","f":"Densità relativa (@23°C)","v":"0,91-0,93 g/cm3","o":9},
{"n":"Olio di colza","f":"Punto di fumo","v":">200°C","o":10},
{"n":"Olio di colza","f":"Contenuto saponi","v":"max 50 mg/kg","o":11},
{"n":"Olio di colza","f":"Materia insaponificabile","v":"max 2,0%","o":12},
{"n":"Olio di colza","f":"Metalli pesanti","v":"As max 0,1; Cu max 0,1; Fe max 1,5; Pb max 0,1 mg/kg","o":13},
{"n":"Olio di colza","f":"Composizione acidi grassi","v":"Monoinsaturi min 54%, polinsaturi ~30%, saturi ~8%, erucico max 5%, trans max 1,5%","o":14},
{"n":"Olio di colza","f":"Shelf life","v":"2 anni (confezionato), 1 anno (sfuso)","o":15},
{"n":"Olio di girasole","f":"Acidi grassi liberi","v":"0,000-0,130%","o":0},
{"n":"Olio di girasole","f":"Indice di iodio","v":"88,00-143,00","o":1},
{"n":"Olio di girasole","f":"Acido linoleico","v":"15,00-75,00%","o":2},
{"n":"Olio di girasole","f":"Acido linolenico","v":"0,00-1,50%","o":3},
{"n":"Olio di girasole","f":"Acido oleico","v":"14,00-75,00%","o":4},
{"n":"Olio di girasole","f":"Acido palmitico","v":"3,00-10,00%","o":5},
{"n":"Olio di girasole","f":"Indice di perossido","v":"0,00-10,00 meq/kg","o":6},
{"n":"Olio di girasole","f":"Indice di rifrazione (@20°C)","v":"1,4700-1,4750","o":7},
{"n":"Olio di girasole","f":"Peso specifico (@25°C)","v":"0,9100-0,9200","o":8},
{"n":"Olio di girasole","f":"Acido stearico","v":"1,00-10,00%","o":9},
{"n":"Olio di girasole","f":"Colore/aspetto","v":"Liquido oleoso limpido, giallo-verdastro brillante","o":10},
{"n":"Olio di girasole","f":"Punto di infiammabilità","v":">200°F (>93,3°C)","o":11},
{"n":"Olio di girasole","f":"Shelf life","v":"12 mesi","o":12},
{"n":"Olio di girasole","f":"Specie botanica","v":"Helianthus annuus L. (seme)","o":13},
{"n":"Olio di jojoba","f":"INCI","v":"Simmondsia Chinensis Seed Oil","o":0},
{"n":"Olio di jojoba","f":"Aspetto (@20°C)","v":"Liquido limpido giallastro","o":1},
{"n":"Olio di jojoba","f":"Densità relativa (@20°C)","v":"0,863-0,873","o":2},
{"n":"Olio di jojoba","f":"Indice di rifrazione (@20°C)","v":"1,465-1,467","o":3},
{"n":"Olio di jojoba","f":"Indice di saponificazione","v":"90-98","o":4},
{"n":"Olio di jojoba","f":"Indice di acidità","v":"max 2,0","o":5},
{"n":"Olio di jojoba","f":"Indice di iodio","v":"80-90","o":6},
{"n":"Olio di jojoba","f":"Materia insaponificabile","v":"45-55%","o":7},
{"n":"Olio di jojoba","f":"Composizione acidi grassi","v":"Palmitico max 3,0%; Oleico 5,0-15,0%; Eicosenoico 65,0-80,0%; Erucico 10,0-22,0%; Nervonico max 3,5%","o":8},
{"n":"Olio di jojoba","f":"Microbiologia","v":"Conta totale ≤100 cfu/g; lieviti/muffe ≤100 cfu/g; patogeni assenti","o":9},
{"n":"Olio di jojoba","f":"Shelf life","v":"min 24 mesi","o":10},
{"n":"Olio di jojoba","f":"Certificazione","v":"Biologico ECOCERT GREENLIFE (standard COSMOS)","o":11},
{"n":"Olio di palma","f":"Aspetto","v":"Semisolido, colore giallo, odore dolciastro","o":0},
{"n":"Olio di palma","f":"Punto di fusione/congelamento","v":"27,0-42,5°C","o":1},
{"n":"Olio di palma","f":"Punto di infiammabilità","v":"314-323°C","o":2},
{"n":"Olio di palma","f":"Densità relativa","v":"0,92","o":3},
{"n":"Olio di palma","f":"Solubilità","v":"Insolubile in acqua e in alcol","o":4},
{"n":"Olio di palma","f":"Temperatura di autoaccensione","v":"316°C","o":5},
{"n":"Ortoftalaldeide (OPA)","f":"Formula molecolare","v":"C8H6O2","o":0},
{"n":"Ortoftalaldeide (OPA)","f":"Peso molecolare","v":"134,13 g/mol","o":1},
{"n":"Ortoftalaldeide (OPA)","f":"Purezza","v":">99,0% (GC)","o":2},
{"n":"Ortoftalaldeide (OPA)","f":"Aspetto","v":"Polvere/cristalli da giallo chiaro a giallo/verde","o":3},
{"n":"Ortoftalaldeide (OPA)","f":"Punto di fusione","v":"55,0-58,0°C (spec.); 56°C (riferimento)","o":4},
{"n":"Ortoftalaldeide (OPA)","f":"Punto di ebollizione","v":"84°C a 0,8 mmHg","o":5},
{"n":"Ortoftalaldeide (OPA)","f":"Solubilità","v":"Solubile in metanolo","o":6},
{"n":"Ortoftalaldeide (OPA)","f":"Condizioni di stoccaggio","v":"Temperatura ambiente, luogo fresco e buio (<15°C), sensibile all'aria, conservare sotto gas inerte","o":7},
{"n":"Ossido di cromo verde","f":"Formula","v":"Cr2O3","o":0},
{"n":"Ossido di cromo verde","f":"Peso molecolare","v":"151,99 g/mol","o":1},
{"n":"Ossido di cromo verde","f":"Aspetto","v":"Polvere di colore verde","o":2},
{"n":"Ossido di cromo verde","f":"Punto di fusione","v":"2.435°C","o":3},
{"n":"Ossido di cromo verde","f":"Punto di ebollizione","v":"4.000°C","o":4},
{"n":"Ossido di cromo verde","f":"Densità relativa","v":"5,210 g/cm3","o":5},
{"n":"Ossido di cromo verde","f":"Solubilità in acqua","v":"Insolubile","o":6},
{"n":"Ossido di cromo verde","f":"Note stoccaggio","v":"Igroscopico, conservare sotto gas inerte","o":7},
{"n":"Ossido di etilene","f":"Formula molecolare","v":"C₂H₄O","o":0},
{"n":"Ossido di etilene","f":"Peso molecolare","v":"44.05","o":1},
{"n":"Ossido di etilene","f":"Assay (calcolato)","v":"≥ 99.97 wt%","o":2},
{"n":"Ossido di etilene","f":"Aldeidi (come acetaldeide)","v":"≤ 50 ppm","o":3},
{"n":"Ossido di etilene","f":"Anidride carbonica","v":"≤ 10 ppm","o":4},
{"n":"Ossido di etilene","f":"Formaldeide","v":"≤ 15 ppm","o":5},
{"n":"Ossido di etilene","f":"Contenuto d'acqua","v":"≤ 0.02 wt%","o":6},
{"n":"Ossido di etilene","f":"Colore","v":"Incolore","o":7},
{"n":"Ossido di etilene","f":"Odore","v":"Inodore","o":8},
{"n":"Ossido di etilene","f":"Punto di fusione/congelamento (1013 hPa)","v":"-111 °C","o":9},
{"n":"Ossido di etilene","f":"Punto di ebollizione (1013 hPa)","v":"10.7 °C","o":10},
{"n":"Ossido di etilene","f":"Punto di infiammabilità (1013 hPa)","v":"-57 °C","o":11},
{"n":"Ossido di etilene","f":"Densità (10 °C)","v":"890 kg/m³","o":12},
{"n":"Ossido di etilene","f":"Densità relativa (10.5 °C)","v":"0.88","o":13},
{"n":"Ossido di etilene","f":"Viscosità dinamica (10 °C)","v":"0.254 mPa·s","o":14},
{"n":"Ossido di etilene","f":"Solubilità in acqua (20 °C)","v":"Solubile","o":15},
{"n":"Ossido di ferro giallo","f":"Composizione chimica","v":"Idrossido di ferro sintetico α-FeOOH","o":0},
{"n":"Ossido di ferro giallo","f":"Colour Index","v":"Pigment Yellow 42 (77492)","o":1},
{"n":"Ossido di ferro giallo","f":"Forma di fornitura","v":"Polvere","o":2},
{"n":"Ossido di ferro giallo","f":"Contenuto idrosolubile","v":"max 0.5%","o":3},
{"n":"Ossido di ferro giallo","f":"Residuo al setaccio (0.045 mm)","v":"max 0.04%","o":4},
{"n":"Ossido di ferro giallo","f":"pH","v":"3.5 - 7.5","o":5},
{"n":"Ossido di ferro giallo","f":"Contenuto α-FeOOH","v":"53 - 99.4%","o":6},
{"n":"Ossido di ferro giallo","f":"Perdita all'incenerimento (1000 °C, 0.5 h)","v":"3 - < 14.0%","o":7},
{"n":"Ossido di ferro giallo","f":"Umidità (dopo produzione)","v":"< 0.5%","o":8},
{"n":"Ossido di ferro giallo","f":"Forma particella","v":"A bastoncino","o":9},
{"n":"Ossido di ferro giallo","f":"Dimensione particella tipica","v":"0.1 x 0.6 μm","o":10},
{"n":"Ossido di ferro giallo","f":"Assorbimento olio","v":"~ 60 g/100 g","o":11},
{"n":"Ossido di ferro giallo","f":"Densità apparente (tamped)","v":"0.2 - 0.6 g/ml","o":12},
{"n":"Ossido di ferro giallo","f":"Densità","v":"~ 4.0 g/ml","o":13},
{"n":"Ossido di ferro giallo","f":"Shelf life","v":"10 anni dalla produzione","o":14},
{"n":"Ossido di ferro nero","f":"Composizione chimica","v":"Ossido di ferro sintetico Fe₃O₄","o":0},
{"n":"Ossido di ferro nero","f":"Colour Index","v":"Pigment Black 11 (77499)","o":1},
{"n":"Ossido di ferro nero","f":"Forma di fornitura","v":"Polvere","o":2},
{"n":"Ossido di ferro nero","f":"Finezza di macinazione","v":"30/50/75 μm","o":3},
{"n":"Ossido di ferro nero","f":"Contenuto idrosolubile","v":"max 0.7%","o":4},
{"n":"Ossido di ferro nero","f":"Residuo al setaccio (0.045 mm)","v":"max 0.005%","o":5},
{"n":"Ossido di ferro nero","f":"pH","v":"4.0 - 8.0","o":6},
{"n":"Ossido di ferro nero","f":"Contenuto Fe₃O₄","v":"53 - 96.8%","o":7},
{"n":"Ossido di ferro nero","f":"Perdita all'incenerimento (1000 °C, 0.5 h)","v":"5 - < 5%","o":8},
{"n":"Ossido di ferro nero","f":"Umidità (dopo produzione)","v":"< 2.5%","o":9},
{"n":"Ossido di ferro nero","f":"Forma particella","v":"Sferica","o":10},
{"n":"Ossido di ferro nero","f":"Dimensione particella tipica","v":"~ 0.2 μm","o":11},
{"n":"Ossido di ferro nero","f":"Assorbimento olio","v":"~ 21 g/100 g","o":12},
{"n":"Ossido di ferro nero","f":"Densità apparente (tamped)","v":"0.8 - 1.2 g/ml","o":13},
{"n":"Ossido di ferro nero","f":"Densità","v":"~ 4.6 g/ml","o":14},
{"n":"Ossido di ferro nero","f":"Shelf life","v":"10 anni dalla produzione","o":15},
{"n":"Ossido di ferro rosso","f":"Composizione chimica","v":"Ossido di ferro sintetico α-Fe₂O₃ (High Performance micronizzato)","o":0},
{"n":"Ossido di ferro rosso","f":"Colour Index","v":"Pigment Red 101 (77491)","o":1},
{"n":"Ossido di ferro rosso","f":"Finezza di macinazione","v":"15/30/40 μm","o":2},
{"n":"Ossido di ferro rosso","f":"Contenuto idrosolubile","v":"max 0.4%","o":3},
{"n":"Ossido di ferro rosso","f":"Residuo al setaccio (0.045 mm)","v":"max 0.002%","o":4},
{"n":"Ossido di ferro rosso","f":"pH","v":"5 - 8","o":5},
{"n":"Ossido di ferro rosso","f":"Contenuto α-Fe₂O₃","v":"53 - 99.2%","o":6},
{"n":"Ossido di ferro rosso","f":"Perdita all'incenerimento (1000 °C, 0.5 h)","v":"< 0.7%","o":7},
{"n":"Ossido di ferro rosso","f":"Umidità (dopo produzione)","v":"< 0.3%","o":8},
{"n":"Ossido di ferro rosso","f":"Forma particella","v":"Sferica","o":9},
{"n":"Ossido di ferro rosso","f":"Dimensione particella tipica","v":"~ 0.17 μm","o":10},
{"n":"Ossido di ferro rosso","f":"Assorbimento olio","v":"~ 27 g/100 g","o":11},
{"n":"Ossido di ferro rosso","f":"Densità apparente (tamped)","v":"0.7 - 1.1 g/ml","o":12},
{"n":"Ossido di ferro rosso","f":"Densità","v":"~ 5.0 g/ml","o":13},
{"n":"Ossido di ferro rosso","f":"Shelf life","v":"10 anni dalla produzione","o":14},
{"n":"Ossido di magnesio","f":"Grado","v":"KP - Tecnico, alta purezza","o":0},
{"n":"Ossido di magnesio","f":"Contenuto MgO (per differenza)","v":"98.0% min (tipico 99.0%)","o":1},
{"n":"Ossido di magnesio","f":"Calcio (come CaO)","v":"max 0.60% (tipico 0.30%)","o":2},
{"n":"Ossido di magnesio","f":"Silicio (come SiO₂)","v":"max 0.10% (tipico 0.03%)","o":3},
{"n":"Ossido di magnesio","f":"Ferro (come Fe₂O₃)","v":"max 0.015% (tipico 0.010%)","o":4},
{"n":"Ossido di magnesio","f":"Solfati (come SO₄)","v":"max 0.15% (tipico 0.12%)","o":5},
{"n":"Ossido di magnesio","f":"Cloruri (come Cl)","v":"max 0.25% (tipico 0.15%)","o":6},
{"n":"Ossido di magnesio","f":"Perdita all'incenerimento (900 °C)","v":"max 2.0% (tipico 0.5%)","o":7},
{"n":"Ossido di magnesio","f":"Densità apparente (tapped)","v":"0.60 g/cc","o":8},
{"n":"Ossido di magnesio","f":"Granulometria - Residuo a 100 mesh","v":"max 5.0% (tipico 1.0%)","o":9},
{"n":"Ossido di magnesio","f":"Granulometria - Residuo a 325 mesh","v":"max 30.0% (tipico 35.0%)","o":10},
{"n":"Ossido di magnesio","f":"Aspetto","v":"Polvere fine bianca","o":11},
{"n":"Ossido di magnesio","f":"Solubilità","v":"Quasi insolubile in acqua e alcool; solubile in acidi minerali diluiti","o":12},
{"n":"Ossido di magnesio","f":"Shelf life","v":"2 anni dalla data di produzione","o":13},
{"n":"Ossido di zinco","f":"Aspetto","v":"Polvere bianca","o":0},
{"n":"Ossido di zinco","f":"Odore","v":"Inodore","o":1},
{"n":"Ossido di zinco","f":"pH","v":"6.72","o":2},
{"n":"Ossido di zinco","f":"Punto di fusione","v":"1000 °C","o":3},
{"n":"Ossido di zinco","f":"Densità relativa (22 °C)","v":"5.68","o":4},
{"n":"Ossido di zinco","f":"Densità","v":"5.68 g/cm³","o":5},
{"n":"Ossido di zinco","f":"Solubilità in acqua (20 °C)","v":"0.0029 g/l (leggermente solubile)","o":6},
{"n":"Ossido di zinco","f":"Peso molecolare","v":"81.39 g/mol","o":7},
{"n":"Ossido di zinco","f":"Composizione (Sez. 3 SDS)","v":"Ossido di zinco ≥80 - ≤100%","o":8},
{"n":"Ossigeno","f":"Formula chimica","v":"O₂","o":0},
{"n":"Ossigeno","f":"Purezza (Ossigeno chimico 3.5)","v":"≥ 99.95%","o":1},
{"n":"Ossigeno","f":"Purezza (Ossigeno per strumenti 5.0)","v":"≥ 99.999%","o":2},
{"n":"Ossigeno","f":"Purezza (HiQ ossigeno 6.0)","v":"≥ 99.9999%","o":3},
{"n":"Ossigeno","f":"Acqua (H₂O)","v":"≤ 5 / ≤ 3 / ≤ 0.5 ppm (a seconda del grado)","o":4},
{"n":"Ossigeno","f":"Idrocarburi totali","v":"≤ 0.2 / ≤ 0.1 ppm","o":5},
{"n":"Ossigeno","f":"Monossido di carbonio","v":"≤ 0.1 ppm","o":6},
{"n":"Ossigeno","f":"Anidride carbonica","v":"≤ 0.1 ppm","o":7},
{"n":"Ossigeno","f":"Azoto","v":"≤ 5 / ≤ 0.5 ppm","o":8},
{"n":"Ossigeno","f":"Argon","v":"≤ 3 / ≤ 1 ppm","o":9},
{"n":"Ossigeno","f":"Pressione di riempimento","v":"200 bar","o":10},
{"n":"Ossigeno","f":"Caratteristiche","v":"Gas compresso, comburente","o":11},
{"n":"Pantenolo (provitamina B5)","f":"Formula molecolare","v":"C₉H₁₉NO₄","o":0},
{"n":"Pantenolo (provitamina B5)","f":"Peso molecolare","v":"205.3 g/mol","o":1},
{"n":"Pantenolo (provitamina B5)","f":"Conformità farmacopea","v":"Ph.Eur.","o":2},
{"n":"Pantenolo (provitamina B5)","f":"Aspetto","v":"Liquido da incolore a leggermente giallo, viscosità molto elevata","o":3},
{"n":"Pantenolo (provitamina B5)","f":"Solubilità","v":"Molto idrofilo, ben solubile in acqua","o":4},
{"n":"Pantenolo (provitamina B5)","f":"Shelf life","v":"36 mesi dalla produzione (se conservato correttamente)","o":5},
{"n":"Pantenolo (provitamina B5)","f":"Packaging disponibile","v":"Fusto HDPE 25 kg / 20 kg; campione tecnico 0.25 kg","o":6},
{"n":"Pantenolo (provitamina B5)","f":"Note di stoccaggio","v":"Igroscopico e fotosensibile, conservare in confezione sigillata","o":7},
{"n":"PBT","f":"Polimero","v":"PBT (Ultradur B4520, non colorato)","o":0},
{"n":"PBT","f":"Densità","v":"1300 kg/m³ (ISO 1183)","o":1},
{"n":"PBT","f":"Indice di viscosità (soluzione)","v":"130 cm³/g","o":2},
{"n":"PBT","f":"Assorbimento d'acqua (equilibrio, 23 °C)","v":"0.5%","o":3},
{"n":"PBT","f":"Assorbimento umidità (23 °C/50% u.r.)","v":"0.25%","o":4},
{"n":"PBT","f":"Indice di fluidità MVR (250 °C, 2.16 kg)","v":"20 cm³/10min","o":5},
{"n":"PBT","f":"Temperatura di fusione (DSC)","v":"223 °C","o":6},
{"n":"PBT","f":"Temperatura di stampaggio (iniezione/estrusione)","v":"250 - 275 °C","o":7},
{"n":"PBT","f":"Temperatura stampo","v":"40 - 70 °C","o":8},
{"n":"PBT","f":"Ritiro allo stampaggio","v":"1.70%","o":9},
{"n":"PBT","f":"Infiammabilità (1.5 mm, IEC 60695-11-10)","v":"Classe HB","o":10},
{"n":"PBT","f":"Indice di ossigeno","v":"20%","o":11},
{"n":"PBT","f":"Modulo a trazione","v":"2400 MPa","o":12},
{"n":"PBT","f":"Sforzo a snervamento (50 mm/min)","v":"55 MPa","o":13},
{"n":"PBT","f":"Allungamento a rottura","v":"> 50%","o":14},
{"n":"PBT","f":"Resilienza Charpy con intaglio (23 °C)","v":"5 kJ/m²","o":15},
{"n":"PBT","f":"Modulo a flessione","v":"2400 MPa","o":16},
{"n":"PBT","f":"Resistenza a flessione","v":"85 MPa","o":17},
{"n":"PBT","f":"HDT A (1.80 MPa)","v":"55 °C","o":18},
{"n":"PBT","f":"HDT B (0.45 MPa)","v":"165 °C","o":19},
{"n":"PBT","f":"Temperatura massima di servizio (breve)","v":"200 °C","o":20},
{"n":"Pectina","f":"Fonte biologica","v":"Agrumi (bucce)","o":0},
{"n":"Pectina","f":"Forma","v":"Polvere","o":1},
{"n":"Pectina","f":"Composizione (acido galatturonico)","v":"≥ 74.0% (base secca)","o":2},
{"n":"Pectina","f":"Impurezze (umidità)","v":"≤ 10%","o":3},
{"n":"Pectina","f":"Colore","v":"Marrone chiaro","o":4},
{"n":"Pectina","f":"Temperatura di stoccaggio","v":"Ambiente","o":5},
{"n":"Pectina","f":"Classe di stoccaggio","v":"11 - Solidi combustibili","o":6},
{"n":"PEEK","f":"Grado","v":"Victrex PEEK Polymer 450G (non rinforzato, flusso standard)","o":0},
{"n":"PEEK","f":"Densità (cristallina)","v":"1.30 g/cm³ (ISO 1183)","o":1},
{"n":"PEEK","f":"Assorbimento d'acqua (saturazione, 23 °C)","v":"0.45%","o":2},
{"n":"PEEK","f":"Assorbimento d'acqua (saturazione, 100 °C)","v":"0.55%","o":3},
{"n":"PEEK","f":"Modulo a trazione (23 °C)","v":"4000 MPa","o":4},
{"n":"PEEK","f":"Sforzo a snervamento (23 °C)","v":"98.0 MPa","o":5},
{"n":"PEEK","f":"Allungamento a rottura (23 °C)","v":"25%","o":6},
{"n":"PEEK","f":"Modulo a flessione (23 °C)","v":"3800 MPa","o":7},
{"n":"PEEK","f":"Resilienza Charpy con intaglio (23 °C)","v":"7.0 kJ/m²","o":8},
{"n":"PEEK","f":"Durezza Shore D (23 °C)","v":"84.5","o":9},
{"n":"PEEK","f":"Temperatura di transizione vetrosa (Tg)","v":"143 - 150 °C","o":10},
{"n":"PEEK","f":"Temperatura di fusione","v":"343 °C","o":11},
{"n":"PEEK","f":"HDT (1.8 MPa, non ricotto)","v":"152 °C","o":12},
{"n":"PEEK","f":"Viscosità di fusione (400 °C)","v":"350 Pa·s","o":13},
{"n":"PEEK","f":"Temperatura di essiccamento consigliata","v":"120 - 150 °C, 3-5 h","o":14},
{"n":"PEEK","f":"Umidità massima consigliata prima di stampaggio","v":"0.020%","o":15},
{"n":"Perborato di sodio","f":"Formula molecolare (forma tetraidrata)","v":"B Na O₃ · 4 H₂O","o":0},
{"n":"Perborato di sodio","f":"Peso molecolare (forma tetraidrata)","v":"153.86","o":1},
{"n":"Perborato di sodio","f":"Aspetto","v":"Solido in polvere, bianco, inodore","o":2},
{"n":"Perborato di sodio","f":"pH (soluzione 1%)","v":"10.4","o":3},
{"n":"Perborato di sodio","f":"Punto di fusione/rammollimento","v":"60 °C","o":4},
{"n":"Perborato di sodio","f":"Densità (forma tetraidrata)","v":"1.731 g/cm³","o":5},
{"n":"Perborato di sodio","f":"Solubilità in acqua (18 °C)","v":"21.5 g/l","o":6},
{"n":"Perborato di sodio","f":"Temperatura di decomposizione","v":"150 - 400 °C","o":7},
{"n":"Perborato di sodio","f":"Composizione (Sez. 3 SDS)","v":"Perborato di sodio tetraidrato >95%; Perborato di sodio (7632-04-4) presente come componente","o":8},
{"n":"Percarbonato di sodio","f":"Formula chimica","v":"2Na₂CO₃ · 3H₂O₂","o":0},
{"n":"Percarbonato di sodio","f":"Aspetto","v":"Polvere granulare bianca, a scorrimento libero","o":1},
{"n":"Percarbonato di sodio","f":"Odore","v":"Inodore","o":2},
{"n":"Percarbonato di sodio","f":"Solubilità","v":"Facilmente solubile in acqua","o":3},
{"n":"Percarbonato di sodio","f":"Comportamento termico","v":"Decomposizione autoaccelerante oltre 50 °C; max 110 °C con rilascio O₂/vapore","o":4},
{"n":"Percloroetilene","f":"Grado","v":"Tecnico (Sales Specification)","o":0},
{"n":"Percloroetilene","f":"Colore (APHA)","v":"max 15","o":1},
{"n":"Percloroetilene","f":"Peso specifico (25/25 °C)","v":"1.617 - 1.621","o":2},
{"n":"Percloroetilene","f":"Residuo non volatile","v":"max 10 ppm","o":3},
{"n":"Percloroetilene","f":"Contenuto d'acqua","v":"max 30 ppm","o":4},
{"n":"Percloroetilene","f":"Alogeni liberi (ASTM D4755)","v":"Conforme","o":5},
{"n":"Percloroetilene","f":"Intervallo di distillazione (760 mm)","v":"120.6 - 121.6 °C","o":6},
{"n":"Perfosfato triplo (TSP)","f":"Fosfato disponibile (P₂O₅)","v":"45.00%","o":0},
{"n":"Perfosfato triplo (TSP)","f":"Calcio (Ca)","v":"13.50%","o":1},
{"n":"Perfosfato triplo (TSP)","f":"Molibdeno (Mo)","v":"0.001%","o":2},
{"n":"Perfosfato triplo (TSP)","f":"Densità apparente (versata)","v":"59.4 lb/ft³","o":3},
{"n":"Perfosfato triplo (TSP)","f":"Densità apparente (compattata)","v":"62.7 lb/ft³","o":4},
{"n":"Perfosfato triplo (TSP)","f":"pH (soluzione 20%)","v":"3.1","o":5},
{"n":"Perfosfato triplo (TSP)","f":"Solubilità in acqua (% del P₂O₅ totale)","v":"90%","o":6},
{"n":"Perfosfato triplo (TSP)","f":"Granulometria","v":"87% tra 2.00-4.00 mm; dimensione media 2.37 mm","o":7},
{"n":"Perfosfato triplo (TSP)","f":"Angolo di riposo","v":"30°","o":8},
{"n":"Permanganato di potassio","f":"Aspetto","v":"Solido","o":0},
{"n":"Permanganato di potassio","f":"Densità (20 °C)","v":"2.70 g/cm³","o":1},
{"n":"Permanganato di potassio","f":"Peso molecolare","v":"158.03 g/mol","o":2},
{"n":"Permanganato di potassio","f":"Proprietà ossidanti","v":"Categoria 2 (ossidante)","o":3},
{"n":"Permanganato di potassio","f":"Composizione (Sez. 3 SDS)","v":"Permanganato di potassio ≥80 - ≤100%","o":4},
{"n":"Perossido di idrogeno","f":"Grado 35% - Ossigeno attivo","v":"16.5%","o":0},
{"n":"Perossido di idrogeno","f":"Grado 35% - Punto di congelamento","v":"-33 °C","o":1},
{"n":"Perossido di idrogeno","f":"Grado 35% - Punto di ebollizione","v":"108 °C","o":2},
{"n":"Perossido di idrogeno","f":"Grado 35% - Densità (20 °C)","v":"1.13 g/mL","o":3},
{"n":"Perossido di idrogeno","f":"Grado 35% - Viscosità (20 °C)","v":"1.11 cP","o":4},
{"n":"Perossido di idrogeno","f":"Grado 50% - Ossigeno attivo","v":"23.5%","o":5},
{"n":"Perossido di idrogeno","f":"Grado 50% - Punto di congelamento","v":"-52 °C","o":6},
{"n":"Perossido di idrogeno","f":"Grado 50% - Punto di ebollizione","v":"114 °C","o":7},
{"n":"Perossido di idrogeno","f":"Grado 50% - Densità (20 °C)","v":"1.20 g/mL","o":8},
{"n":"Perossido di idrogeno","f":"Grado 50% - Viscosità (20 °C)","v":"1.17 cP","o":9},
{"n":"Perossido di idrogeno","f":"Grado 70% - Ossigeno attivo","v":"32.9%","o":10},
{"n":"Perossido di idrogeno","f":"Grado 70% - Punto di congelamento","v":"-40 °C","o":11},
{"n":"Perossido di idrogeno","f":"Grado 70% - Punto di ebollizione","v":"125 °C","o":12},
{"n":"Perossido di idrogeno","f":"Grado 70% - Densità (20 °C)","v":"1.29 g/mL","o":13},
{"n":"Perossido di idrogeno","f":"Grado 70% - Viscosità (20 °C)","v":"1.24 cP","o":14},
{"n":"Perossimonosolfato di potassio (KMPS)","f":"Componente attivo","v":"KHSO₅ (monopersolfato di potassio), sale triplo 2KHSO₅·KHSO₄·K₂SO₄","o":0},
{"n":"Perossimonosolfato di potassio (KMPS)","f":"Peso molecolare (sale triplo)","v":"614.7","o":1},
{"n":"Perossimonosolfato di potassio (KMPS)","f":"Ossigeno attivo","v":"min 4.5% (media 4.7%; teorico 5.2%)","o":2},
{"n":"Perossimonosolfato di potassio (KMPS)","f":"Componente attivo KHSO₅","v":"min 42.8%","o":3},
{"n":"Perossimonosolfato di potassio (KMPS)","f":"Densità apparente","v":"1.15 - 1.30 g/cm³ (72-81 lb/ft³)","o":4},
{"n":"Perossimonosolfato di potassio (KMPS)","f":"Granulometria (setaccio US #20 / #200)","v":"100% / min 10% passante","o":5},
{"n":"Perossimonosolfato di potassio (KMPS)","f":"pH (soluzione 1% / 3%, 25 °C)","v":"2.3 / 2.0","o":6},
{"n":"Perossimonosolfato di potassio (KMPS)","f":"Solubilità in acqua (20 °C)","v":"256 g/l","o":7},
{"n":"Perossimonosolfato di potassio (KMPS)","f":"Contenuto d'acqua","v":"max 0.1%","o":8},
{"n":"Perossimonosolfato di potassio (KMPS)","f":"Stabilità","v":"< 1% perdita ossigeno attivo/mese","o":9},
{"n":"Perossimonosolfato di potassio (KMPS)","f":"Calore di decomposizione","v":"251 kJ/kg","o":10},
{"n":"Perossimonosolfato di potassio (KMPS)","f":"Conducibilità termica","v":"0.161 W/m·K","o":11},
{"n":"PET riciclato (rPET)","f":"Aspetto","v":"Solido, scaglie trasparenti/colorate","o":0},
{"n":"PET riciclato (rPET)","f":"Odore","v":"Inodore","o":1},
{"n":"PET riciclato (rPET)","f":"Composizione (Sez. 3 SDS)","v":"Polietilene tereftalato >99%; additivi/coloranti <1%","o":2},
{"n":"PET riciclato (rPET)","f":"Peso specifico","v":"1.33 - 1.45 g/cm³","o":3},
{"n":"PET riciclato (rPET)","f":"Punto di fusione","v":"225 - 250 °C","o":4},
{"n":"PET riciclato (rPET)","f":"Solubilità in acqua","v":"Insolubile","o":5},
{"n":"PET riciclato (rPET)","f":"Temperatura di decomposizione","v":"330 °C","o":6},
{"n":"Phenoxyethanol","f":"Aspetto","v":"Liquido incolore, odore debole","o":0},
{"n":"Phenoxyethanol","f":"pH (23 °C)","v":"7","o":1},
{"n":"Phenoxyethanol","f":"Punto di fusione","v":"11 - 13 °C","o":2},
{"n":"Phenoxyethanol","f":"Punto di ebollizione","v":"244 - 246 °C","o":3},
{"n":"Phenoxyethanol","f":"Punto di infiammabilità (chiuso)","v":"126 °C","o":4},
{"n":"Phenoxyethanol","f":"Densità (20 °C)","v":"1.107 g/mL","o":5},
{"n":"Phenoxyethanol","f":"Solubilità in acqua (20.7 °C)","v":"28.6 g/l","o":6},
{"n":"Phenoxyethanol","f":"Coefficiente di ripartizione (log Pow)","v":"1.107","o":7},
{"n":"Phenoxyethanol","f":"Viscosità dinamica (19.8 °C)","v":"41 mPa·s","o":8},
{"n":"Phenoxyethanol","f":"Peso molecolare","v":"138.16 g/mol","o":9},
{"n":"Phenoxyethanol","f":"Tensione superficiale","v":"70.7 mN/m","o":10},
{"n":"Phenoxyethanol","f":"Composizione (Sez. 3 SDS)","v":"2-Phenoxyethanol ≥90 - ≤100%","o":11},
{"n":"PHMB (poliesametilene biguanide)","f":"Composizione (Sez. 3 SDS)","v":"Soluzione acquosa con PHMB 19-21%; acido cloridrico <1%; acqua a saldo","o":0},
{"n":"PHMB (poliesametilene biguanide)","f":"Stato fisico","v":"Liquido","o":1},
{"n":"PHMB (poliesametilene biguanide)","f":"Colore","v":"Incolore, limpido, lievemente opalescente","o":2},
{"n":"PHMB (poliesametilene biguanide)","f":"Odore","v":"Inodore","o":3},
{"n":"PHMB (poliesametilene biguanide)","f":"pH (soluzione 20% PHMB)","v":"4 - 5","o":4},
{"n":"PHMB (poliesametilene biguanide)","f":"Punto di ebollizione","v":"102 - 105 °C","o":5},
{"n":"PHMB (poliesametilene biguanide)","f":"Punto di congelamento","v":"< 6 °C","o":6},
{"n":"PHMB (poliesametilene biguanide)","f":"Densità","v":"1.04 - 1.05 kg/L","o":7},
{"n":"PHMB (poliesametilene biguanide)","f":"Viscosità (20 °C)","v":"1.2 - 10 mPa·s","o":8},
{"n":"PHMB (poliesametilene biguanide)","f":"Pressione di vapore (20 °C)","v":"4 kPa","o":9},
{"n":"PHMB (poliesametilene biguanide)","f":"Solubilità","v":"Miscibile con acqua in tutte le proporzioni; miscibile con alcoli alifatici e glicoli","o":10},
{"n":"PHMB (poliesametilene biguanide)","f":"Temperatura di decomposizione","v":"200 - 300 °C (dopo evaporazione dell'acqua)","o":11},
{"n":"Piombo (lingotti)","f":"Grado - Piombo raffinato puro","v":"99.97% (ASTM B29-03)","o":0},
{"n":"Piombo (lingotti)","f":"Grado - Piombo puro","v":"99.94% (ASTM B29-03)","o":1},
{"n":"Piombo (lingotti)","f":"Grado ballast G2","v":"min 96.5% Pb; 1.5-3% Sb; 0.1-3.5% Sn","o":2},
{"n":"Piombo (lingotti)","f":"Leghe disponibili","v":"Bullion antimoniale 3% (chiglie), 6% (proiettili)","o":3},
{"n":"Piombo (lingotti)","f":"Formati disponibili","v":"Lingotti 10-70 lb; ice cube tray 25 lb; strip 65 lb","o":4},
{"n":"Plastificante DEHP (ftalato)","f":"Nome chimico","v":"Bis(2-etilesil) ftalato (DEHP)","o":0},
{"n":"Plastificante DEHP (ftalato)","f":"Aspetto","v":"Oleoso, incolore, inodore","o":1},
{"n":"Plastificante DEHP (ftalato)","f":"pH","v":"Neutro","o":2},
{"n":"Plastificante DEHP (ftalato)","f":"Punto di fusione","v":"-50 °C","o":3},
{"n":"Plastificante DEHP (ftalato)","f":"Punto di ebollizione","v":"384 °C","o":4},
{"n":"Plastificante DEHP (ftalato)","f":"Punto di infiammabilità (chiuso)","v":"207 °C","o":5},
{"n":"Plastificante DEHP (ftalato)","f":"Pressione di vapore (93 °C)","v":"1.6 hPa","o":6},
{"n":"Plastificante DEHP (ftalato)","f":"Densità (25 °C)","v":"0.985 g/cm³","o":7},
{"n":"Plastificante DEHP (ftalato)","f":"Solubilità in acqua (25 °C)","v":"ca. 0.086 g/l (insolubile)","o":8},
{"n":"Plastificante DEHP (ftalato)","f":"Viscosità dinamica (20 °C)","v":"81 mPa·s","o":9},
{"n":"Plastificante DEHP (ftalato)","f":"Peso molecolare","v":"390.56 g/mol","o":10},
{"n":"Plastificante DEHP (ftalato)","f":"Composizione (Sez. 3 SDS)","v":"Bis(2-etilesil) ftalato ≥80 - ≤100%","o":11},
{"n":"Plastificante DINP","f":"Formula chimica","v":"C₆H₄(COOC₉H₁₉)₂","o":0},
{"n":"Plastificante DINP","f":"Composizione (Sez. 3 SDS)","v":"Diisononil ftalato 99.5%","o":1},
{"n":"Plastificante DINP","f":"Stato fisico","v":"Liquido oleoso","o":2},
{"n":"Plastificante DINP","f":"Colore","v":"Da incolore a giallastro","o":3},
{"n":"Plastificante DINP","f":"Odore","v":"Inodore","o":4},
{"n":"Plastificante DINP","f":"Punto di ebollizione (5 hPa)","v":"≥ 270 - 280 °C","o":5},
{"n":"Plastificante DINP","f":"Punto di fusione","v":"-54 °C","o":6},
{"n":"Plastificante DINP","f":"Punto di infiammabilità","v":"ca. 200 °C","o":7},
{"n":"Plastificante DINP","f":"Temperatura di autoaccensione","v":"ca. 400 °C","o":8},
{"n":"Plastificante DINP","f":"Peso specifico / Densità","v":"0.972 - 0.977 g/cm³","o":9},
{"n":"Plastificante DINP","f":"Pressione di vapore (20 °C)","v":"< 1 Pa","o":10},
{"n":"Plastificante DINP","f":"Solubilità","v":"Insolubile in acqua (<0.01 g/100 ml, 20 °C); solubile in acetone, metanolo, benzene, etere","o":11},
{"n":"Plastificante non-ftalico (DOTP)","f":"Formula molecolare","v":"C24H38O4","o":0},
{"n":"Plastificante non-ftalico (DOTP)","f":"Peso molecolare","v":"390,57 (teorico)","o":1},
{"n":"Plastificante non-ftalico (DOTP)","f":"Densità (peso specifico 20°C/20°C)","v":"0,9835","o":2},
{"n":"Plastificante non-ftalico (DOTP)","f":"Viscosità (25°C)","v":"49 cP","o":3},
{"n":"Plastificante non-ftalico (DOTP)","f":"Punto di infiammabilità (COC)","v":"238 °C","o":4},
{"n":"Plastificante non-ftalico (DOTP)","f":"Punto di ebollizione (760 mmHg)","v":"375 °C","o":5},
{"n":"PMMA (acrilico)","f":"Densità","v":"1,19 g/cm³","o":0},
{"n":"PMMA (acrilico)","f":"Indice di fluidità (MFI)","v":"3,0 g/10min","o":1},
{"n":"PMMA (acrilico)","f":"Temperatura Vicat (B50)","v":"fino a 108 °C","o":2},
{"n":"PMMA (acrilico)","f":"Resistenza a trazione","v":"70 MPa","o":3},
{"n":"PMMA (acrilico)","f":"Trasmittanza luminosa","v":"92%","o":4},
{"n":"Poli-DADMAC","f":"Contenuto solidi non volatili","v":"19-22%","o":0},
{"n":"Poli-DADMAC","f":"Viscosità Brookfield","v":"700-1000 cps","o":1},
{"n":"Poli-DADMAC","f":"pH","v":"5,0-7,0","o":2},
{"n":"Poli-DADMAC","f":"Peso specifico","v":"1,02-1,07","o":3},
{"n":"Poli-DADMAC","f":"Densità di carica","v":"Molto alta","o":4},
{"n":"Poli-DADMAC","f":"Shelf life","v":"24 mesi","o":5},
{"n":"Poli-DADMAC","f":"Temperatura di stoccaggio","v":"0-35 °C","o":6},
{"n":"Poli-DADMAC","f":"Punto di congelamento","v":"< -3 °C","o":7},
{"n":"Poliacrilammide (flocculante)","f":"Peso molecolare (gamma prodotti)","v":"5-15 milioni","o":0},
{"n":"Poliacrilammide (flocculante)","f":"Anionicità (gamma prodotti)","v":"0-50%","o":1},
{"n":"Poliacrilammide (flocculante)","f":"Aspetto (grado polvere)","v":"Granuli liberi, igroscopici","o":2},
{"n":"Poliammide 6 (Nylon 6)","f":"Densità","v":"1130 kg/m³ (ISO 1183)","o":0},
{"n":"Poliammide 6 (Nylon 6)","f":"Punto di fusione (DSC)","v":"220 °C (ISO 11357)","o":1},
{"n":"Poliammide 6 (Nylon 6)","f":"Temperatura di lavorazione (fusione)","v":"250-270 °C","o":2},
{"n":"Poliammide 6 (Nylon 6)","f":"Numero di viscosità (0,5% in H2SO4 96%)","v":"145 cm³/g (ISO 307/1157/1628)","o":3},
{"n":"Poliammide 6 (Nylon 6)","f":"MVR (275°C/5kg)","v":"160 cm³/10min (ISO 1133)","o":4},
{"n":"Poliammide 6 (Nylon 6)","f":"Assorbimento umidità equilibrio (23°C/50%UR)","v":"2,6-3,4% (ISO 62)","o":5},
{"n":"Poliammide 6 (Nylon 6)","f":"Assorbimento acqua a saturazione","v":"9-10%","o":6},
{"n":"Poliammide 6 (Nylon 6)","f":"Umidità raccomandata pre-lavorazione","v":"0,03-0,06%","o":7},
{"n":"Poliammide 6 (Nylon 6)","f":"Densità apparente (granuli)","v":"~0,7 g/cm³","o":8},
{"n":"Poliammide 66 (PA66)","f":"Descrizione prodotto","v":"Grado ad iniezione facile scorrimento, non rinforzato","o":0},
{"n":"Poliammide 66 (PA66)","f":"Densità apparente (granuli)","v":"~0,7 g/cm³","o":1},
{"n":"Policarbonato (PC)","f":"Densità (valori tipici gamma Makrolon)","v":"1200 kg/m³","o":0},
{"n":"Policarbonato (PC)","f":"Temperatura Vicat (50N, 50°C/h, ISO 306)","v":"145 °C","o":1},
{"n":"Policarbonato (PC)","f":"Resistenza Izod con intaglio (23°C, 3mm)","v":"50 kJ/m²","o":2},
{"n":"Policarbonato (PC)","f":"MVR (300°C/1,2kg, esempio grado standard)","v":"6-12 cm³/10min","o":3},
{"n":"Policloruro di alluminio (PAC)","f":"Aspetto","v":"Liquido, da incolore/ambra a giallo chiaro","o":0},
{"n":"Policloruro di alluminio (PAC)","f":"pH","v":"0,5-4,4","o":1},
{"n":"Policloruro di alluminio (PAC)","f":"Densità","v":"1,34-1,40 g/cm³ (25°C)","o":2},
{"n":"Policloruro di alluminio (PAC)","f":"Contenuto Al2O3","v":"17,1 ± 0,4%","o":3},
{"n":"Policloruro di alluminio (PAC)","f":"Punto di ebollizione","v":"105-115 °C","o":4},
{"n":"Policloruro di alluminio (PAC)","f":"Punto di cristallizzazione","v":"-10 °C","o":5},
{"n":"Polietilene alta densita (HDPE)","f":"Indice di fluidità (190°C/21,6kg)","v":"8,5 g/10min (ASTM D1238)","o":0},
{"n":"Polietilene alta densita (HDPE)","f":"Densità","v":"0,949 g/cm³ (ASTM D792)","o":1},
{"n":"Polietilene alta densita (HDPE)","f":"Resistenza a trazione a rottura (MD/TD)","v":"60/50 MPa","o":2},
{"n":"Polietilene alta densita (HDPE)","f":"Allungamento a rottura (MD/TD)","v":"18/47%","o":3},
{"n":"Polietilene alta densita (HDPE)","f":"Modulo a trazione","v":"416 MPa","o":4},
{"n":"Polietilene bassa densita (LDPE)","f":"Densità","v":"0,922 g/cm³","o":0},
{"n":"Polietilene bassa densita (LDPE)","f":"Indice di fluidità (190°C/2,16kg)","v":"2 g/10min","o":1},
{"n":"Polietilene bassa densita (LDPE)","f":"Spessore film tipico","v":"25/20 μm","o":2},
{"n":"Polietilene bassa densita (LDPE)","f":"Additivi","v":"Slip 500 ppm, antiblocking 750 ppm","o":3},
{"n":"Polietilene tereftalato (PET)","f":"Viscosità intrinseca (IV)","v":"0,80 ± 0,02 dl/g","o":0},
{"n":"Polietilene tereftalato (PET)","f":"Densità","v":"1,4 g/cc","o":1},
{"n":"Polietilene tereftalato (PET)","f":"Punto di fusione","v":"247 ± 2,0 °C","o":2},
{"n":"Polietilene tereftalato (PET)","f":"Acetaldeide residua","v":"max 1 ppm","o":3},
{"n":"Polietilene tereftalato (PET)","f":"Colore L*","v":"min 82","o":4},
{"n":"Polietilene tereftalato (PET)","f":"Peso pellet","v":"65 ± 5 pezzi/g","o":5},
{"n":"Polietilene tereftalato (PET)","f":"Fini (particelle fini)","v":"max 0,05% in peso","o":6},
{"n":"Polipropilene (PP)","f":"Densità","v":"0,90 g/cm³","o":0},
{"n":"Polipropilene (PP)","f":"Indice di fluidità (230°C/2,16kg)","v":"25 g/10min","o":1},
{"n":"Polipropilene (PP)","f":"Resistenza a trazione allo snervamento","v":"32 MPa","o":2},
{"n":"Polipropilene (PP)","f":"Allungamento a rottura","v":">50%","o":3},
{"n":"Polipropilene (PP)","f":"Resilienza Charpy con intaglio","v":"2 kJ/m²","o":4},
{"n":"Polisorbato 80 (Tween 80)","f":"Valore HLB","v":"15,0","o":0},
{"n":"Polisorbato 80 (Tween 80)","f":"Viscosità Brookfield (25°C)","v":"400-620 cps","o":1},
{"n":"Polisorbato 80 (Tween 80)","f":"Peso specifico (25°C)","v":"1,07","o":2},
{"n":"Polisorbato 80 (Tween 80)","f":"Indice di idrossile","v":"65-80","o":3},
{"n":"Polisorbato 80 (Tween 80)","f":"Indice di saponificazione","v":"45-55","o":4},
{"n":"Polistirene (PS)","f":"Indice di fluidità (200°C/5kg)","v":"1,5 g/10min (ASTM D1238)","o":0},
{"n":"Polistirene (PS)","f":"Descrizione","v":"Polistirene cristallo \"high heat\", senza additivi, idoneo contatto alimentare","o":1},
{"n":"Polistirene espandibile (EPS)","f":"Granulometria (diametro perline)","v":"0,9-1,3 mm","o":0},
{"n":"Polistirene espandibile (EPS)","f":"Densità apparente in applicazione","v":"10-30 kg/m³ (tipico 15 kg/m³)","o":1},
{"n":"Polistirene espandibile (EPS)","f":"Contenuto pentano","v":"~6,0%","o":2},
{"n":"Polistirene espandibile (EPS)","f":"Tempo di maturazione intermedia","v":"10-48 ore","o":3},
{"n":"Polivinilcloruro (PVC)","f":"Descrizione prodotto","v":"Omopolimero PVC a peso molecolare medio-basso per estrusione rigida","o":0},
{"n":"Polivinilcloruro (PVC)","f":"Classificazione ASTM","v":"GP4-15000","o":1},
{"n":"Polivinilcloruro (PVC)","f":"Caratteristiche","v":"Alta densità apparente, ottima scorrevolezza a secco","o":2}]$j$::jsonb) as x(n text, f text, v text, o int);
  select md5(string_agg(rh, '' order by rh collate "C")) into got from (select md5(n||chr(31)||f||chr(31)||v||chr(31)||o::text) as rh from _stg_specs) q;
  if got is distinct from expected then
    raise exception 'specs batch 3 integrity check failed: expected % got %', expected, got;
  end if;
  insert into public.product_specs (product_id, campo, valore, ordine)
  select p.id, s.f, s.v, s.o from _stg_specs s join public.products p on lower(btrim(p.canonical_name)) = lower(btrim(s.n));
  get diagnostics n_ins = row_count;
  raise notice 'specs batch 3: staged=%, inserted=%', (select count(*) from _stg_specs), n_ins;
end
$mig$;
