-- Part B (batch 2/4): import specifiche in public.product_specs. Match SOLO per nome.
-- 'ordine' 0-based per prodotto (precalcolato). Righe 'Nessun dato' escluse. Integrity guard MD5.
do $mig$
declare
  expected text := 'e519ba375a2f6050603970fb1852dee5';
  got text;
  n_ins int;
begin
  create temp table _stg_specs on commit drop as select n, f, v, (o)::int as o from jsonb_to_recordset($j$[{"n":"Biossido di titanio (rutilo)","f":"Valore di rigonfiamento (bulking value)","v":"0,25 L/kg (0,03 gal/lb)","o":2},
{"n":"Biossido di titanio (rutilo)","f":"Trattamento superficiale","v":"Allumina e silice amorfa; trattamento organico","o":3},
{"n":"Biossido di titanio (rutilo)","f":"Colore (CIE L*)","v":"99,6","o":4},
{"n":"Biossido di titanio (rutilo)","f":"Granulometria (dimensione media particella)","v":"0,405 µm","o":5},
{"n":"Biossido di titanio (rutilo)","f":"Assorbimento olio","v":"16,2","o":6},
{"n":"Biossido di titanio (rutilo)","f":"pH","v":"7,9","o":7},
{"n":"Biossido di titanio (rutilo)","f":"Resistività (30°C)","v":"8,1 (1000 ohm)","o":8},
{"n":"Biossido di titanio (rutilo)","f":"Packaging disponibile","v":"Sacchi carta 25 kg; big bag 1 t; slurry in autocisterna (15 t) o vagone (67 t), in alcune regioni","o":9},
{"n":"Biossido di titanio (rutilo)","f":"Shelf life","v":"Indefinita, se protetto dal contatto diretto con umidità","o":10},
{"n":"Bisabololo","f":"Nome chimico","v":"1-Metil-4-(1,5-dimetil-1-idrossiesa-4(5)-enil)cicloesene (alpha-Bisabololo)","o":0},
{"n":"Bisabololo","f":"Purezza (area %)","v":">85%","o":1},
{"n":"Bisabololo","f":"Peso molecolare","v":"222,4 g/mol","o":2},
{"n":"Bisabololo","f":"Indice di rifrazione n(D/20)","v":"1,492–1,498","o":3},
{"n":"Bisabololo","f":"Aspetto","v":"Liquido limpido, da incolore a leggermente giallastro","o":4},
{"n":"Bisabololo","f":"Stabilità pH","v":"Stabile in formulazioni pH 3–11","o":5},
{"n":"Bisabololo","f":"Solubilità","v":"Solubile in etanolo, isopropanolo, oli/grassi naturali/minerali/sintetici; insolubile in acqua e glicerolo","o":6},
{"n":"Bisabololo","f":"Shelf life","v":"Almeno 24 mesi (contenitori originali sigillati, max 20°C, luogo asciutto)","o":7},
{"n":"Bisfenolo A (BPA)","f":"Peso molecolare","v":"228,29 g/mol","o":0},
{"n":"Bisfenolo A (BPA)","f":"Aspetto","v":"Cristallino, beige, inodore","o":1},
{"n":"Bisfenolo A (BPA)","f":"Punto di fusione","v":"158–159°C","o":2},
{"n":"Bisfenolo A (BPA)","f":"Punto di ebollizione","v":"220°C (5 hPa)","o":3},
{"n":"Bisfenolo A (BPA)","f":"Flash point","v":"227°C (crogiolo chiuso)","o":4},
{"n":"Bisfenolo A (BPA)","f":"Densità relativa (25°C)","v":"1,2","o":5},
{"n":"Bisfenolo A (BPA)","f":"Solubilità in acqua","v":"0,298 g/l (25°C)","o":6},
{"n":"Bisfenolo A (BPA)","f":"Log Pow","v":"3,4 (21,5°C)","o":7},
{"n":"Bisfenolo A (BPA)","f":"Temperatura di autoaccensione","v":"510°C","o":8},
{"n":"Bisolfito di sodio","f":"Concentrazione (sodio idrogeno solfito)","v":"30,0–60,0% p/p in soluzione acquosa","o":0},
{"n":"Bisolfito di sodio","f":"Aspetto","v":"Liquido, soluzione acquosa, da incolore a giallo","o":1},
{"n":"Bisolfito di sodio","f":"Odore","v":"Pungente","o":2},
{"n":"Bisolfito di sodio","f":"pH","v":"3,5–5,0","o":3},
{"n":"Bisolfito di sodio","f":"Punto di fusione/cristallizzazione","v":"<5°C","o":4},
{"n":"Bisolfito di sodio","f":"Punto di ebollizione","v":"100°C (1013 mbar)","o":5},
{"n":"Bisolfito di sodio","f":"Densità (20°C)","v":"1,325 g/cm³","o":6},
{"n":"Bisolfito di sodio","f":"Viscosità dinamica (20°C)","v":"3,64 mPa·s","o":7},
{"n":"Bisolfito di sodio","f":"Solubilità in acqua","v":"Circa 515 g/l (20°C)","o":8},
{"n":"Bitartrato di potassio","f":"Formula molecolare","v":"KHC4H4O6","o":0},
{"n":"Bitartrato di potassio","f":"Peso molecolare","v":"188,19 g/mol","o":1},
{"n":"Bitartrato di potassio","f":"Aspetto","v":"Polvere cristallina incolore o bianca, inodore","o":2},
{"n":"Bitartrato di potassio","f":"pH (soluzione acquosa 1%)","v":"3,5–4,0","o":3},
{"n":"Bitartrato di potassio","f":"Densità relativa (18°C)","v":"1,984 (acqua=1)","o":4},
{"n":"Bitartrato di potassio","f":"Solubilità","v":"1 g in 16 ml acqua bollente","o":5},
{"n":"Bitume adesivo","f":"Gradazioni disponibili","v":"40/60, 50/70, 70/100, 100/150, 160/220, 250/330 (EN 12591)","o":0},
{"n":"Bitume adesivo","f":"Penetrazione @25°C","v":"Es. 40/60: 40–60 dmm (EN 1426), variabile per grado","o":1},
{"n":"Bitume adesivo","f":"Punto di rammollimento","v":"Es. 40/60: 48–56°C (EN 1427), variabile per grado","o":2},
{"n":"Bitume adesivo","f":"Solubilità","v":"≥99,0% (EN 12592, tutti i gradi)","o":3},
{"n":"Bitume adesivo","f":"Punto di infiammabilità","v":"≥230°C (maggior parte gradi); ≥220°C (160/220); ≥180°C (250/330)","o":4},
{"n":"Bitume adesivo","f":"Viscosità cinematica @135°C","v":"Es. 40/60: ≥325 mm²/s (EN 12595), variabile per grado","o":5},
{"n":"Bitume adesivo","f":"Durabilità (resistenza indurimento @163°C)","v":"Variazione di massa ≤0,5–1,0% secondo grado (EN 12607-1)","o":6},
{"n":"Bitume adesivo","f":"Conformità normativa","v":"EN 12591","o":7},
{"n":"Bitume adesivo","f":"Temperature di stoccaggio/pompaggio","v":"Variabili per grado (es. 40/60: pompaggio min 115°C, stoccaggio 160°C)","o":8},
{"n":"Bitume adesivo","f":"Certificazione qualità","v":"BS EN ISO 9001:2015","o":9},
{"n":"Blu oltremare","f":"Composizione","v":"Sodio alluminio solfosilicato (Pigment Blue 29, C.I. 77007), 100%","o":0},
{"n":"Blu oltremare","f":"Aspetto","v":"Solido, polvere blu, inodore","o":1},
{"n":"Blu oltremare","f":"pH","v":"7–9 (ASTM 1208-78)","o":2},
{"n":"Blu oltremare","f":"Temperatura di decomposizione","v":"400°C","o":3},
{"n":"Blu oltremare","f":"Punto di fusione","v":">1000°C","o":4},
{"n":"Blu oltremare","f":"Solubilità in acqua","v":"Insolubile","o":5},
{"n":"Blu oltremare","f":"Densità (gravità specifica)","v":"2,35 g/cm³ (acqua=1)","o":6},
{"n":"Carragenina","f":"Viscosità (1,5%, 75°C)","v":"≥5 mPa·s","o":0},
{"n":"Carragenina","f":"Forza del gel","v":"Kappa Refined ≥1.300 g/cm² (1,5%+0,2% KCl, 20°C); Kappa Semi-Refined ≥450 g/cm²","o":1},
{"n":"Carragenina","f":"Perdita all'essiccamento (105°C)","v":"≤12%","o":2},
{"n":"Carragenina","f":"Ceneri totali (550°C)","v":"15-40%","o":3},
{"n":"Carragenina","f":"pH (soluzione 1%)","v":"8-11","o":4},
{"n":"Carragenina","f":"Ceneri insolubili in acido","v":"≤1%","o":5},
{"n":"Carragenina","f":"Materia insolubile in acido","v":"Refined ≤2%; Semi-Refined ≤15%","o":6},
{"n":"Carragenina","f":"Metalli pesanti (Pb)","v":"≤5 ppm","o":7},
{"n":"Carragenina","f":"Arsenico","v":"≤3 ppm","o":8},
{"n":"Carragenina","f":"Granulometria","v":"Polvere fine, colore bianco sporco","o":9},
{"n":"Carragenina","f":"Shelf life","v":"24 mesi in confezione originale, luogo fresco e asciutto","o":10},
{"n":"Carragenina","f":"Packaging disponibile","v":"Sacchi da 25 kg (tessuto o kraft con sacco interno in polietilene)","o":11},
{"n":"Carragenina","f":"Conformità normativa","v":"Non OGM","o":12},
{"n":"Caseina (adesivo)","f":"Composizione","v":"Caseina >95%","o":0},
{"n":"Caseina (adesivo)","f":"Aspetto","v":"Polvere solida, da bianca a giallastra","o":1},
{"n":"Caseina (adesivo)","f":"Punto di fusione","v":"280°C","o":2},
{"n":"Caseina (adesivo)","f":"pH (soluzione 100 g/L, 20°C)","v":"4,5","o":3},
{"n":"Caseina (adesivo)","f":"Solubilità in acqua","v":"Insolubile","o":4},
{"n":"Caseinato di sodio","f":"Composizione tipica","v":"Proteine 90%; Umidità 7,0%; Grasso di latte 1,2%; Ceneri 4,5%","o":0},
{"n":"Caseinato di sodio","f":"pH","v":"7,0","o":1},
{"n":"Caseinato di sodio","f":"Densità apparente (IDF 134)","v":"0,65-0,83 g/mL","o":2},
{"n":"Caseinato di sodio","f":"Colore","v":"Crema chiaro","o":3},
{"n":"Caseinato di sodio","f":"Valori microbiologici tipici","v":"SPC ≤20.000 cfu/g; Coliformi negativo; Lieviti ≤50/g; Muffe ≤50/g; Salmonella negativo/375g","o":4},
{"n":"Caseinato di sodio","f":"Shelf life","v":"24 mesi dalla data di produzione","o":5},
{"n":"Caseinato di sodio","f":"Packaging disponibile","v":"25 kg (sacco multistrato con barriera all'umidità) o 1000 kg (big bag)","o":6},
{"n":"Caseinato di sodio","f":"Conformità normativa","v":"Standard GFSI, Halal, Kosher, legislazione UE applicabile","o":7},
{"n":"Cellulosa kraft (pasta)","f":"Materia prima","v":"Hardwood (Eucalyptus grandis, dunnii, globulus, maidenii), pasta kraft ECF sbiancata","o":0},
{"n":"Cellulosa kraft (pasta)","f":"Brillantezza (ISO Brightness)","v":"≥89% (tipico 90%), ISO 2470-1/ISO 3688","o":1},
{"n":"Cellulosa kraft (pasta)","f":"pH","v":"5,0-7,0 (ISO 1762)","o":2},
{"n":"Cellulosa kraft (pasta)","f":"Packaging disponibile","v":"Balle standard 250 kg (92x67 cm, unità 2000 kg/8 balle) o big bale 1000 kg (unità 2000 kg/2 balle)","o":3},
{"n":"Cellulosa kraft (pasta)","f":"Grammatura foglio balla","v":"1000-1200 g/m²","o":4},
{"n":"Cellulosa microcristallina (MCC)","f":"Conformità farmacopea","v":"NF, Ph.Eur., JP (Avicel PH-101)","o":0},
{"n":"Cellulosa microcristallina (MCC)","f":"Perdita all'essiccamento","v":"3,0-5,0%","o":1},
{"n":"Cellulosa microcristallina (MCC)","f":"Densità apparente non compattata","v":"0,26-0,31 g/cc","o":2},
{"n":"Cellulosa microcristallina (MCC)","f":"Grado di polimerizzazione","v":"NMT 350 unità","o":3},
{"n":"Cellulosa microcristallina (MCC)","f":"pH","v":"5,5-7,0","o":4},
{"n":"Cellulosa microcristallina (MCC)","f":"Conducibilità","v":"NMT 75 µS/cm","o":5},
{"n":"Cellulosa microcristallina (MCC)","f":"Residuo all'incenerimento","v":"NMT 0,05%","o":6},
{"n":"Cellulosa microcristallina (MCC)","f":"Sostanze solubili in acqua","v":"NMT 0,25% (NMT 12,5 mg/5g)","o":7},
{"n":"Cellulosa microcristallina (MCC)","f":"Metalli pesanti","v":"NMT 0,001%","o":8},
{"n":"Cellulosa microcristallina (MCC)","f":"Granulometria (PSD)","v":"D10 14-30 µm; D50 40-75 µm; D90 77-156 µm","o":9},
{"n":"Cellulosa microcristallina (MCC)","f":"Granulometria (Air Jet)","v":"+60 mesh (250 µm) NMT 1,0%; +200 mesh (75 µm) NMT 30%","o":10},
{"n":"Cellulosa microcristallina (MCC)","f":"Conformità normativa","v":"USP <467> Solventi residui; ICH Q3C","o":11},
{"n":"Cellulosa microcristallina (MCC)","f":"Shelf life","v":"4 anni dalla data di produzione (contenitori sigillati, condizioni ambientali)","o":12},
{"n":"Cetearyl alcohol","f":"Nome INCI","v":"Cetearyl Alcohol (miscela alcol cetilico C16 + stearico C18)","o":0},
{"n":"Cetearyl alcohol","f":"Punto di fusione","v":"49-59°C (cetilico 49-56°C; stearico 56-59°C)","o":1},
{"n":"Cetearyl alcohol","f":"Densità","v":"0,8-0,9 g/cm³","o":2},
{"n":"Cetearyl alcohol","f":"HLB","v":"15,5","o":3},
{"n":"Cetearyl alcohol","f":"Solubilità","v":"Scarsamente solubile in acqua; solubile in oli, etanolo, isopropanolo","o":4},
{"n":"Cetearyl alcohol","f":"Range d'uso tipico","v":"0,5-10%","o":5},
{"n":"Cetrimonio cloruro (CTAC)","f":"Nome INCI","v":"Cetrimonium Chloride (Hexadecyltrimethylammonium chloride, in acqua)","o":0},
{"n":"Cetrimonio cloruro (CTAC)","f":"Contenuto principio attivo","v":"25%","o":1},
{"n":"Cetrimonio cloruro (CTAC)","f":"pH (soluzione 2%)","v":"3-5","o":2},
{"n":"Cetrimonio cloruro (CTAC)","f":"Aspetto","v":"Liquido da incolore a leggermente giallastro","o":3},
{"n":"Cetrimonio cloruro (CTAC)","f":"Conformità normativa","v":"Reg. Cosmetici UE: max 0,1% come conservante (alchil C12-C22 trimetilammonio cloruro)","o":4},
{"n":"Cetrimonio cloruro (CTAC)","f":"Range d'uso","v":"Risciacquo fino al 10%; leave-on 0,25-1%","o":5},
{"n":"Cetyl alcohol","f":"Aspetto","v":"Pastiglie bianche","o":0},
{"n":"Cetyl alcohol","f":"Indice di acidità","v":"Max 0,1","o":1},
{"n":"Cetyl alcohol","f":"Indice di saponificazione","v":"Max 0,3","o":2},
{"n":"Cetyl alcohol","f":"Indice di iodio","v":"Max 0,3","o":3},
{"n":"Cetyl alcohol","f":"Indice di idrossile","v":"225-235","o":4},
{"n":"Cetyl alcohol","f":"Umidità","v":"Max 0,1%","o":5},
{"n":"Cetyl alcohol","f":"Distribuzione catena carboniosa","v":"C12 <0,5%; C14 <1,0%; C16 >98%; C18 <1%","o":6},
{"n":"Cetyl alcohol","f":"Peso molecolare medio","v":"238-249","o":7},
{"n":"Cetyl alcohol","f":"Intervallo di solidificazione","v":"47-50°C","o":8},
{"n":"Cetyl alcohol","f":"Densità","v":"0,805-0,815","o":9},
{"n":"Cetyl alcohol","f":"Punto di infiammabilità","v":"~175°C","o":10},
{"n":"Cetyl alcohol","f":"Intervallo di ebollizione","v":"305-330°C","o":11},
{"n":"Cetyl alcohol","f":"Packaging disponibile","v":"Sacchi da 25 kg con liner in polietilene","o":12},
{"n":"Chinacridone violetto","f":"Forma cristallina","v":"Beta, tonalità blu-violetto","o":0},
{"n":"Chinacridone violetto","f":"Numero di costituzione","v":"73900","o":1},
{"n":"Chinacridone violetto","f":"Peso specifico","v":"~1,50 g/cm³","o":2},
{"n":"Chinacridone violetto","f":"Resistenza al calore","v":"570°F/299°C (HDPE 5 min); 390°F/199°C (vernice alchidica cotta 30 min); 330°F/166°C (inchiostri metal deco 30 min)","o":3},
{"n":"Chinacridone violetto","f":"Solidità alla luce (Lightfastness)","v":"7-8 (masstone, vernice alchidica); 6+ (offset); 7-8 (plastica PVC)","o":4},
{"n":"Chinacridone violetto","f":"Resistenza chimica","v":"Xylene 5, Etanolo 4-5, MEK 4-5, Solvent nafta 5, Acqua 5 (scala 1-5)","o":5},
{"n":"Chinacridone violetto","f":"Conformità normativa","v":"FDA approvato (Sez. 178.3297)","o":6},
{"n":"Cianoacrilato (presa rapida)","f":"Tecnologia","v":"Cianoacrilato (etil cianoacrilato)","o":0},
{"n":"Cianoacrilato (presa rapida)","f":"Peso specifico (25°C)","v":"1,1","o":1},
{"n":"Cianoacrilato (presa rapida)","f":"Viscosità","v":"150-450 mPa·s (Cono/Piatto, Casson); Brookfield 100.000-300.000 mPa·s (2,5 rpm)","o":2},
{"n":"Cianoacrilato (presa rapida)","f":"Resistenza a trazione (72h, 22°C, Buna-N)","v":"15,1 N/mm²","o":3},
{"n":"Cianoacrilato (presa rapida)","f":"Resistenza a taglio (lap shear, ISO 4587)","v":"Acciaio 20,9 N/mm²; Alluminio 17,1 N/mm²; ABS 8,3 N/mm²; PVC 7,1 N/mm²; Policarbonato 7,7 N/mm²","o":4},
{"n":"Cianoacrilato (presa rapida)","f":"Tempo di presa (fixture time)","v":"Acciaio 30-60s; Alluminio 2-10s; ABS <5s; Legno pino 15-30s","o":5},
{"n":"Cianoacrilato (presa rapida)","f":"Shelf life / conservazione","v":"Conservare a 2-8°C","o":6},
{"n":"Cianoacrilato (presa rapida)","f":"Conformità normativa","v":"NSF International categoria P1","o":7},
{"n":"Ciclopentasilossano","f":"Composizione (SDS Sez. 3)","v":"Decametilciclopentasilossano ≥99,0-100,0%; Dodecametilciclossasilossano CAS 540-97-6 ≥1,0-<5,0%","o":0},
{"n":"Ciclopentasilossano","f":"Stato fisico","v":"Liquido incolore, inodore","o":1},
{"n":"Ciclopentasilossano","f":"Punto di ebollizione (760 mmHg)","v":"211°C","o":2},
{"n":"Ciclopentasilossano","f":"Punto di infiammabilità (vaso chiuso)","v":"77°C","o":3},
{"n":"Ciclopentasilossano","f":"Densità relativa (acqua=1)","v":"0,95","o":4},
{"n":"Ciclopentasilossano","f":"Viscosità cinematica (25°C)","v":"3,8 cSt","o":5},
{"n":"Cloramina T","f":"Nome chimico","v":"Sodio N-cloro-para-toluensolfonamide","o":0},
{"n":"Cloramina T","f":"Formula molecolare","v":"C7H7ClNNaO2S·3H2O","o":1},
{"n":"Cloramina T","f":"Peso molecolare","v":"281,5","o":2},
{"n":"Cloramina T","f":"Assay (titolo)","v":"98,0-103,0% m/m","o":3},
{"n":"Cloramina T","f":"Torbidità (soluzione 0,5%)","v":"≤5 FTU","o":4},
{"n":"Cloramina T","f":"Colore (soluzione 5%)","v":"≤25 Pt/Co","o":5},
{"n":"Cloramina T","f":"pH (soluzione 5%)","v":"8,0-10,3","o":6},
{"n":"Cloramina T","f":"Aspetto","v":"Polvere cristallina bianca","o":7},
{"n":"Cloramina T","f":"Solubilità in acqua (25°C)","v":"150 g/l","o":8},
{"n":"Cloramina T","f":"Densità apparente","v":"540-680 g/ml","o":9},
{"n":"Cloramina T","f":"Punto di infiammabilità","v":"192°C (Pensky-Martens)","o":10},
{"n":"Cloramina T","f":"Packaging disponibile","v":"Sacchi 25 kg, fusti PE 25 kg, fusti fibra 125 kg, big bag 1000 kg","o":11},
{"n":"Clorexidina digluconato","f":"Formula molecolare","v":"C22H30Cl2N10 · 2 C6H12O7","o":0},
{"n":"Clorexidina digluconato","f":"Peso molecolare","v":"897,8","o":1},
{"n":"Clorexidina digluconato","f":"Concentrazione","v":"Soluzione acquosa al 20% (w/v)","o":2},
{"n":"Clorexidina digluconato","f":"Aspetto","v":"Liquido limpido, da incolore a leggermente giallo","o":3},
{"n":"Clorexidina digluconato","f":"Solubilità in acqua","v":"Almeno 50% (w/v)","o":4},
{"n":"Clorexidina digluconato","f":"Stabilità pH (soluzione)","v":"Ottimale 5-8","o":5},
{"n":"Clorexidina digluconato","f":"Shelf life","v":"3 anni a 2-8°C come fornito","o":6},
{"n":"Cloro","f":"Peso molecolare","v":"70,906","o":0},
{"n":"Cloro","f":"Aspetto","v":"Gas liquefatto verde-giallastro, odore pungente","o":1},
{"n":"Cloro","f":"Purezza (grado)","v":"Elettronica 99,99%; UHP 99,9%; HP 99,5%","o":2},
{"n":"Cloro","f":"Volume specifico","v":"5,46 cf/lb a 70°F, 1 ATM","o":3},
{"n":"Cloro","f":"Classe DOT","v":"2.3, 8 (tossico per inalazione e corrosivo)","o":4},
{"n":"Cloruro di benzalconio","f":"Composizione","v":"N-Alchildimetilbenzilammonio cloruro 50% + acqua 50%","o":0},
{"n":"Cloruro di benzalconio","f":"Aspetto","v":"Liquido giallo chiaro","o":1},
{"n":"Cloruro di benzalconio","f":"pH (soluzione acquosa 10%)","v":"6,0-9,0","o":2},
{"n":"Cloruro di benzalconio","f":"Viscosità (20°C)","v":"130 mPa·s","o":3},
{"n":"Cloruro di benzalconio","f":"Punto di ebollizione (760 mmHg)","v":">100°C","o":4},
{"n":"Cloruro di benzalconio","f":"Densità","v":"0,980","o":5},
{"n":"Cloruro di benzalconio","f":"Temperatura di decomposizione","v":">140°C","o":6},
{"n":"Cloruro di benzalconio","f":"Temperatura di autoaccensione","v":"370°C","o":7},
{"n":"Cloruro di benzalconio","f":"Pressione di vapore (50°C)","v":"120 hPa","o":8},
{"n":"Cloruro di calcio","f":"Aspetto","v":"Pellet solidi bianchi, inodore, igroscopico","o":0},
{"n":"Cloruro di calcio","f":"Assay","v":"CaCl2 94,5%; KCl 2,5%; NaCl 1,6%; CaBr2 0,9%; Acqua 0,5%","o":1},
{"n":"Cloruro di calcio","f":"Conformità FCC (anidro)","v":"Fluoruro <0,004%; Piombo <5 mg/kg; Magnesio e sali alcalini <5,0%; Materia insolubile in acido <0,02%; Arsenico <3 mg/kg","o":2},
{"n":"Cloruro di calcio","f":"Conformità normativa","v":"FDA 21 CFR 184.1193 e 582.1193 (GRAS), Kosher, Halal","o":3},
{"n":"Cloruro di calcio","f":"Packaging disponibile","v":"Sacchi in plastica da 50 lb","o":4},
{"n":"Cloruro di didecildimetilammonio (DDAC)","f":"Formula molecolare","v":"C22H48ClN","o":0},
{"n":"Cloruro di didecildimetilammonio (DDAC)","f":"Aspetto","v":"Cationico, da giallo chiaro a bianco","o":1},
{"n":"Cloruro di didecildimetilammonio (DDAC)","f":"Materia attiva","v":"80% min","o":2},
{"n":"Cloruro di didecildimetilammonio (DDAC)","f":"Ammina libera","v":"2% max","o":3},
{"n":"Cloruro di didecildimetilammonio (DDAC)","f":"pH (soluzione acquosa 10%)","v":"4-8","o":4},
{"n":"Cloruro di didecildimetilammonio (DDAC)","f":"Gardner","v":"100% max","o":5},
{"n":"Cloruro di didecildimetilammonio (DDAC)","f":"Contenuto C2H5OH","v":"20%","o":6},
{"n":"Cloruro di didecildimetilammonio (DDAC)","f":"Packaging disponibile","v":"Fusti in plastica da 180 kg (14,4 MT/FCL 20')","o":7},
{"n":"Cloruro di didecildimetilammonio (DDAC)","f":"Shelf life","v":"2 anni in luogo asciutto e ombreggiato","o":8},
{"n":"Cloruro di potassio (MOP)","f":"Composizione","v":"K2O 60,0% min (61,2% tipico); KCl 96,5% tipico; K 50,6% tipico","o":0},
{"n":"Cloruro di potassio (MOP)","f":"Impurezze tipiche","v":"Umidità 0,05%; Mg 0,05%; Ca 0,04%; NaCl 2,5%; Cloruro 47,4%; Solfato 0,08%; Sodio 1,0%; Insolubili in acqua 0,5%","o":1},
{"n":"Cloruro di potassio (MOP)","f":"Aspetto/Colore","v":"Rosso/Rosa","o":2},
{"n":"Cloruro di potassio (MOP)","f":"Densità apparente","v":"76-84 lb/ft³ (1217-1345 kg/m³), tipico 80 lb/ft³","o":3},
{"n":"Cloruro di potassio (MOP)","f":"Granulometria (SGN)","v":"95","o":4},
{"n":"Cloruro di potassio (MOP)","f":"Indice di uniformità","v":"20","o":5},
{"n":"Cloruro di potassio (MOP)","f":"Angolo di riposo","v":"31-35° (tipico 33°)","o":6},
{"n":"Cloruro di sodio industriale","f":"Composizione","v":"NaCl (secco) 99,8%","o":0},
{"n":"Cloruro di sodio industriale","f":"Impurezze tipiche","v":"Ca e Mg (come Ca) 0,04%; Solfato (come SO4) 0,06%; Umidità superficiale 0,01%; Insolubili in acqua 20 ppm","o":1},
{"n":"Cloruro di sodio industriale","f":"Densità apparente","v":"69-84 lb/ft³ (1100-1345 g/L)","o":2},
{"n":"Cloruro di sodio industriale","f":"Granulometria","v":"Distribuzione su setacci USS 30-70 mesh (590-210 micron)","o":3},
{"n":"Cloruro di sodio industriale","f":"Metodo di analisi","v":"ASTM E 534","o":4},
{"n":"Cloruro di sodio industriale","f":"Conformità normativa","v":"NSF 60 (prodotti bulk certificati)","o":5},
{"n":"Cloruro di vinile (VCM)","f":"Purezza","v":">99,9%","o":0},
{"n":"Cloruro di vinile (VCM)","f":"Punto di ebollizione","v":"-13,8°C","o":1},
{"n":"Cloruro di vinile (VCM)","f":"Punto di fusione","v":"-154°C","o":2},
{"n":"Cloruro di vinile (VCM)","f":"Pressione di vapore (20°C)","v":"2500 mmHg","o":3},
{"n":"Cloruro di vinile (VCM)","f":"Densità di vapore (aria=1)","v":"2,2","o":4},
{"n":"Cloruro di vinile (VCM)","f":"Punto di infiammabilità","v":"-78°C","o":5},
{"n":"Cloruro di vinile (VCM)","f":"Limiti di infiammabilità","v":"LEL 3,6%; UEL 33%","o":6},
{"n":"Cloruro di vinile (VCM)","f":"Temperatura di autoaccensione","v":"472°C","o":7},
{"n":"Cloruro ferrico","f":"Formula molecolare","v":"FeCl3","o":0},
{"n":"Cloruro ferrico","f":"Peso molecolare","v":"162,2 g/mol","o":1},
{"n":"Cloruro ferrico","f":"Purezza (Iron trichloride)","v":"80,0–100,0%","o":2},
{"n":"Cloruro ferrico","f":"Aspetto","v":"Solido cristallino, colore da verde a nero","o":3},
{"n":"Cloruro ferrico","f":"Odore","v":"Lieve, pungente","o":4},
{"n":"Cloruro ferrico","f":"pH","v":"1 (soluzione 200 g/l, 20°C)","o":5},
{"n":"Cloruro ferrico","f":"Punto di ebollizione","v":"315°C (decompone, 1013,25 hPa)","o":6},
{"n":"Cloruro ferrico","f":"Temperatura di sublimazione","v":"304°C (1 bar)","o":7},
{"n":"Cloruro ferrico","f":"Densità","v":"2,89 g/cm3 (25°C)","o":8},
{"n":"Cloruro ferrico","f":"Densità apparente","v":"circa 1000 kg/m3","o":9},
{"n":"Cloruro ferrico","f":"Solubilità in acqua","v":"744 g/l (0°C); 480 g/kg (20°C)","o":10},
{"n":"Cloruro ferrico","f":"Granulometria","v":"D10 3,3 µm; D50 11,7 µm; D90 35,3 µm","o":11},
{"n":"Cocamidopropil betaina (CAPB)","f":"Aspetto","v":"Liquido limpido, giallo pallido","o":0},
{"n":"Cocamidopropil betaina (CAPB)","f":"Sostanza attiva (Active Matter)","v":"29–31%","o":1},
{"n":"Cocamidopropil betaina (CAPB)","f":"pH (soluzione al 5%)","v":"4,0–6,0","o":2},
{"n":"Cocamidopropil betaina (CAPB)","f":"Cloruri (come NaCl)","v":"4,0–6,0%","o":3},
{"n":"Cocamidopropil betaina (CAPB)","f":"Colore (Gardner)","v":"1,0 max","o":4},
{"n":"Cocamidopropil betaina (CAPB)","f":"Contenuto d'acqua","v":"63–67%","o":5},
{"n":"Cocamidopropil betaina (CAPB)","f":"Solidi totali","v":"34,0–37,0%","o":6},
{"n":"Colofonia (rosin)","f":"EC number","v":"232-475-7","o":0},
{"n":"Colofonia (rosin)","f":"Aspetto","v":"Solido cristallino, colore da giallo chiaro a scuro","o":1},
{"n":"Colofonia (rosin)","f":"Odore","v":"Resinoso, lieve","o":2},
{"n":"Colofonia (rosin)","f":"Colore (Gardner)","v":"4–10 (ASTM D6166)","o":3},
{"n":"Colofonia (rosin)","f":"Indice di acidità","v":"76–85 mg KOH/g (NP 236)","o":4},
{"n":"Colofonia (rosin)","f":"Ceneri (525°C)","v":"< 0,2% (NP 3454)","o":5},
{"n":"Colofonia (rosin)","f":"Indice di saponificazione","v":"158–188 mg KOH/g (NP 3452)","o":6},
{"n":"Colofonia (rosin)","f":"Insolubile in toluene","v":"< 0,1% (NP 236)","o":7},
{"n":"Colofonia (rosin)","f":"Punto di rammollimento","v":"162–175°C (NP 238)","o":8},
{"n":"Colofonia (rosin)","f":"Olio volatile","v":"≤ 2,5% (NP 101)","o":9},
{"n":"Colofonia (rosin)","f":"Composizione","v":"Acidi resinici diterpenici (abietico, neoabietico, palustrico, pimarico ecc.) 85–95%; frazione neutra 5–15%","o":10},
{"n":"Colofonia (rosin)","f":"Solubilità","v":"Solubile in idrocarburi aromatici e clorurati, esteri, chetoni; parzialmente solubile in idrocarburi alifatici","o":11},
{"n":"Colofonia (rosin)","f":"Forme disponibili","v":"Fiocchi, sbriciolato, blocco","o":12},
{"n":"Colofonia (rosin)","f":"Packaging disponibile","v":"Sacchi carta 25 kg, scatole cartone 25 kg, fusti 250 kg, sacchi PP 250 kg","o":13},
{"n":"Colofonia (sizing)","f":"EC number","v":"232-475-7","o":0},
{"n":"Colofonia (sizing)","f":"Aspetto","v":"Solido cristallino, colore da giallo chiaro a scuro","o":1},
{"n":"Colofonia (sizing)","f":"Odore","v":"Resinoso, lieve","o":2},
{"n":"Colofonia (sizing)","f":"Colore (Gardner)","v":"4–10 (ASTM D6166)","o":3},
{"n":"Colofonia (sizing)","f":"Indice di acidità","v":"76–85 mg KOH/g (NP 236)","o":4},
{"n":"Colofonia (sizing)","f":"Ceneri (525°C)","v":"< 0,2% (NP 3454)","o":5},
{"n":"Colofonia (sizing)","f":"Indice di saponificazione","v":"158–188 mg KOH/g (NP 3452)","o":6},
{"n":"Colofonia (sizing)","f":"Insolubile in toluene","v":"< 0,1% (NP 236)","o":7},
{"n":"Colofonia (sizing)","f":"Punto di rammollimento","v":"162–175°C (NP 238)","o":8},
{"n":"Colofonia (sizing)","f":"Olio volatile","v":"≤ 2,5% (NP 101)","o":9},
{"n":"Colofonia (sizing)","f":"Composizione","v":"Acidi resinici diterpenici (abietico, neoabietico, palustrico, pimarico ecc.) 85–95%; frazione neutra 5–15%","o":10},
{"n":"Colofonia (sizing)","f":"Packaging disponibile","v":"Sacchi carta 25 kg, scatole cartone 25 kg, fusti 250 kg, sacchi PP 250 kg","o":11},
{"n":"Cromo metallico","f":"Formula lineare","v":"Cr","o":0},
{"n":"Cromo metallico","f":"Peso atomico/molecolare","v":"52 (51,9961) g/mol","o":1},
{"n":"Cromo metallico","f":"Aspetto","v":"Argenteo","o":2},
{"n":"Cromo metallico","f":"Punto di fusione","v":"1857°C","o":3},
{"n":"Cromo metallico","f":"Punto di ebollizione","v":"2672°C","o":4},
{"n":"Cromo metallico","f":"Densità","v":"7,18 g/cm3","o":5},
{"n":"Cromo metallico","f":"Purezza disponibile","v":"Da 99% (2N) a 99,999% (5N)","o":6},
{"n":"Cromo metallico","f":"EC No.","v":"231-157-5","o":7},
{"n":"Cromo metallico","f":"MDL Number","v":"MFCD00010944","o":8},
{"n":"Decyl glucoside","f":"INCI","v":"Decyl Glucoside","o":0},
{"n":"Decyl glucoside","f":"Aspetto","v":"Liquido viscoso da incolore a giallo pallido","o":1},
{"n":"Decyl glucoside","f":"pH (soluzione 10%)","v":"11,0–12,5","o":2},
{"n":"Decyl glucoside","f":"Contenuto solido","v":"min. 50%","o":3},
{"n":"Decyl glucoside","f":"Alcol residuo","v":"max 1,0%","o":4},
{"n":"Decyl glucoside","f":"Shelf life","v":"24 mesi","o":5},
{"n":"Decyl glucoside","f":"Packaging disponibile","v":"Fusti da 125 kg","o":6},
{"n":"Decyl glucoside","f":"Dosaggio raccomandato","v":"5–20%","o":7},
{"n":"Dicloroisocianurato di sodio (NaDCC)","f":"Formula molecolare","v":"C3HCl2N3NaO3","o":0},
{"n":"Dicloroisocianurato di sodio (NaDCC)","f":"Peso molecolare","v":"220,95 g/mol","o":1},
{"n":"Dicloroisocianurato di sodio (NaDCC)","f":"Condizioni di stoccaggio","v":"Ambiente, asciutto e fresco; in soluzione: -80°C 1 anno, -20°C 6 mesi","o":2},
{"n":"Diclorometano (DCM)","f":"Purezza (Dichloromethane)","v":"80–100%","o":0},
{"n":"Diclorometano (DCM)","f":"Peso molecolare","v":"84,93 g/mol","o":1},
{"n":"Diclorometano (DCM)","f":"Aspetto","v":"Liquido incolore","o":2},
{"n":"Diclorometano (DCM)","f":"Odore","v":"Etereo","o":3},
{"n":"Diclorometano (DCM)","f":"Punto di fusione","v":"-97°C","o":4},
{"n":"Diclorometano (DCM)","f":"Punto di ebollizione","v":"39,8–40°C","o":5},
{"n":"Diclorometano (DCM)","f":"Densità","v":"1,325 g/mL (25°C)","o":6},
{"n":"Diclorometano (DCM)","f":"Densità relativa vapore","v":"2,93","o":7},
{"n":"Diclorometano (DCM)","f":"Tensione di vapore","v":"584 hPa (25°C)","o":8},
{"n":"Diclorometano (DCM)","f":"Solubilità in acqua","v":"13,2 g/l (25°C, pH 7)","o":9},
{"n":"Diclorometano (DCM)","f":"Viscosità dinamica","v":"0,42 mPa·s (25°C)","o":10},
{"n":"Diclorometano (DCM)","f":"Indice di rifrazione","v":"1,42 (20°C)","o":11},
{"n":"Diclorometano (DCM)","f":"Temperatura di autoaccensione","v":"556,1°C","o":12},
{"n":"Diclorometano (DCM)","f":"Limiti di esplosività","v":"13–22% vol","o":13},
{"n":"Diclorometano (DCM)","f":"Punto di infiammabilità","v":"Non infiammabile (does not flash)","o":14},
{"n":"Dimeticone","f":"INCI","v":"Dimethicone","o":0},
{"n":"Dimeticone","f":"Formula chimica","v":"(CH3)3SiO[SiO(CH3)2]nSi(CH3)3","o":1},
{"n":"Dimeticone","f":"Gamma viscosità disponibile","v":"50, 100, 200, 350, 500, 1000 cSt","o":2},
{"n":"Dimeticone","f":"Peso specifico (25°C)","v":"0,960–0,970","o":3},
{"n":"Dimeticone","f":"Indice di rifrazione (25°C)","v":"1,4022–1,4035","o":4},
{"n":"Dimeticone","f":"Colore (APHA)","v":"5","o":5},
{"n":"Dimeticone","f":"Punto di infiammabilità (vaso aperto)","v":"318°C (50 cSt) fino a >326°C (gradi più viscosi)","o":6},
{"n":"Dimeticone","f":"Punto di fusione","v":"da -41°C (50 cSt) a -25°C (1000 cSt)","o":7},
{"n":"Dimeticone","f":"Pour point","v":"da -70°C a -50°C","o":8},
{"n":"Dimeticone","f":"Tensione superficiale (25°C)","v":"20,8–21,2 dynes/cm","o":9},
{"n":"Dimeticone","f":"Contenuto volatile (150°C)","v":"0,02–0,3%","o":10},
{"n":"Dimeticone","f":"Rigidità dielettrica (25°C)","v":"400 volt/mil","o":11},
{"n":"Dimeticone","f":"Resistività di volume (25°C)","v":"1,0×10^15 ohm·cm","o":12},
{"n":"Dimeticone","f":"Solubilità","v":"Alta in solventi clorurati, aromatici, alifatici; scarsa in acqua e alcoli anidri","o":13},
{"n":"Dimetilformammide (DMF)","f":"Formula molecolare","v":"C3H7NO","o":0},
{"n":"Dimetilformammide (DMF)","f":"Peso molecolare","v":"73,09 g/mol","o":1},
{"n":"Dimetilformammide (DMF)","f":"Punto di ebollizione","v":"153°C","o":2},
{"n":"Dimetilformammide (DMF)","f":"Punto di congelamento","v":"-60,4°C","o":3},
{"n":"Dimetilformammide (DMF)","f":"Densità","v":"949 kg/m3 (20°C); 931 kg/m3 (40°C)","o":4},
{"n":"Dimetilformammide (DMF)","f":"Punto di infiammabilità","v":"58°C (vaso chiuso); 67°C (vaso aperto)","o":5},
{"n":"Dimetilformammide (DMF)","f":"Temperatura di autoaccensione","v":"445°C","o":6},
{"n":"Dimetilformammide (DMF)","f":"Limiti di infiammabilità (100°C)","v":"2,2–16,0 vol%","o":7},
{"n":"Dimetilformammide (DMF)","f":"Viscosità (25°C)","v":"0,802 mPa·s","o":8},
{"n":"Dimetilformammide (DMF)","f":"Indice di rifrazione (25°C)","v":"1,4278","o":9},
{"n":"Dimetilformammide (DMF)","f":"Purezza (Assay)","v":"≥ 99,8%","o":10},
{"n":"Dimetilformammide (DMF)","f":"Colore","v":"≤ 10 APHA","o":11},
{"n":"Dimetilformammide (DMF)","f":"Contenuto d'acqua","v":"≤ 300 ppm","o":12},
{"n":"Dimetilformammide (DMF)","f":"Metanolo","v":"≤ 100 ppm","o":13},
{"n":"Dimetilformammide (DMF)","f":"Acido formico","v":"≤ 3 ppm","o":14},
{"n":"Dimetilformammide (DMF)","f":"Dimetilammina (DMA)","v":"≤ 10 ppm","o":15},
{"n":"Dimetilformammide (DMF)","f":"Conducibilità (20°C)","v":"≤ 2,5 µS/cm","o":16},
{"n":"Dimetilformammide (DMF)","f":"pH (soluzione acquosa 20%)","v":"6,5–8,5","o":17},
{"n":"Dimetilformammide (DMF)","f":"Packaging disponibile","v":"Fusti PE 200 kg, fusti ferro 195 kg, IBC 945 kg, autocisterne/carri in acciaio inox","o":18},
{"n":"Distearildimonio cloruro","f":"Nome chimico","v":"Dialkyl dimethyl ammonium chloride (R=C18)","o":0},
{"n":"Distearildimonio cloruro","f":"Aspetto (20°C)","v":"Pellet giallo pallido","o":1},
{"n":"Distearildimonio cloruro","f":"Odore","v":"Debole","o":2},
{"n":"Distearildimonio cloruro","f":"Sostanza attiva","v":"90,0–98,0%","o":3},
{"n":"Distearildimonio cloruro","f":"Peso molecolare medio","v":"570 g/mol","o":4},
{"n":"Distearildimonio cloruro","f":"pH (1% sostanza attiva in acqua)","v":"4,0–6,0","o":5},
{"n":"Distearildimonio cloruro","f":"Contenuto d'acqua","v":"max 3,0%","o":6},
{"n":"Distearildimonio cloruro","f":"Isopropanolo","v":"max 7,0%","o":7},
{"n":"Distearildimonio cloruro","f":"Solubilità","v":"Dispersibile in acqua calda","o":8},
{"n":"Dolomite","f":"Composizione chimica","v":"CaMg(CO3)2 99,0%; insolubile in HCl 1,0%","o":0},
{"n":"Dolomite","f":"Residuo su setaccio 45 µm","v":"0,01%","o":1},
{"n":"Dolomite","f":"Top cut (d98%)","v":"20 µm","o":2},
{"n":"Dolomite","f":"Dimensione media particelle (d50%)","v":"7 µm","o":3},
{"n":"Dolomite","f":"Particelle < 2 µm","v":"20%","o":4},
{"n":"Dolomite","f":"Superficie specifica BET","v":"2,3 m²/g","o":5},
{"n":"Dolomite","f":"Brillantezza (Ry, C/2°)","v":"94%","o":6},
{"n":"Dolomite","f":"Umidità (ex works)","v":"0,2%","o":7},
{"n":"Dolomite","f":"Densità materia prima","v":"2,85 g/ml","o":8},
{"n":"Dolomite","f":"Densità apparente (packed bulk)","v":"1,1 g/ml","o":9},
{"n":"Dolomite","f":"pH","v":"10","o":10},
{"n":"Dolomite","f":"Assorbimento olio","v":"15 g/100g","o":11},
{"n":"EDTA tetrasodico","f":"Formula molecolare","v":"C10H12N2O8Na4","o":0},
{"n":"EDTA tetrasodico","f":"Aspetto","v":"Liquido ambra chiaro","o":1},
{"n":"EDTA tetrasodico","f":"Assay (come Na4EDTA)","v":"39% min","o":2},
{"n":"EDTA tetrasodico","f":"pH (soluzione 1%)","v":"11,0–11,8","o":3},
{"n":"EDTA tetrasodico","f":"Peso specifico (25°C)","v":"1,31 (10,6 lbs/gal)","o":4},
{"n":"EDTA tetrasodico","f":"Viscosità (20°C)","v":"20 cps","o":5},
{"n":"EDTA tetrasodico","f":"Shelf life","v":"Almeno 5 anni in contenitore chiuso","o":6},
{"n":"EDTA tetrasodico","f":"Packaging disponibile","v":"Fusti 600 lb, cisternette 3000 lb, small packs","o":7},
{"n":"Elio","f":"Purezza He","v":"Instrument 4.6 ≥99,996%; Detector 5.0 ≥99,999%; Laboratory 5.6 ≥99,9996%; HiQ 6.0 ≥99,9999%","o":0},
{"n":"Elio","f":"Acqua (H2O)","v":"≤5 ppm (4.6) fino a ≤0,5 ppm (6.0)","o":1},
{"n":"Elio","f":"Ossigeno (O2)","v":"≤5 ppm (4.6) fino a ≤0,5 ppm (5.6/6.0)","o":2},
{"n":"Elio","f":"Idrocarburi totali (CnHm)","v":"≤1 ppm (4.6/5.0) fino a ≤0,1 ppm (5.6/6.0)","o":3},
{"n":"Elio","f":"Monossido di carbonio (CO)","v":"≤0,1 ppm (grado 6.0)","o":4},
{"n":"Elio","f":"Anidride carbonica (CO2)","v":"≤0,1 ppm (grado 6.0)","o":5},
{"n":"Elio","f":"Azoto (N2)","v":"≤5 ppm fino a ≤0,5 ppm","o":6},
{"n":"Elio","f":"Idrogeno (H2)","v":"≤0,5 ppm (5.6/6.0)","o":7},
{"n":"Elio","f":"Pressione di riempimento","v":"200 bar","o":8},
{"n":"Elio","f":"Caratteristiche","v":"Gas compresso, inerte","o":9},
{"n":"Esafluoruro di zolfo","f":"Purezza SF6","v":"Chemical 3.0 ≥99,9%; HiQ 5.0 ≥99,999%","o":0},
{"n":"Esafluoruro di zolfo","f":"Acqua (H2O)","v":"≤6 ppm (3.0) / ≤1 ppm (5.0)","o":1},
{"n":"Esafluoruro di zolfo","f":"Ossigeno+Azoto (O2+N2)","v":"≤500 ppm w/w (3.0) / ≤5 ppm (5.0)","o":2},
{"n":"Esafluoruro di zolfo","f":"Tetrafluorometano (CF4)","v":"≤400 ppm (3.0) / ≤5 ppm (5.0)","o":3},
{"n":"Esafluoruro di zolfo","f":"Acidità (come HF)","v":"≤0,3 ppm (3.0) / ≤0,1 ppm w/w (5.0)","o":4},
{"n":"Esafluoruro di zolfo","f":"Pressione di riempimento","v":"19 bar (15°C)","o":5},
{"n":"Esafluoruro di zolfo","f":"Caratteristiche","v":"Gas liquefatto, incolore","o":6},
{"n":"Esafluoruro di zolfo","f":"Conformità normativa","v":"ASTM D2472 & IEC (grado 3.0)","o":7},
{"n":"Esametafosfato di sodio (SHMP)","f":"Formula molecolare","v":"(NaPO3)x","o":0},
{"n":"Esametafosfato di sodio (SHMP)","f":"Peso molecolare","v":"101,96 g/mol","o":1},
{"n":"Esametafosfato di sodio (SHMP)","f":"pH (soluzione 1%)","v":"6,5–7,2","o":2},
{"n":"Esametafosfato di sodio (SHMP)","f":"Densità apparente","v":"min. 1,00 g/cc","o":3},
{"n":"Esametafosfato di sodio (SHMP)","f":"Umidità (100°C, 4h)","v":"max 0,50%","o":4},
{"n":"Esametafosfato di sodio (SHMP)","f":"Insolubile in acqua","v":"max 0,10%","o":5},
{"n":"Esametafosfato di sodio (SHMP)","f":"Fosfato come P2O5","v":"66,5–68,5%","o":6},
{"n":"Esametafosfato di sodio (SHMP)","f":"Perdita all'incenerimento","v":"max 1,00%","o":7},
{"n":"Esametafosfato di sodio (SHMP)","f":"Fluoruro come F","v":"max 10,0 ppm","o":8},
{"n":"Esametafosfato di sodio (SHMP)","f":"Arsenico come As","v":"max 3,0 ppm","o":9},
{"n":"Esametafosfato di sodio (SHMP)","f":"Piombo come Pb","v":"max 3,0 ppm","o":10},
{"n":"Esametafosfato di sodio (SHMP)","f":"Cadmio come Cd","v":"max 1,0 ppm","o":11},
{"n":"Esametafosfato di sodio (SHMP)","f":"Mercurio come Hg","v":"max 1,0 ppm","o":12},
{"n":"Esametafosfato di sodio (SHMP)","f":"Metalli pesanti come Pb","v":"max 10,0 ppm","o":13},
{"n":"Esametafosfato di sodio (SHMP)","f":"Granulometria","v":"Trattenuto su 20 mesh (850µm) max 20,0%; trattenuto su 100 mesh (150µm) max 35,0%","o":14},
{"n":"Essiccante al cobalto (cobalto octoato)","f":"Composizione","v":"Sali metallici dell'acido 2-etilesanoico (ottoati) in xilene","o":0},
{"n":"Essiccante al cobalto (cobalto octoato)","f":"Densità","v":"0,97 g/cm3 (20°C)","o":1},
{"n":"Essiccante al cobalto (cobalto octoato)","f":"Dosaggio tipico","v":"0,005–0,020% (come metallo su legante solido, in poliesteri insaturi)","o":2},
{"n":"Essiccante al cobalto (cobalto octoato)","f":"Condizioni di stoccaggio","v":"5–30°C, protetto dagli agenti atmosferici","o":3},
{"n":"Ethylhexyl methoxycinnamate (octinoxate)","f":"INCI","v":"Ethylhexyl Methoxycinnamate (Octinoxate, USA)","o":0},
{"n":"Ethylhexyl methoxycinnamate (octinoxate)","f":"Formula molecolare","v":"C18H26O3","o":1},
{"n":"Ethylhexyl methoxycinnamate (octinoxate)","f":"Peso molecolare","v":"290 g/mol","o":2},
{"n":"Ethylhexyl methoxycinnamate (octinoxate)","f":"Aspetto","v":"Liquido da incolore a giallo chiaro","o":3},
{"n":"Ethylhexyl methoxycinnamate (octinoxate)","f":"Odore","v":"Molto debole, caratteristico","o":4},
{"n":"Ethylhexyl methoxycinnamate (octinoxate)","f":"Assay","v":"95,0–105,0 g/100g (USP)","o":5},
{"n":"Ethylhexyl methoxycinnamate (octinoxate)","f":"Purezza (GC)","v":"min. 99,0% area","o":6},
{"n":"Ethylhexyl methoxycinnamate (octinoxate)","f":"Impurezze totali","v":"max 2,0% (singola impurezza max 0,5%)","o":7},
{"n":"Ethylhexyl methoxycinnamate (octinoxate)","f":"Assorbanza specifica (A1%/1cm, 310nm in etanolo)","v":"min. 850","o":8},
{"n":"Ethylhexyl methoxycinnamate (octinoxate)","f":"Colore (Hazen/APHA)","v":"max 70","o":9},
{"n":"Ethylhexyl methoxycinnamate (octinoxate)","f":"Indice di rifrazione n(20/D)","v":"1,542–1,548","o":10},
{"n":"Ethylhexyl methoxycinnamate (octinoxate)","f":"Peso specifico d(25/25)","v":"1,005–1,013","o":11},
{"n":"Ethylhexyl methoxycinnamate (octinoxate)","f":"Indice di perossido","v":"max 1,0 meq/kg (Ph.Eur. 2.5.5 Metodo A)","o":12},
{"n":"Ethylhexyl methoxycinnamate (octinoxate)","f":"Conformità farmacopea","v":"USP, Ph.Eur.","o":13},
{"n":"Ethylhexyl methoxycinnamate (octinoxate)","f":"Shelf life","v":"36 mesi","o":14},
{"n":"Ethylhexyl methoxycinnamate (octinoxate)","f":"Stabilizzanti","v":"BHT 0,07%","o":15},
{"n":"Ethylhexyl methoxycinnamate (octinoxate)","f":"Origine materia prima","v":"Sintetica (olio minerale/gas naturale)","o":16},
{"n":"Etilcellulosa","f":"Prodotto","v":"ETHOCEL Standard 300 Industrial Ethylcellulose","o":0},
{"n":"Etilcellulosa","f":"Perdita all'essiccamento","v":"≤ 2,0%","o":1},
{"n":"Etilcellulosa","f":"Viscosità (Ubbelohde, 5% sol.)","v":"270,0 - 330,0 mPa·s","o":2},
{"n":"Etilcellulosa","f":"Contenuto etossile","v":"48,0 - 49,5%","o":3},
{"n":"Etilcellulosa","f":"Cloruri (come NaCl)","v":"≤ 0,15%","o":4},
{"n":"Etilene","f":"Formula molecolare","v":"C2H4","o":0},
{"n":"Etilene","f":"Purezza (gradi disponibili)","v":"Chemical 2.5 ≥99,5% / HiQ 3.0 ≥99,9% / Scientific 3.5 ≥99,95%","o":1},
{"n":"Etilene","f":"Acqua (H2O)","v":"≤50 ppm (2.5) / ≤5 ppm (3.0-3.5)","o":2},
{"n":"Etilene","f":"Ossigeno (O2)","v":"≤15 ppm (2.5) / ≤10 ppm (3.0-3.5)","o":3},
{"n":"Etilene","f":"Altri idrocarburi (CnHm)","v":"≤1000 ppm (2.5-3.0) / ≤450 ppm (3.5)","o":4},
{"n":"Etilene","f":"Anidride carbonica (CO2)","v":"≤5 ppm","o":5},
{"n":"Etilene","f":"Azoto (N2)","v":"≤40 ppm","o":6},
{"n":"Etilene","f":"Pressione di riempimento","v":"76 bar (15°C)","o":7},
{"n":"Etilene","f":"Caratteristiche","v":"Liquefatto, infiammabile","o":8},
{"n":"EVA (etilene-vinilacetato)","f":"Nome sostanza","v":"Acetic acid ethenyl ester, polymer with ethene (ELVAX 3165)","o":0},
{"n":"EVA (etilene-vinilacetato)","f":"Aspetto","v":"Pellet, colore trasparente, odore estereo","o":1},
{"n":"EVA (etilene-vinilacetato)","f":"Punto di fusione","v":"89°C (192°F)","o":2},
{"n":"EVA (etilene-vinilacetato)","f":"Punto di congelamento","v":"68°C (154°F)","o":3},
{"n":"EVA (etilene-vinilacetato)","f":"Punto di infiammabilità (COC)","v":"260°C (500°F)","o":4},
{"n":"EVA (etilene-vinilacetato)","f":"Densità relativa (acqua=1)","v":"0,94","o":5},
{"n":"EVA (etilene-vinilacetato)","f":"Solubilità in acqua","v":"Trascurabile","o":6},
{"n":"EVA (etilene-vinilacetato)","f":"Temperatura di decomposizione","v":">235°C (455°F)","o":7},
{"n":"Fenolo","f":"Formula molecolare","v":"C6H6O","o":0},
{"n":"Fenolo","f":"Peso molecolare","v":"94,11","o":1},
{"n":"Fenolo","f":"Punto di fusione","v":"40,85°C","o":2},
{"n":"Fenolo","f":"Punto di ebollizione","v":"182°C","o":3},
{"n":"Fenolo","f":"pKa","v":"10,0 (25°C)","o":4},
{"n":"Fenolo","f":"Solubilità","v":"Solubile in acqua (50 mg/mL)","o":5},
{"n":"Fenolo","f":"Temperatura di stoccaggio","v":"2-8°C","o":6},
{"n":"Filo di rame","f":"Formula","v":"Cu","o":0},
{"n":"Filo di rame","f":"Peso molecolare","v":"63,55","o":1},
{"n":"Filo di rame","f":"Purezza","v":"99,9% (3N)","o":2},
{"n":"Filo di rame","f":"Aspetto","v":"Metallo rossastro","o":3},
{"n":"Filo di rame","f":"Punto di fusione","v":"1085°C","o":4},
{"n":"Filo di rame","f":"Punto di ebollizione","v":"2562°C","o":5},
{"n":"Filo di rame","f":"Densità","v":"8,96 g/cm3","o":6},
{"n":"Formaldeide (formalina)","f":"Denominazione prodotto","v":"Formaldehyde solution 37% w/w, Pharmpur, Ph.Eur., BP, USP, stabilizzata con metanolo","o":0},
{"n":"Formaldeide (formalina)","f":"Formula molecolare","v":"CH2O (M=30,03 g/mol)","o":1},
{"n":"Formaldeide (formalina)","f":"Titolo (assay acidimetrico)","v":"34,5 - 38,0%","o":2},
{"n":"Formaldeide (formalina)","f":"Metanolo (stabilizzante, GC v/v)","v":"9,0 - 15,0%","o":3},
{"n":"Formaldeide (formalina)","f":"Residuo all'incenerimento","v":"max 0,1%","o":4},
{"n":"Formaldeide (formalina)","f":"Densità","v":"1,09 g/cm3","o":5},
{"n":"Formaldeide (formalina)","f":"Punto di fusione","v":"< -15°C","o":6},
{"n":"Formaldeide (formalina)","f":"Punto di ebollizione","v":"93 - 96°C","o":7},
{"n":"Formaldeide (formalina)","f":"Punto di infiammabilità","v":"62°C","o":8},
{"n":"Formaldeide (formalina)","f":"pH (20°C)","v":"3 - 4","o":9},
{"n":"Formaldeide (formalina)","f":"Aspetto","v":"Incolore","o":10},
{"n":"Formaldeide (formalina)","f":"Conformità normativa","v":"Ph.Eur., BP, USP","o":11},
{"n":"Fosfato biammonico (DAP)","f":"Denominazione","v":"Diammonium Phosphate 18-46-0","o":0},
{"n":"Fosfato biammonico (DAP)","f":"Azoto totale (N)","v":"18% (tipico e garantito min.)","o":1},
{"n":"Fosfato biammonico (DAP)","f":"Fosfato disponibile (P2O5)","v":"46% (tipico e garantito min.)","o":2},
{"n":"Fosfato biammonico (DAP)","f":"Fosfato idrosolubile (P2O5)","v":"42% tipico","o":3},
{"n":"Fosfato biammonico (DAP)","f":"Umidità (H2O)","v":"2,2% tipico","o":4},
{"n":"Fosfato biammonico (DAP)","f":"Densità apparente (loose)","v":"58 lb/ft3 (930 kg/m3)","o":5},
{"n":"Fosfato biammonico (DAP)","f":"Angolo di riposo","v":"37°","o":6},
{"n":"Fosfato biammonico (DAP)","f":"Granulometria (2mm x 4mm)","v":"≥90%","o":7},
{"n":"Fosfato biammonico (DAP)","f":"Size Guide Number (SGN)","v":"295","o":8},
{"n":"Fosfato biammonico (DAP)","f":"Uniformity Index (UI)","v":"55","o":9},
{"n":"Fosfato di zinco (anticorrosivo)","f":"Denominazione/caratterizzazione chimica","v":"Zinc Phosphate ZP 10 - zinco ortofosfato idrato","o":0},
{"n":"Fosfato di zinco (anticorrosivo)","f":"Zinco come Zn","v":"50,5 - 52,0%","o":1},
{"n":"Fosfato di zinco (anticorrosivo)","f":"Fosforo come PO4³⁻","v":"47,0 - 49,0%","o":2},
{"n":"Fosfato di zinco (anticorrosivo)","f":"Cloruri idrosolubili","v":"max 0,025%","o":3},
{"n":"Fosfato di zinco (anticorrosivo)","f":"Solfati idrosolubili","v":"max 0,05%","o":4},
{"n":"Fosfato di zinco (anticorrosivo)","f":"Piombo come Pb","v":"max 10 ppm","o":5},
{"n":"Fosfato di zinco (anticorrosivo)","f":"Cadmio come Cd","v":"max 10 ppm","o":6},
{"n":"Fosfato di zinco (anticorrosivo)","f":"Perdita all'incenerimento (600°C)","v":"8,5 - 13,0%","o":7},
{"n":"Fosfato di zinco (anticorrosivo)","f":"Conducibilità","v":"max 150 µS/cm","o":8},
{"n":"Fosfato di zinco (anticorrosivo)","f":"pH","v":"6,0 - 8,0","o":9},
{"n":"Fosfato di zinco (anticorrosivo)","f":"Densità","v":"tipica 3,3 g/cm3","o":10},
{"n":"Fosfato di zinco (anticorrosivo)","f":"Densità apparente","v":"tipica 0,4 g/cm3","o":11},
{"n":"Fosfato di zinco (anticorrosivo)","f":"Densità pressata (tamped)","v":"tipica 0,8 g/cm3","o":12},
{"n":"Fosfato di zinco (anticorrosivo)","f":"Assorbimento olio","v":"tipico 20 g/100g","o":13},
{"n":"Fosfato di zinco (anticorrosivo)","f":"Residuo al setaccio (32 µm)","v":"max 0,01%","o":14},
{"n":"Fosfato di zinco (anticorrosivo)","f":"Granulometria media","v":"2,0 - 3,5 µm","o":15},
{"n":"Fosfato monoammonico (MAP)","f":"Composizione","v":"Acido fosforico, sale di ammonio (1:1), 100%","o":0},
{"n":"Fosfato monoammonico (MAP)","f":"Aspetto","v":"Polvere bianca, inodore","o":1},
{"n":"Fosfato monoammonico (MAP)","f":"pH","v":"4,4 - 4,9","o":2},
{"n":"Fosfato monoammonico (MAP)","f":"Peso specifico","v":"1,8","o":3},
{"n":"Fosfato monoammonico (MAP)","f":"Solubilità in acqua","v":"29,4%","o":4},
{"n":"Fruttosio","f":"Formula empirica","v":"C6H12O6","o":0},
{"n":"Fruttosio","f":"Peso molecolare","v":"180,16","o":1},
{"n":"Fruttosio","f":"Titolo (assay)","v":"≥99% (HPLC)","o":2},
{"n":"Fruttosio","f":"Forma","v":"Polvere","o":3},
{"n":"Fruttosio","f":"Impurezze","v":"≤0,05% glucosio (enzimatico)","o":4},
{"n":"Fruttosio","f":"Colore","v":"Incolore","o":5},
{"n":"Fruttosio","f":"Range pH utile","v":"5,0-7 (25°C, 18 g/L)","o":6},
{"n":"Fruttosio","f":"Punto di fusione","v":"119-122°C (dec.)","o":7},
{"n":"Fruttosio","f":"Solubilità","v":"Acqua: 790 g/L a 20°C","o":8},
{"n":"Fruttosio","f":"Fonte biologica","v":"Mais","o":9},
{"n":"Fruttosio","f":"Temperatura di stoccaggio","v":"Ambiente","o":10},
{"n":"Ftalocianina blu","f":"Composizione","v":"Phthalocyanine blue (CAS 147-14-8) >94%","o":0},
{"n":"Ftalocianina blu","f":"Formula molecolare","v":"C32H16CuN8","o":1},
{"n":"Ftalocianina blu","f":"Peso molecolare","v":"576,08","o":2},
{"n":"Ftalocianina blu","f":"Sinonimi","v":"C.I. 74160, Pigment Blue 15","o":3},
{"n":"Ftalocianina blu","f":"Aspetto","v":"Polvere solida, colore blu scuro","o":4},
{"n":"Ftalocianina blu","f":"Punto di fusione","v":"480°C (896°F)","o":5},
{"n":"Ftalocianina blu","f":"Solubilità in acqua","v":"Praticamente insolubile","o":6},
{"n":"Ftalocianina blu","f":"Log Pow","v":"6,6","o":7},
{"n":"Ftalocianina verde","f":"Denominazione/Classe chimica","v":"Pigment Green 7 (C.I. No 74260) - Phthalocyanine","o":0},
{"n":"Ftalocianina verde","f":"Assorbimento olio","v":"≤45 cc","o":1},
{"n":"Ftalocianina verde","f":"Densità apparente (Bulk Density)","v":"1,6 g/cm3","o":2},
{"n":"Ftalocianina verde","f":"pH","v":"6-8","o":3},
{"n":"Ftalocianina verde","f":"Residuo al setaccio (45 µ)","v":"<1%","o":4},
{"n":"Ftalocianina verde","f":"Contenuto d'acqua (umidità)","v":"max 1%","o":5},
{"n":"Gelatina alimentare","f":"Composizione","v":"Gelatina derivata da cotenna di maiale (Pig Skin Derived Gelatin), 100%","o":0},
{"n":"Gelatina alimentare","f":"Aspetto","v":"Polvere, composto granulare secco","o":1},
{"n":"Gelatina alimentare","f":"Colore","v":"Ambra","o":2},
{"n":"Gelatina alimentare","f":"pH","v":"4,5 - 7,5","o":3},
{"n":"Gelatina alimentare","f":"Densità relativa","v":"0,5 - 0,8 g/cm3","o":4},
{"n":"Gelatina alimentare","f":"Viscosità dinamica","v":"<10 mPa·s (60°C, 6,67% in acqua)","o":5},
{"n":"Gelatina alimentare","f":"Temperatura di decomposizione","v":"circa 100°C","o":6},
{"n":"Gelatina enologica","f":"Composizione","v":"Gelatina alimentare in polvere, alto peso molecolare","o":0},
{"n":"Gelatina enologica","f":"Aspetto","v":"Microgranuli di colore bianco","o":1},
{"n":"Gelatina enologica","f":"Dosi d'uso","v":"Vino bianco 2-8 g/hl; vino rosso 4-10 g/hl; mosti/vini molto torbidi 5-15 g/hl","o":2},
{"n":"Gelatina enologica","f":"Modalità d'uso","v":"Solubilizzare in acqua calda (35-40°C) in rapporto 1:20","o":3},
{"n":"Gelatina enologica","f":"Packaging disponibile","v":"Sacchetto da 1 kg","o":4},
{"n":"Gelatina enologica","f":"Conformità normativa","v":"Codex Œnologique International; Reg. CE 834/2007 e 889/2008 (biologico); Reg. CE 606/2009; Reg. UE 203/2012","o":5},
{"n":"Gesso agricolo (solfato di calcio)","f":"Denominazione","v":"USG Calcium Sulfate Feed Grade - Regular Grind","o":0},
{"n":"Gesso agricolo (solfato di calcio)","f":"Solfato di calcio diidrato equiv. (Gesso, CaSO4·2H2O)","v":"90%","o":1},
{"n":"Gesso agricolo (solfato di calcio)","f":"Solfato di calcio equiv. (CaSO4)","v":"71%","o":2},
{"n":"Gesso agricolo (solfato di calcio)","f":"Calcio (Ca)","v":"20%","o":3},
{"n":"Gesso agricolo (solfato di calcio)","f":"Zolfo (S)","v":"16%","o":4},
{"n":"Gesso agricolo (solfato di calcio)","f":"pH","v":"7,2","o":5},
{"n":"Gesso agricolo (solfato di calcio)","f":"Granulometria (% passante)","v":"4 mesh 100%; 8 mesh 100%; 16 mesh 99,93%; 50 mesh 98,58%; 100 mesh 92,48%; 200 mesh 76,14%; 325 mesh 58,82%","o":6},
{"n":"Gesso agricolo (solfato di calcio)","f":"Densità apparente","v":"62 lb/ft3 (loose) / ~68 lb/ft3 (packed)","o":7},
{"n":"Gesso agricolo (solfato di calcio)","f":"Conformità/certificazioni","v":"OMRI (biologico), Halal, Kosher","o":8},
{"n":"Ghiaccio secco (CO2 solida)","f":"Formula","v":"CO2","o":0},
{"n":"Ghiaccio secco (CO2 solida)","f":"Stato fisico","v":"Gas / gas solidificato refrigerato","o":1},
{"n":"Ghiaccio secco (CO2 solida)","f":"Aspetto/Colore","v":"Solido bianco","o":2},
{"n":"Ghiaccio secco (CO2 solida)","f":"Punto di fusione (sublimazione)","v":"78,5°C (come riportato in fonte; a pressione atmosferica il ghiaccio secco sublima)","o":3},
{"n":"Ghiaccio secco (CO2 solida)","f":"Punto di ebollizione","v":"56,6°C (come riportato in fonte)","o":4},
{"n":"Ghiaccio secco (CO2 solida)","f":"Temperatura critica","v":"30°C","o":5},
{"n":"Ghiaccio secco (CO2 solida)","f":"Pressione di vapore","v":"57,3 bar(a)","o":6},
{"n":"Ghiaccio secco (CO2 solida)","f":"Densità relativa","v":"1,03 (densità gas relativa 1,52)","o":7},
{"n":"Ghiaccio secco (CO2 solida)","f":"Solubilità in acqua","v":"2000 mg/l (completamente solubile)","o":8},
{"n":"Ghiaccio secco (CO2 solida)","f":"Massa molecolare","v":"44 g/mol","o":9},
{"n":"Glicole etilenico (MEG)","f":"Formula","v":"HOCH2CH2OH","o":0},
{"n":"Glicole etilenico (MEG)","f":"Peso molecolare","v":"62,07 g/mol","o":1},
{"n":"Glicole etilenico (MEG)","f":"Punto di ebollizione normale","v":"197,4°C @ 1013,25 hPa","o":2},
{"n":"Glicole etilenico (MEG)","f":"Punto di congelamento normale","v":"-11,2°C","o":3},
{"n":"Glicole etilenico (MEG)","f":"Punto di infiammabilità (vaso chiuso)","v":"111°C","o":4},
{"n":"Glicole etilenico (MEG)","f":"Densità relativa (20/20°C)","v":"1,1153","o":5},
{"n":"Glicole etilenico (MEG)","f":"Solubilità in acqua (20°C)","v":"100% in peso (miscibile completamente)","o":6},
{"n":"Glicole etilenico (MEG)","f":"Viscosità dinamica (20°C)","v":"19,83 mPa·s","o":7},
{"n":"Glicole etilenico (MEG)","f":"Indice di rifrazione (nD, 25°C)","v":"1,4306","o":8},
{"n":"Glicole etilenico (MEG)","f":"Pressione di vapore (20°C)","v":"0,067 hPa","o":9},
{"n":"Glicole etilenico (MEG)","f":"Temperatura di autoaccensione","v":"398°C","o":10},
{"n":"Glicole etilenico (MEG)","f":"Tensione superficiale (25°C)","v":"48,0 mN/m","o":11},
{"n":"Glicole etilenico (MEG)","f":"Conformità normativa (produzione)","v":"ISO 9001","o":12},
{"n":"Glicole propilenico (MPG)","f":"Composizione (1,2-propandiolo)","v":"≥80 – ≤100% (intervallo dichiarato come segreto commerciale)","o":0},
{"n":"Glicole propilenico (MPG)","f":"Peso molecolare","v":"76,09 g/mol","o":1},
{"n":"Glicole propilenico (MPG)","f":"Punto di fusione","v":"-60 °C","o":2},
{"n":"Glicole propilenico (MPG)","f":"Punto di ebollizione","v":"187 °C","o":3},
{"n":"Glicole propilenico (MPG)","f":"Punto di infiammabilità","v":"104 °C (vaso chiuso)","o":4},
{"n":"Glicole propilenico (MPG)","f":"Densità","v":"1,036 g/cm³ (25 °C); densità relativa 1,03 (20 °C)","o":5},
{"n":"Glicole propilenico (MPG)","f":"Viscosità","v":"12,78 mPa·s (45 °C)","o":6},
{"n":"Glicole propilenico (MPG)","f":"pH","v":"7,1 – 7,8 (soluzione acquosa)","o":7},
{"n":"Glicole propilenico (MPG)","f":"Solubilità","v":"Completamente miscibile in acqua (20 °C)","o":8},
{"n":"Glicole propilenico (MPG)","f":"Temperatura di autoaccensione","v":">400 °C","o":9},
{"n":"Glicole propilenico metiletere (PGME)","f":"Formula molecolare","v":"CH3OCH2CHOHCH3 (isomero maggioritario)","o":0},
{"n":"Glicole propilenico metiletere (PGME)","f":"Peso molecolare","v":"90,1 g/mol","o":1},
{"n":"Glicole propilenico metiletere (PGME)","f":"Punto di ebollizione","v":"120 °C (760 mmHg)","o":2},
{"n":"Glicole propilenico metiletere (PGME)","f":"Punto di infiammabilità","v":"31 °C (Setaflash, vaso chiuso)","o":3},
{"n":"Glicole propilenico metiletere (PGME)","f":"Punto di congelamento","v":"-97 °C","o":4},
{"n":"Glicole propilenico metiletere (PGME)","f":"Densità","v":"0,921 g/cm³ (20 °C); 0,916 g/cm³ (25 °C)","o":5},
{"n":"Glicole propilenico metiletere (PGME)","f":"Peso specifico","v":"0,919 (25/25 °C)","o":6},
{"n":"Glicole propilenico metiletere (PGME)","f":"Viscosità","v":"1,7 cP (25 °C)","o":7},
{"n":"Glicole propilenico metiletere (PGME)","f":"Tensione superficiale","v":"27,7 mN/m (25 °C)","o":8},
{"n":"Glicole propilenico metiletere (PGME)","f":"Tensione di vapore","v":"0,87 mmHg (20 °C, estrapolato)","o":9},
{"n":"Glicole propilenico metiletere (PGME)","f":"Temperatura di autoaccensione","v":"287 °C","o":10},
{"n":"Glicole propilenico metiletere (PGME)","f":"Limiti di infiammabilità","v":"1,48 – 13,74 % vol (misurati a 150 °C)","o":11},
{"n":"Glicole propilenico metiletere (PGME)","f":"Calore specifico","v":"2,44 J/g/°C (25 °C)","o":12},
{"n":"Glifosate tecnico","f":"Formula molecolare","v":"C3H8NO5P","o":0},
{"n":"Glifosate tecnico","f":"Peso molecolare","v":"169,1 g/mol","o":1},
{"n":"Glifosate tecnico","f":"Aspetto","v":"Polvere bianca (secca/cristallina), priva di impurità estranee visibili","o":2},
{"n":"Glifosate tecnico","f":"Purezza (titolo acido glifosate)","v":"Dichiarata, non inferiore a 950 g/kg (min. 95%) – Spec. FAO 284/TC","o":3},
{"n":"Glifosate tecnico","f":"Formaldeide (impurità)","v":"Massimo 1,3 g/kg del contenuto di acido glifosate","o":4},
{"n":"Glifosate tecnico","f":"N-Nitrosoglifosate (impurità)","v":"Massimo 1 mg/kg","o":5},
{"n":"Glifosate tecnico","f":"Densità relativa","v":"1,67 ± 0,02 (20 °C)","o":6},
{"n":"Glifosate tecnico","f":"pH","v":"1,86 – 1,90","o":7},
{"n":"Glifosate tecnico","f":"Punto di fusione","v":">295 °C","o":8},
{"n":"Glifosate tecnico","f":"Tensione di vapore","v":"1,2636×10⁻⁵ Pa","o":9},
{"n":"Glifosate tecnico","f":"Solubilità in acqua","v":"12,91 ± 0,25 g/l (30 °C)","o":10},
{"n":"Glifosate tecnico","f":"Punto di infiammabilità","v":"Non infiammabile","o":11},
{"n":"Glucosio (destrosio)","f":"Formula molecolare","v":"C6H12O6","o":0},
{"n":"Glucosio (destrosio)","f":"Peso molecolare","v":"180,16 g/mol","o":1},
{"n":"Glucosio (destrosio)","f":"Aspetto","v":"Polvere cristallina, bianca","o":2},
{"n":"Glucosio (destrosio)","f":"Punto di fusione","v":"150 – 152 °C","o":3},
{"n":"Glucosio (destrosio)","f":"Solubilità","v":"Solubile in acqua","o":4},
{"n":"Glutammato monosodico (MSG)","f":"Aspetto","v":"Cristalli piccoli, biancastri","o":0},
{"n":"Glutammato monosodico (MSG)","f":"Aroma/Sapore","v":"Leggermente salato","o":1},
{"n":"Glutammato monosodico (MSG)","f":"Titolo (Content)","v":"Min. 99,0%","o":2},
{"n":"Glutammato monosodico (MSG)","f":"Cloruri","v":"Max 0,1%","o":3},
{"n":"Glutammato monosodico (MSG)","f":"Perdita all'essiccamento","v":"Max 0,5%","o":4},
{"n":"Glutammato monosodico (MSG)","f":"Solfati","v":"Max 0,05%","o":5},
{"n":"Glutammato monosodico (MSG)","f":"Trasmittanza","v":"Min. 98,0%","o":6},
{"n":"Glutammato monosodico (MSG)","f":"Rotazione ottica specifica [α]D 20°C (sol. 10%)","v":"+24,9 / +25,3°","o":7},
{"n":"Glutammato monosodico (MSG)","f":"pH","v":"6,7 – 7,5","o":8},
{"n":"Glutammato monosodico (MSG)","f":"Acido pirrolidoncarbossilico","v":"Max 0,2%","o":9},
{"n":"Glutammato monosodico (MSG)","f":"Ferro","v":"Max 5 mg/kg","o":10},
{"n":"Glutammato monosodico (MSG)","f":"Piombo (Pb)","v":"Max 1 mg/kg","o":11},
{"n":"Glutammato monosodico (MSG)","f":"Packaging disponibile","v":"Sacchi poli-lined da 25 kg","o":12},
{"n":"Glutammato monosodico (MSG)","f":"Shelf life","v":"3 anni (36 mesi) in confezione originale non aperta","o":13},
{"n":"Glutaraldeide","f":"Concentrazione (glutaral)","v":"50% p/p (soluzione acquosa)","o":0},
{"n":"Glutaraldeide","f":"Aspetto","v":"Liquido limpido","o":1},
{"n":"Glutaraldeide","f":"Odore","v":"Fruttato","o":2},
{"n":"Glutaraldeide","f":"pH","v":"3,1 – 4,5 (20 °C, concentrazione 100%)","o":3},
{"n":"Glutaraldeide","f":"Punto di congelamento","v":"-18 °C","o":4},
{"n":"Glutaraldeide","f":"Punto di ebollizione","v":"100,7 °C","o":5},
{"n":"Glutaraldeide","f":"Densità","v":"1,13 g/cm³ (20 °C); densità relativa 1,129","o":6},
{"n":"Glutaraldeide","f":"Viscosità","v":"15,4 cps (25 °C, dinamica); 20,2 mm²/s (20 °C, cinematica)","o":7},
{"n":"Glutaraldeide","f":"Tensione di vapore","v":"0,399 hPa (20 °C)","o":8},
{"n":"Glutaraldeide","f":"Peso molecolare","v":"100,12 g/mol (componente principale)","o":9},
{"n":"Glutaraldeide","f":"Solubilità in acqua","v":"Completamente solubile","o":10},
{"n":"Glutaraldeide","f":"Temperatura di accensione","v":"385 °C","o":11},
{"n":"Glutaraldeide","f":"Conformità normativa (FDA)","v":"Conforme a normative FDA 21 CFR 172.230, 173.320(b)(6), 173.357, 175.105(c)(5), 176.170(a)(5), 176.180(b)(1), 176.300 per usi specifici (agente reticolante/antimicrobico)","o":12},
{"n":"Glutine di frumento","f":"Umidità (Moisture)","v":"8,0% max","o":0},
{"n":"Glutine di frumento","f":"Contenuto proteico (N x 5,7, base secca)","v":"75,0% min","o":1},
{"n":"Glutine di frumento","f":"Ceneri (Ash)","v":"1,0% max","o":2},
{"n":"Glutine di frumento","f":"Granulometria","v":"min. 98,0% passante a 40 mesh US Std","o":3},
{"n":"Glutine di frumento","f":"Packaging disponibile","v":"Sacchi kraft multistrato, peso netto 50 lbs (22,7 kg); disponibili spedizione sfusa o altri imballi","o":4},
{"n":"Glutine di frumento","f":"Shelf life","v":"2 anni dalla data di produzione (stoccaggio fresco, asciutto, in area sanitaria)","o":5},
{"n":"Glyceryl stearate","f":"Formula molecolare","v":"C17H35OCOCH2CH(OH)CH2OH","o":0},
{"n":"Glyceryl stearate","f":"Peso molecolare","v":"358,56 g/mol","o":1},
{"n":"Glyceryl stearate","f":"Stato fisico","v":"Solido","o":2},
{"n":"Glyceryl stearate","f":"Coefficiente di ripartizione (log Pow)","v":"6,1","o":3},
{"n":"Gomma arabica","f":"Colore (soluzione acquosa al 25%)","v":"Max 7","o":0},
{"n":"Gomma arabica","f":"pH (soluzione acquosa al 25%)","v":"4,1 – 4,8","o":1},
{"n":"Gomma arabica","f":"Densità","v":"0,4 – 0,5 kg/l","o":2},
{"n":"Gomma arabica","f":"Solubilità in acqua","v":"400 – 500 g/L","o":3},
{"n":"Gomma arabica","f":"Viscosità (20°C, soluzione al 25%)","v":"60 – 130 mPa·s","o":4},
{"n":"Gomma arabica","f":"Packaging disponibile","v":"Sacco in polietilene","o":5},
{"n":"Gomma di guar","f":"Composizione chimica","v":"Galattomannano, polisaccaride ad alto peso molecolare (galattosio e mannosio) ottenuto dall'endosperma di Cyamopsis tetragonolobus","o":0},
{"n":"Gomma di guar","f":"pH","v":"5,4 – 7,0 (in dispersione acquosa)","o":1},
{"n":"Gomma di guar","f":"Numero INS / E number","v":"INS 412 / E412","o":2},
{"n":"Gomma di guar","f":"Metalli pesanti (come Pb)","v":"Non più di (NMT) 2 mg/kg (conforme FCC)","o":3},
{"n":"Gomma di guar","f":"Solubilità","v":"Dispersibile in acqua calda o fredda formando un sol; forma gel con aggiunta di borato di sodio","o":4},
{"n":"Gomma di guar","f":"Conformità normativa","v":"FCC; USA 21 CFR 184.1339; USP <467> (solventi residui)","o":5},
{"n":"Gomma xantano","f":"Granulometria","v":"-28 mesh (600 µm): min 98% passante; -42 mesh (355 µm): min 92% passante","o":0},
{"n":"Gomma xantano","f":"Perdita all'essiccamento","v":"6 – 16%","o":1},
{"n":"Gomma xantano","f":"Colore polvere","v":"Non meno di 69","o":2},
{"n":"Gomma xantano","f":"Viscosità (1% in acqua DI, 60 rpm)","v":"800 – 1200 mPa·s (cP)","o":3},
{"n":"Gomma xantano","f":"pH (soluzione 1% in acqua DI)","v":"5,5 – 8,5","o":4},
{"n":"Gomma xantano","f":"Shelf life","v":"1095 giorni (3 anni) dalla data di produzione","o":5},
{"n":"Gomma xantano","f":"Packaging disponibile","v":"Sacchi multistrato con valvola da 25 kg","o":6},
{"n":"Gomma xantano","f":"Conformità normativa","v":"TSCA, EINECS, DSL, AICS, ECL, ENCS, PICCS, inventario chimico Cina; sistema qualità ISO 9001","o":7},
{"n":"HDPE riciclato (rHDPE)","f":"Densità","v":"0,957 g/cm³ (ISO 1183)","o":0},
{"n":"HDPE riciclato (rHDPE)","f":"Indice di fluidità (MFR 190°C/2,16 kg)","v":"2,5 g/10 min (ISO 1133/D)","o":1},
{"n":"HDPE riciclato (rHDPE)","f":"Modulo elastico a trazione","v":"1200 MPa (ISO 527)","o":2},
{"n":"HDPE riciclato (rHDPE)","f":"Temperatura di fusione","v":"130°C (ISO 11357)","o":3},
{"n":"HDPE riciclato (rHDPE)","f":"Contenuto di materiale riciclato (PCR content)","v":"50%","o":4},
{"n":"HDPE riciclato (rHDPE)","f":"Colore","v":"Grigio scuro","o":5},
{"n":"HDPE riciclato (rHDPE)","f":"Forma","v":"Granuli (pellet), contenente antiossidanti","o":6},
{"n":"Idrogeno","f":"Formula molecolare","v":"H2","o":0},
{"n":"Idrogeno","f":"Purezza gas (grado Instrument hydrogen 4.5)","v":"≥ 99,995% H2; H2O ≤ 5 ppm; O2 ≤ 5 ppm; idrocarburi totali (CnHm) ≤ 0,5 ppm; CO+CO2 ≤ 0,2 ppm; N2 ≤ 4 ppm","o":1},
{"n":"Idrogeno","f":"Purezza gas (grado Detector hydrogen 5.0)","v":"≥ 99,999% H2; H2O ≤ 4 ppm; O2 ≤ 2 ppm; idrocarburi totali (CnHm) ≤ 0,1 ppm; N2 ≤ 3 ppm","o":2},
{"n":"Idrogeno","f":"Purezza gas (grado Laboratory hydrogen 5.5)","v":"≥ 99,9995% H2; H2O ≤ 2 ppm; O2 ≤ 1 ppm; idrocarburi totali (CnHm) ≤ 0,1 ppm; CO ≤ 0,1 ppm; CO2 ≤ 0,1 ppm","o":3},
{"n":"Idrogeno","f":"Purezza gas (grado HiQ hydrogen 6.0)","v":"≥ 99,9999% H2; H2O ≤ 0,5 ppm; O2 ≤ 0,5 ppm; N2 ≤ 0,5 ppm","o":4},
{"n":"Idrogeno","f":"Pressione di riempimento","v":"200 bar","o":5},
{"n":"Idrogeno","f":"Caratteristiche","v":"Gas compresso, infiammabile","o":6},
{"n":"Idrogeno","f":"Colore bombola","v":"Rosso","o":7},
{"n":"Idrogeno","f":"Valvola di erogazione","v":"DIN 477 No. 1","o":8},
{"n":"Inulina","f":"Aspetto","v":"Polvere bianca","o":0},
{"n":"Inulina","f":"Descrizione chimica","v":"Fruttano vegetale indigeribile; miscela di polimeri β-2,1 di fruttosio per lo più legati a un residuo terminale di glucosio; grado di polimerizzazione tra 3 e 60","o":1},
{"n":"Inulina","f":"Origine/Processo produttivo","v":"Estratta da radice di cicoria (Cichorium intybus), agave blu o Jerusalem Artichoke tramite diffusione in acqua calda, purificazione ed essiccazione","o":2},
{"n":"Inulina","f":"Solubilità","v":"Molto solubile in acqua calda; leggermente solubile in acqua fredda; quasi insolubile nella maggior parte dei solventi organici","o":3},
{"n":"Inulina","f":"Metalli pesanti (come Pb)","v":"Non più di 1 mg/kg (conforme FCC)","o":4},
{"n":"Inulina","f":"Solventi residui/organici","v":"Conforme a USP <467>; nessun solvente di classe 1, 2, 3 utilizzato","o":5},
{"n":"Inulina","f":"Conformità normativa","v":"Food Chemicals Codex (FCC); GRAS (FDA, GRN 118 cicoria, GRN 1019/854 agave)","o":6},
{"n":"Iodopovidone (PVP-iodio)","f":"Formula molecolare","v":"(C6H9NO)n·xI","o":0},
{"n":"Iodopovidone (PVP-iodio)","f":"Peso molecolare","v":"Variabile","o":1},
{"n":"Iodopovidone (PVP-iodio)","f":"Composizione","v":"Complesso di polivinilpirrolidone (Povidone, PVP) e iodio elementare","o":2},
{"n":"Iodopovidone (PVP-iodio)","f":"Aspetto","v":"Polvere amorfa da giallo-bruno a rosso-bruno, odore leggero caratteristico","o":3},
{"n":"Iodopovidone (PVP-iodio)","f":"Solubilità","v":"Solubile in acqua e alcol; praticamente insolubile in cloroformio, tetracloruro di carbonio, etere, esano e acetone; soluzione acida al tornasole","o":4},
{"n":"Iodopovidone (PVP-iodio)","f":"Perdita all'essiccamento (Ph.Eur./USP/IP)","v":"Non più di 8,0%","o":5},
{"n":"Iodopovidone (PVP-iodio)","f":"Residuo all'incenerimento (USP)","v":"Non più di 0,025%","o":6},
{"n":"Iodopovidone (PVP-iodio)","f":"Ceneri solfatate (Ph.Eur./IP)","v":"Massimo 0,1%","o":7},
{"n":"Iodopovidone (PVP-iodio)","f":"Ioduro su base secca (USP/IP)","v":"Non più di 6,6%","o":8},
{"n":"Iodopovidone (PVP-iodio)","f":"Ioduro su base secca (Ph.Eur./IP)","v":"Non più di 6,0%","o":9},
{"n":"Iodopovidone (PVP-iodio)","f":"pH (Ph.Eur.)","v":"1,5 - 5,0","o":10},
{"n":"Iodopovidone (PVP-iodio)","f":"Metalli pesanti (USP)","v":"Non più di 0,002%","o":11},
{"n":"Iodopovidone (PVP-iodio)","f":"Contenuto di azoto su base secca (USP)","v":"9,5% - 11,5%","o":12},
{"n":"Iodopovidone (PVP-iodio)","f":"Assay - iodio disponibile (Ph.Eur./USP/IP)","v":"9,0% - 12,0%","o":13},
{"n":"Iodopovidone (PVP-iodio)","f":"Granulometria (micronizzato, in-house)","v":"~97% passante a 100 mesh","o":14},
{"n":"Iodopovidone (PVP-iodio)","f":"Densità apparente (in-house)","v":"~0,65 g/mL","o":15},
{"n":"Iodopovidone (PVP-iodio)","f":"Conformità normativa/farmacopea","v":"BP/EP/USP/IP","o":16},
{"n":"Iodopovidone (PVP-iodio)","f":"Packaging disponibile","v":"Fusti in plastica o fibra da 25 kg netti con liner interno; fusti plastici UN approvati 25 kg (Classe 9, UN 3077)","o":17},
{"n":"Iodopovidone (PVP-iodio)","f":"Shelf life","v":"3 anni dalla data di produzione","o":18},
{"n":"Ipoclorito di sodio","f":"Formula molecolare","v":"NaClO (soluzione acquosa)","o":0},
{"n":"Ipoclorito di sodio","f":"Aspetto","v":"Liquido limpido, giallo-verde, con odore caratteristico","o":1},
{"n":"Ipoclorito di sodio","f":"Cloro attivo (Cl2)","v":"Min. 150 g/l alla consegna; min. 12,5% in peso; min. 47 gradi clorometrici","o":2},
{"n":"Ipoclorito di sodio","f":"Densità (20°C)","v":"1,205 - 1,260 kg/l","o":3},
{"n":"Ipoclorito di sodio","f":"Idrossido di sodio (NaOH)","v":"0,2 - 1,0% in peso","o":4},
{"n":"Ipoclorito di sodio","f":"Ferro (Fe)","v":"Massimo 2,0 ppm","o":5},
{"n":"Ipoclorito di sodio","f":"Conformità normativa","v":"EN 901 tipo 1 (norma europea per trattamento acqua potabile)","o":6},
{"n":"Ipoclorito di sodio","f":"Shelf life","v":"1 mese dalla data di produzione (conservare al fresco e al buio)","o":7},
{"n":"Ipoclorito di sodio","f":"Packaging disponibile","v":"Sfuso, IBC, fusti, taniche","o":8},
{"n":"Ipoclorito di sodio (candeggina)","f":"Formula molecolare","v":"NaClO","o":0},
{"n":"Ipoclorito di sodio (candeggina)","f":"Aspetto","v":"Liquido limpido, giallo-verde, con odore caratteristico","o":1},
{"n":"Ipoclorito di sodio (candeggina)","f":"Cloro attivo (Cl2)","v":"min. 150 g/l alla consegna; min. 12,5% in peso; min. 47° cloro-metrici","o":2},
{"n":"Ipoclorito di sodio (candeggina)","f":"Densità (20°C)","v":"1,205 – 1,260 kg/l","o":3},
{"n":"Ipoclorito di sodio (candeggina)","f":"Idrossido di sodio (NaOH)","v":"0,2 – 1,0% in peso","o":4},
{"n":"Ipoclorito di sodio (candeggina)","f":"Ferro (Fe)","v":"max. 2,0 ppm","o":5},
{"n":"Ipoclorito di sodio (candeggina)","f":"pH","v":"12 (soluzione 160 g/l)","o":6},
{"n":"Ipoclorito di sodio (candeggina)","f":"Punto di ebollizione","v":"100°C","o":7},
{"n":"Ipoclorito di sodio (candeggina)","f":"Punto di fusione","v":"da -30°C a -20°C","o":8},
{"n":"Ipoclorito di sodio (candeggina)","f":"Viscosità (20°C)","v":"3 – 4 mPa·s","o":9},
{"n":"Ipoclorito di sodio (candeggina)","f":"Shelf life","v":"1 mese dalla data di produzione; conservare fresco e al buio","o":10},
{"n":"Ipoclorito di sodio (candeggina)","f":"Packaging disponibile","v":"Sfuso, IBC, fusti, taniche","o":11},
{"n":"Isobutanolo","f":"Formula molecolare","v":"C4H10O","o":0},
{"n":"Isobutanolo","f":"Peso molecolare","v":"74,12 g/mol","o":1},
{"n":"Isobutanolo","f":"Purezza/Assay","v":"Isobutanolo ≥99,5% – ≤100,0% (1-propanolo 0,001–0,2%; n-butanolo 0,001–0,3%)","o":2},
{"n":"Isobutanolo","f":"Aspetto","v":"Liquido limpido, odore alcolico","o":3},
{"n":"Isobutanolo","f":"Punto di fusione","v":"< -90°C","o":4},
{"n":"Isobutanolo","f":"Punto di ebollizione","v":"108°C (1.013 hPa)","o":5},
{"n":"Isobutanolo","f":"Punto di infiammabilità","v":"31°C (coppa chiusa)","o":6},
{"n":"Isobutanolo","f":"Densità (20°C)","v":"0,8017 g/cm³","o":7},
{"n":"Isobutanolo","f":"Viscosità (20°C)","v":"3,103 mPa·s","o":8},
{"n":"Isobutanolo","f":"Solubilità in acqua (20°C)","v":"70 g/l","o":9},
{"n":"Isobutanolo","f":"Tensione di vapore","v":"9,5 hPa (20°C); 70,7 hPa (50°C)","o":10},
{"n":"Isobutanolo","f":"Temperatura di autoaccensione","v":"400°C","o":11},
{"n":"Isobutanolo","f":"Limiti di esplosione","v":"1,1% – 11,7% (V)","o":12},
{"n":"Isopropanolo (IPA)","f":"Peso molecolare","v":"60 g/mol","o":0},
{"n":"Isopropanolo (IPA)","f":"Purezza","v":"min. 99,8% m/m (DIN 55685)","o":1},
{"n":"Isopropanolo (IPA)","f":"Contenuto d'acqua","v":"0,05% m/m","o":2},
{"n":"Isopropanolo (IPA)","f":"Densità (20°C)","v":"0,785 kg/l","o":3},
{"n":"Isopropanolo (IPA)","f":"Punto di ebollizione","v":"82°C","o":4},
{"n":"Isopropanolo (IPA)","f":"Punto di infiammabilità","v":"12°C","o":5},
{"n":"Isopropanolo (IPA)","f":"Temperatura di autoaccensione","v":"425°C","o":6},
{"n":"Isopropanolo (IPA)","f":"Limiti di esplosione","v":"2% – 12% v/v","o":7},
{"n":"Isopropanolo (IPA)","f":"Punto di congelamento","v":"-88°C","o":8},
{"n":"Isopropanolo (IPA)","f":"Viscosità (20°C)","v":"2,4 mPa·s","o":9},
{"n":"Isopropanolo (IPA)","f":"Indice di rifrazione (20°C)","v":"1,378","o":10},
{"n":"Isopropanolo (IPA)","f":"Tensione superficiale (20°C)","v":"23 mN/m","o":11},
{"n":"Isopropanolo (IPA)","f":"Contenuto VOC","v":"785 g/l","o":12},
{"n":"Isopropanolo (IPA)","f":"Solubilità","v":"Completamente miscibile con acqua","o":13},
{"n":"Isopropanolo (IPA)","f":"Azeotropo con acqua","v":"p. eb. 80,3°C; contenuto solvente 87,4% m/m","o":14},
{"n":"Isopropanolo (IPA)","f":"Conformità/Qualità","v":"Non contiene quantità rilevabili di metalli pesanti, composti clorurati o idrocarburi policiclici aromatici","o":15}]$j$::jsonb) as x(n text, f text, v text, o int);
  select md5(string_agg(rh, '' order by rh collate "C")) into got from (select md5(n||chr(31)||f||chr(31)||v||chr(31)||o::text) as rh from _stg_specs) q;
  if got is distinct from expected then
    raise exception 'specs batch 2 integrity check failed: expected % got %', expected, got;
  end if;
  insert into public.product_specs (product_id, campo, valore, ordine)
  select p.id, s.f, s.v, s.o from _stg_specs s join public.products p on lower(btrim(p.canonical_name)) = lower(btrim(s.n));
  get diagnostics n_ins = row_count;
  raise notice 'specs batch 2: staged=%, inserted=%', (select count(*) from _stg_specs), n_ins;
end
$mig$;
