-- Part A: ri-sync SDS/TDS su public.products. Match SOLO per nome.
-- Overwrite dove il CSV ha un valore non vuoto; mai azzerare un URL esistente.
do $mig$
declare
  expected text := 'd98270d44aff333ff0fb012fd3c64e77';
  got text;
  n_upd int;
begin
  create temp table _stg_sds on commit drop as select n, s, t from jsonb_to_recordset($j$[{"n":"2-Butossietanolo (butilglicole)","s":"https://download.basf.com/p1/000000000030034845_SDS_GEN_US/en_US/BUTYLGLYCOL_30034845_SDS_GEN_US_en_10-0.pdf","t":"https://chemicals.basf.com/dam/jcr:e97d38fe-d7a7-357a-b4aa-d90f08295c39/Alcohols_Glycol_Ethers_and_Acetates_from_BASF-Technical.pdf"},
{"n":"ABS","s":"https://b2b-safety-data-sheets.s3.us-east-2.amazonaws.com/INEOS+STYROLUTION+AMERICA/Novodur/Ineos_Novodur+ABS+Granulat_EN.pdf","t":"https://www.albis.com/en/products/download/doc/en/SI/styrolution/NovodurH701.pdf"},
{"n":"Acesulfame K","s":"https://www.sigmaaldrich.com/US/en/sds/SIAL/PHR1266","t":""},
{"n":"Acetato di butile","s":"https://www.sigmaaldrich.com/US/en/sds/sial/287725","t":"https://mgchemicals.com/downloads/tds/tds-9660-l.pdf"},
{"n":"Acetato di cellulosa","s":"https://www.chempoint.com/products/download?grade=3672&type=sds","t":""},
{"n":"Acetato di etile","s":"https://www.sigmaaldrich.com/US/en/sds/sial/270989","t":"https://mgchemicals.com/downloads/tds/tds-9620-l.pdf"},
{"n":"Acetilene","s":"https://certs-msds.airliquide.ca/Documents/SupportDoc/Acetylene_74-86-2_(CA-1001-05235)_EN_6.pdf","t":"https://static.prd.echannel.linde.com/wcsstore/SE_REN_Industrial_Gas_Store/pdf/EN/Acetylene_product_datasheet_EN.pdf"},
{"n":"Acetone","s":"https://www.sigmaaldrich.com/US/en/sds/sigald/179124","t":"https://www.advansix.com/wp-content/uploads/2023/02/Acetone-TDS.pdf"},
{"n":"Acetonitrile","s":"https://www.sigmaaldrich.com/US/en/sds/sial/271004","t":"https://www.ineos.com/show-document/?grade=Acetonitrile%20-%20HPLC&bu=INEOS%20Nitriles&documentType=SSS&docLanguage=EN&version=48cacf054908ec96c3ab0ac3830c6e23"},
{"n":"Acido acetico glaciale","s":"https://www.ineos.com/globalassets/ineos-group/businesses/ineos-acetyls/acetyls-america-documents/safety-data-sheet-acetic-acid.pdf","t":"https://www.ineos.com/globalassets/ineos-group/businesses/ineos-acetyls/acetyls-america-documents/acetic-acid-glacial-specification-sheet.pdf"},
{"n":"Acido amminotrimetilenfosfonico (ATMP)","s":"https://northmetal.net/wp-content/uploads/Amino-Trimethylene-Phosphonic-Acid-ATMP-C3H12NO9P3-DeQuest-2000-Belclene-640-Phos-2-NQ6400-6419-19-8-SDS.pdf","t":"https://northmetal.net/wp-content/uploads/Amino-Trimethylene-Phosphonic-Acid-ATMP-C3H12NO9P3-DeQuest-2000-Belclene-640-Phos-2-NQ6400-6419-19-8-TDS-2.pdf"},
{"n":"Acido ascorbico","s":"https://www.sigmaaldrich.com/US/en/sds/sial/a92902","t":"https://download.basf.com/p1/EN_StaticDocuments_6116/en/Technical_Information"},
{"n":"Acido ascorbico (vitamina C)","s":"https://www.sigmaaldrich.com/US/en/sds/sial/a92902","t":"https://download.basf.com/p1/EN_StaticDocuments_6116/en/Technical_Information"},
{"n":"Acido borico","s":"https://www.sigmaaldrich.com/US/en/sds/sigma/b7901","t":"https://www.etimineusa.com/wp-content/uploads/2020/01/TDS-of-Boric-Acid-M-normal-sulfate.pdf"},
{"n":"Acido citrico","s":"https://www.sigmaaldrich.com/US/en/sds/sial/251275","t":"https://www.cargill.com/doc/1432075932601/citric-acid-technical-data-sheet.pdf"},
{"n":"Acido cloridrico","s":"https://www.sigmaaldrich.com/US/en/sds/sial/258148","t":"https://www.atul.co.in/wp-content/uploads/BI_Hydrochloric-acid-30.pdf"},
{"n":"Acido etidronico (HEDP)","s":"https://northmetal.net/wp-content/uploads/Hydroxyethylidene-Diphosphonic-Acid-HEDP-C2H8O7P2-DeQuest-2010-Belclene-660-Codex-661-Phos-6-NQ6600-2809-21-4-SDS.pdf","t":"https://northmetal.net/wp-content/uploads/Hydroxyethylidene-Diphosphonic-Acid-HEDP-C2H8O7P2-DeQuest-2010-Belclene-660-Codex-661-Phos-6-NQ6600-2809-21-4-TDS-2.pdf"},
{"n":"Acido fosforico","s":"https://www.sigmaaldrich.com/US/en/sds/sigald/30417","t":"https://ingredi.com/content/pdfs/Phosphoric_Acid_85_PDS.pdf"},
{"n":"Acido fumarico","s":"https://www.sigmaaldrich.com/US/en/sds/sial/47910","t":"https://bisleyinternational.com/wp-content/uploads/2021/09/Fumaric-Acid-TDS.pdf"},
{"n":"Acido glicolico","s":"https://www.sigmaaldrich.com/US/en/sds/sial/124737","t":"https://www.eastharbourgroup.com/storage/download-files/glycolic-acid/Glycolic-Acid-TDS-315-V1.pdf"},
{"n":"Acido lattico","s":"https://www.sigmaaldrich.com/US/en/sds/sigma/l6661","t":"https://sbi4beer.com/wp-content/uploads/2020/12/TDS-Purac-80-Corbion-Purac-Rev09-230424-SBI.pdf"},
{"n":"Acido malico","s":"https://www.sigmaaldrich.com/US/en/sds/sial/94916","t":"https://ingredi.com/content/pdfs/Malic_Acid_TDS.pdf"},
{"n":"Acido malico (DL)","s":"https://www.sigmaaldrich.com/US/en/sds/sial/94916","t":"https://ingredi.com/content/pdfs/Malic_Acid_TDS.pdf"},
{"n":"Acido nitrico","s":"https://www.sigmaaldrich.com/US/en/sds/sial/695041","t":"https://trademarknitrogen.com/Portals/0/Images/PDF/TDS/Nitric-Acid_Industrial-TDS_TMN_2022.pdf"},
{"n":"Acido peracetico","s":"https://www.spectrumchemical.com/media/sds/P1023_AGHS.pdf","t":""},
{"n":"Acido salicilico","s":"https://www.sigmaaldrich.com/US/en/sds/sigma/s7401","t":"https://www.tnjchem.com/uploadfile/downloads/TDS-Salicylic-acid-69-72-7.pdf"},
{"n":"Acido solforico","s":"https://www.sigmaaldrich.com/US/en/sds/aldrich/339741","t":"https://www.nouryon.com/globalassets/inriver/resources/pds-sulfuric-acid-93-na-en.pdf"},
{"n":"Acido sorbico","s":"https://www.sigmaaldrich.com/US/en/sds/sigma/s1626","t":"https://avenalab.com/images/0001DOKUMENTACIJA/TDS/Sorbic_Acid_TDS_ENG.pdf"},
{"n":"Acido tartarico L(+)","s":"https://www.sigmaaldrich.com/US/en/sds/sial/251380","t":"https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-TartaricAcid.pdf"},
{"n":"Acido tereftalico (PTA)","s":"https://www.alpekpolyester.com/wp-content/uploads/2023/11/DK0001.US_.EN-2023.11.16.pdf","t":"https://alpekpolyester.com.br/wp-content/uploads/2022/05/Alpek-Polyester-PTA-Product-Specification.pdf"},
{"n":"Acido tricloroisocianurico (TCCA)","s":"https://redox.com/wp-content/sds/2217.pdf","t":""},
{"n":"Acrilonitrile","s":"https://www.sigmaaldrich.com/US/en/sds/aldrich/110213","t":"https://www.ineos.com/globalassets/ineos-group/businesses/ineos-nitriles/she/acrylonitrile_brochure.pdf"},
{"n":"Agar","s":"https://www.sigmaaldrich.com/US/en/sds/sigma/a1296","t":"https://ginobiotech.com/wp-content/uploads/2020/05/Agar-Agar-Technical-Data-Sheet.pdf"},
{"n":"AKD (alchil chetene dimero)","s":"https://www.biosynth.com/Files/MSDS/FA/31/MSDS_FA31709_5000_EN.pdf","t":"https://www.stobec.com/DATA/PRODUIT/2648~v~data.pdf"},
{"n":"Alchil poliglucoside (APG)","s":"https://chemistryconnection.com/sds/data/pdf/Lauryl_Glucoside_SDS.pdf","t":"https://dps.com.mx/productos/hoja_tecnica335.pdf"},
{"n":"Alchilbenzensolfonato lineare sodico (LAS)","s":"https://www.sigmaaldrich.com/US/en/sds/aldrich/289957","t":""},
{"n":"Alfa olefin solfonato sodico (AOS)","s":"https://redox.com/wp-content/sds/3627.pdf","t":"https://colonialchem.com/wp-content/uploads/2020/10/Colonial-AOS-40-TDS.pdf"},
{"n":"Alginato di sodio","s":"https://www.sigmaaldrich.com/US/en/sds/aldrich/w201502","t":"https://gumstabilizer.com/wp-content/uploads/2022/03/Sodium-Alginate-Technical-Data-Sheet.pdf"},
{"n":"Allantoina","s":"https://www.spectrumchemical.com/media/sds/A2721_AGHS.pdf","t":"https://yeserchem.com/wp-content/uploads/2023/02/TDS-Yeser%C2%AE-Allantoin.pdf"},
{"n":"Alluminio primario (lingotti)","s":"https://www.carlroth.com/medias/SDB-5280-IE-EN.pdf","t":"https://mechem.com/wp-content/uploads/2021/06/Mechem-S.A.-Primary-Aluminium.pdf"},
{"n":"Amido di mais","s":"https://www.sigmaaldrich.com/US/en/sds/SIAL/S5296","t":""},
{"n":"Amido di patata","s":"https://www.sigmaaldrich.com/US/en/sds/sial/s2004","t":"https://www.ingredion.com/content/dam/ingredion/technical-documents/na/Product%20Information%20File%20-%20Potato%20Starch.pdf"},
{"n":"Amido per carta","s":"https://www.sigmaaldrich.com/US/en/sds/SIAL/S5296","t":""},
{"n":"Ammoniaca","s":"https://produkte.linde-gas.at/sdb_konform/NH3_10021772EN.pdf","t":"https://static.prd.echannel.linde.com/wcsstore/FR_RES_Industrial_Gas_Store/Assets/produits-et-approvisionnement/linde-datasheet-01-ammonia-June-2017_tcm201-417364.pdf"},
{"n":"Anidride acetica","s":"https://www.sigmaaldrich.com/US/en/sds/sial/242845","t":"https://www.ineos.com/globalassets/ineos-group/businesses/ineos-acetyls/acetyls-america-documents/acetyls-acetic-anhydride-technical-data-sheet.pdf"},
{"n":"Anidride carbonica","s":"https://produkte.linde-gas.at/sdb_konform/CO2_10021714EN.pdf","t":"https://static.prd.echannel.linde.com/wcsstore/EE_REN_Industrial_Gas_Store/pdf/Downloadable%20files/Linde_Carbon_Dioxide_product_datasheet_EN_tcm607-579332.pdf"},
{"n":"Anidride carbonica (CO2)","s":"https://produkte.linde-gas.at/sdb_konform/CO2_10021714EN.pdf","t":"https://static.prd.echannel.linde.com/wcsstore/EE_REN_Industrial_Gas_Store/pdf/Downloadable%20files/Linde_Carbon_Dioxide_product_datasheet_EN_tcm607-579332.pdf"},
{"n":"Anidride solforosa","s":"https://produkte.linde-gas.at/sdb_konform/SO2_10021800EN.pdf","t":"https://static.prd.echannel.linde.com/wcsstore/DK_REN_Industrial_Gas_Store/pdf/Linde_Sulphur_Dioxide_product_datasheet_EN_tcm575-579352.pdf"},
{"n":"Anidride solforosa liquida","s":"https://produkte.linde-gas.at/sdb_konform/SO2_10021800EN.pdf","t":"https://static.prd.echannel.linde.com/wcsstore/DK_REN_Industrial_Gas_Store/pdf/Linde_Sulphur_Dioxide_product_datasheet_EN_tcm575-579352.pdf"},
{"n":"Antiossidante (tipo Irganox 1010)","s":"https://download.basf.com/p1/000000000030483816_SDS_GEN_US/en_US/Irganox_1010_ED_30483816_SDS_GEN_US_en_5-0.pdf","t":"https://dispersions-resins-products.basf.us/files/technical-datasheets/Irganox_1010_April_2015_R2_IC.pdf"},
{"n":"Argon","s":"https://produkte.linde-gas.at/sdb_konform/AR_10021700EN.pdf","t":"https://static.prd.echannel.linde.com/wcsstore/EE_REN_Industrial_Gas_Store/pdf/Downloadable%20files/Linde_Argon_product_datasheet_EN_tcm607-579331.pdf"},
{"n":"Aspartame","s":"https://www.sigmaaldrich.com/US/en/sds/aldrich/w700655","t":"https://www.sigmaaldrich.com/US/en/product/aldrich/w700655"},
{"n":"Avobenzone","s":"https://redox.com/wp-content/sds/2650.pdf","t":""},
{"n":"Azoto","s":"https://produkte.linde-gas.at/sdb_konform/N2_10021697EN.pdf","t":"https://static.prd.echannel.linde.com/wcsstore/EE_REN_Industrial_Gas_Store/pdf/Linde_Nitrogen_product_datasheet_EN.pdf"},
{"n":"Azoto (N2)","s":"https://produkte.linde-gas.at/sdb_konform/N2_10021697EN.pdf","t":"https://static.prd.echannel.linde.com/wcsstore/EE_REN_Industrial_Gas_Store/pdf/Linde_Nitrogen_product_datasheet_EN.pdf"},
{"n":"Bentonite","s":"https://www.sigmaaldrich.com/US/en/sds/sigald/285234","t":""},
{"n":"Benzoato di sodio","s":"https://www.sigmaaldrich.com/US/en/sds/sigma/71295","t":""},
{"n":"Benzyl alcohol","s":"https://www.sigmaaldrich.com/US/en/sds/ALDRICH/W213705","t":""},
{"n":"Beta-carotene","s":"https://www.sigmaaldrich.com/US/en/sds/sigma/c9750","t":"https://download.basf.com/p1/EN_StaticDocuments_25294/en/Technical_Information"},
{"n":"BHA","s":"https://www.sigmaaldrich.com/US/en/sds/aldrich/b1253","t":""},
{"n":"BHT","s":"https://www.sigmaaldrich.com/US/en/sds/aldrich/w218405","t":""},
{"n":"Bicarbonato di potassio","s":"https://www.sigmaaldrich.com/US/en/sds/SIAL/P9144","t":"https://www.armandproducts.com/wp-content/uploads/2023/04/Potassium_Bicarbonate_Handbook_8-6-2021.pdf"},
{"n":"Bicarbonato di sodio","s":"https://www.sigmaaldrich.com/US/en/sds/sigald/s8875","t":"https://naturalsoda.com/wp-content/uploads/2018/08/AMM-NS-TFF-TDS.pdf"},
{"n":"Biossido di cloro","s":"https://www.ercoworldwide.com/wp-content/uploads/2024/06/ENG-US-Erco-Chlorine-Dioxide-Solution-1.pdf","t":""},
{"n":"Biossido di titanio (carta)","s":"https://www.kronosww.com/wp-content/uploads/2026/01/sd1876_-_KRONOS_Titanium_dioxide_v13_00_US.pdf","t":"https://www.kronosww.com/products/datasheets-and-literature/"},
{"n":"Biossido di titanio (rutilo)","s":"https://media.knowde.com/image/upload/v1734419990/Ti-PureTMR-902PSDS_USA_English_AlyseKetcham.pdf20241217-1-t7zpum.pdf","t":"https://www.tipure.com/en/-/media/files/tipure/legacy/ti-pure-r-902-tds.pdf"},
{"n":"Bisabololo","s":"https://oxychemicals.com.vn/wp-content/uploads/2019/10/Bisabolol-rac_MSDS.pdf","t":"https://promo.basf.com/campaign/Projetos/CaringForYou/Documentos/Geral/Bisabolol%20RAC.pdf"},
{"n":"Bisfenolo A (BPA)","s":"https://www.sigmaaldrich.com/US/en/sds/aldrich/239658","t":""},
{"n":"Bisolfito di sodio","s":"https://download.basf.com/p1/000000000030042368_SDS_GEN_US/en/Sodium_Bisulfite_Solution_38-40_non_food_grade_Safety_Data_Sheet_English.pdf","t":""},
{"n":"Bitartrato di potassio","s":"https://atpgroup.com/wp-content/uploads/2024/04/Cream-of-Tartar-SDS-V02.-April-1-2024.pdf","t":""},
{"n":"Bitume adesivo","s":"https://epcprodstorage.blob.core.windows.net/epcblobstorage/GSAP_msds_02370120.PDF","t":"https://www.epc.shell.com/DocumentManagement/BlobDocumentDownload?DocId=162252095"},
{"n":"Blu oltremare","s":"https://www.fastenal.com/productimages/supplemental/product_docs/NUBIOLA,%20INC_14657.pdf","t":""},
{"n":"Borace (sodio tetraborato)","s":"https://www.sigmaaldrich.com/US/en/sds/sigald/s9640","t":"https://www.borax.com/BoraxCorp/media/Borax-Main/Resources/Data-Sheets/borax-decahydrate.pdf"},
{"n":"Burro di cacao","s":"https://www.cargill.com/doc/1432223225565/beauty-sustainable-cocoa-sds.pdf","t":"https://www.cargill.com/doc/1432220521357/beauty-sustainable-cocoa-butter-product-data-sheet.pdf"},
{"n":"Burro di karite","s":"https://www.nhrorganicoils.com/uploads/20221202163551e_Shea_Butter_SDS.pdf","t":"https://www.ellementalpro.com/download/M-1702_TDS_S.pdf"},
{"n":"Butano","s":"https://www.sigmaaldrich.com/US/en/sds/ALDRICH/494402","t":"https://us.nipponsanso.com/pdfs/puregas/n-Butane-Pure-Gas.pdf"},
{"n":"Calcare agricolo (carbonato di calcio)","s":"https://www.sigmaaldrich.com/US/en/sds/sial/21069","t":"https://www.carmelo.com/wp-content/uploads/2021/05/21-Carbonato-de-Calcio.pdf"},
{"n":"Calce idrata","s":"https://www.lhoist.com/sites/lhoist/files/lna_sds_hydrated_lime_2018.pdf","t":"https://wilsonsalt.com/wp-content/uploads/2021/05/TDS123_Lhoist_Hydrated_Lime_Jan_18_9d774f57-4353-4cfa-b97c-ea29a923431e.pdf"},
{"n":"Calce viva","s":"https://www.carmeuse.com/sites/default/files/2024-04/carmeuse_americas_high_calcium_quicklime_ca-en_v2_0.pdf","t":"https://www.mlc.com/wp-content/uploads/2019/02/Pulverized-Quicklime.pdf"},
{"n":"Caolino","s":"https://www.sigmaaldrich.com/US/en/sds/sial/k7375","t":""},
{"n":"Caolino (patinatura)","s":"https://www.sigmaaldrich.com/US/en/sds/sial/k7375","t":"https://polymeradd.co.th/wp-content/uploads/2025/06/KAOLIN-CLAY-TDS.pdf"},
{"n":"Caprolattame","s":"https://download.basf.com/p1/000000000030043506_SDS_GEN_US/en_US/Caprolactam_liquid_30043506_SDS_GEN_US_en_5-0.pdf","t":"https://techcenter.lanxess.com/scp/emea/en/docguard/LANXESS_Caprolactam_datasheet.pdf?docId=25172442"},
{"n":"Caprylic/capric triglyceride","s":"https://www.spectrumchemical.com/MSDS/C3465_AGHS.pdf","t":"https://www.avenalab.com/images/0001DOKUMENTACIJA/TDS/CaprylicCapric_Trigliceride_TDS_ENG.pdf"},
{"n":"Caprylyl glycol","s":"https://www.sigmaaldrich.com/US/en/sds/aldrich/213705","t":"https://avenalab.com/images/001SDS/TDS/Caprylyl-Glycol-TDS.pdf"},
{"n":"Caramello semplice","s":"https://www.sethness-roquette.com/pdf/SRUS/Product%20Safety%20Data%20Sheet/English%20version/SR%20USA%20-%20Safety%20Data%20Sheet%20-%20Caramel%20Color%20(Powders).pdf","t":"https://www.sethness-roquette.com/pdf/SRUS/Product%20Specification%20and%20Technical%20Data/English%20version/SRUS%20P212%20-%20Product%20Specifications%20&%20Technical%20Data.pdf"},
{"n":"Carbomer","s":"https://www.fishersci.com/store/msds?partNumber=AC278382500&productDescription=CARBOPOL+940+250G&vendorId=VN00032119&countryCode=US&language=en","t":"https://www.lubrizol.com/-/media/Lubrizol/Health/Literature/SPEC_Carbopol_940_NF.pdf"},
{"n":"Carbonato di calcio","s":"https://www.sigmaaldrich.com/US/en/sds/sial/c4830","t":"https://www.sigmaaldrich.com/US/en/product/sigma/c6033"},
{"n":"Carbonato di calcio (calcite)","s":"https://www.sigmaaldrich.com/US/en/sds/sial/c4830","t":"https://www.lookpolymers.com/pdf/Omya-OMYACARB-5-FL-Calcium-Carbonate.pdf"},
{"n":"Carbonato di calcio (filler carta)","s":"https://www.sigmaaldrich.com/US/en/sds/sial/c4830","t":"https://www.lookpolymers.com/pdf/Omya-HYDROCARB-90-Calcium-Carbonate.pdf"},
{"n":"Carbonato di sodio","s":"https://www.sigmaaldrich.com/US/en/sds/sial/s7795","t":"https://www.tatachemicals.com/upload/pdf/Dense_Ash_TCNA.pdf"},
{"n":"Carbone attivo granulare (GAC)","s":"https://norit.com/hubfs/S-GAC-Europe-EN.pdf","t":"https://www.urbansaqua.com/wp-content/uploads/2023/01/www.urbansaqua.com-activated-carbon-specifications-norit-gac-1240-plus-1240plus-water-english.pdf"},
{"n":"Carbone enologico","s":"https://www.perdomini-ioc.com/wp-content/uploads/2021/04/SS_CARBO_F.pdf","t":"https://www.perdomini-ioc.com/wp-content/uploads/2021/04/PERDOMINI-scheda-tecnica-Carbo-F-rev03-2021.pdf"},
{"n":"Carbone vegetale","s":"https://www.zetalab.it/schede/x211242.pdf","t":"https://megadolciaria.it/wp-content/uploads/2020/07/COL035.pdf"},
{"n":"Carbossimetilcellulosa (CMC)","s":"https://www.sigmaaldrich.com/US/en/sds/aldrich/419273","t":"https://www.chempoint.com/products/download?grade=66781&doctype=tds&documentid=01030001139010936249411&language=English"},
{"n":"Carbossimetilcellulosa sodica (CMC)","s":"https://www.carlroth.com/medias/SDB-336E-GB-EN.pdf","t":""},
{"n":"Carminio (acido carminico)","s":"https://www.sigmaaldrich.com/sds/sial/229253","t":""},
{"n":"Carragenina","s":"https://www.sigmaaldrich.com/US/en/sds/SIAL/73117","t":"https://ginobiotech.com/wp-content/uploads/2020/05/Carrageenan-Technical-Data-Sheet.pdf"},
{"n":"Caseina (adesivo)","s":"https://www.fishersci.com/store/msds?partNumber=AAA1370736&productDescription=CASEIN+TECHNICAL+GRADE+500G&vendorId=VN00024248&countryCode=US&language=en","t":""},
{"n":"Caseinato di sodio","s":"https://www.sigmaaldrich.com/US/en/sds/Sigma/C8654","t":"https://www.ornua.com/wp-content/uploads/2018/07/Sodium-Caseinate.pdf"},
{"n":"Cellulosa kraft (pasta)","s":"https://www.internationalpaper.com/docs/default-source/english/sustainability/product-safety-data-sheets/kraft-pulp-bleached.pdf","t":"https://www.upmpulp.com/siteassets/documents/upm-euca-fray-bentos-2017.pdf"},
{"n":"Cellulosa microcristallina (MCC)","s":"https://www.stobec.com/DATA/PRODUIT/2792~v~sds.pdf","t":"https://www.stobec.com/DATA/PRODUIT/2906~v~data.pdf"},
{"n":"Cetearyl alcohol","s":"https://www.carlroth.com/medias/SDB-2HAE-DE-EN.pdf","t":"https://www.avenalab.com/images/0001DOKUMENTACIJA/TDS/Cetearyl_Alcohol_TDS_ENG.pdf"},
{"n":"Cetrimonio cloruro (CTAC)","s":"https://www.sigmaaldrich.com/US/en/sds/aldrich/292737","t":"https://www.avenalab.com/images/0001DOKUMENTACIJA/TDS/Cetrimonium_Chloride_TDS_ENG.pdf"},
{"n":"Cetyl alcohol","s":"https://www.sigmaaldrich.com/US/en/sds/sial/68824","t":"https://www.vvfltd.com/PDF/fattyalcohol/Vegarol1698PDS.pdf"},
{"n":"Chinacridone violetto","s":"https://www.kremer-pigmente.com/elements/resources/products/files/23710_SDS.pdf","t":"https://www.pigments.com/wp-content/uploads/1419_QUINACRIDONE_VIOLET_PV19_PFS.pdf"},
{"n":"Chitosano di origine fungina","s":"https://www.sigmaaldrich.com/US/en/sds/aldrich/417963","t":"https://www.sigmaaldrich.com/US/en/specification-sheet/sigma/42344"},
{"n":"Cianoacrilato (presa rapida)","s":"https://www.sigmaaldrich.com/US/en/sds/aldrich/e1505","t":"https://datasheets.tdx.henkel.com/LOCTITE-454-en_GL.pdf"},
{"n":"Ciclopentasilossano","s":"http://www.ezychem.com/download/MSDS/PMX%200245%20GHS%20MSDS.pdf","t":"https://www.dow.com/documents/95/95-0/95-513-xiameter-pmx-0245-cyclopentasi.pdf"},
{"n":"Cloramina T","s":"https://0201.nccdn.net/1_2/000/000/17f/726/410301_gb_halamid.pdf","t":"http://www.ihanskorea.com/html/_skin/2/brochure/Halamid_TDS.pdf"},
{"n":"Clorexidina digluconato","s":"https://www.sigmaaldrich.com/US/en/sds/sigma/c9394","t":"https://www.sigmaaldrich.com/content/dam/sigma-aldrich/docs/Sigma/Product_Information_Sheet/c9394pis.pdf"},
{"n":"Cloro","s":"https://www.airgas.com/msds/001015.pdf","t":"https://www.airgas.com/airgascatalog/catalog/P15_Chlorine_Pure_Gases.pdf"},
{"n":"Clorofille","s":"https://www.spectrumchemical.com/MSDS/TCI-C0780.pdf","t":""},
{"n":"Cloruro di benzalconio","s":"https://www.fishersci.com/store/msds?partNumber=AC263820010&productDescription=BENZALKONIUMCHLORIDE%2C+50+1LT&vendorId=VN00032119&countryCode=US&language=en","t":""},
{"n":"Cloruro di calcio","s":"https://www.sigmaaldrich.com/US/en/sds/sigald/c1016","t":"https://www.cal-chlor.com/wp-content/uploads/173-01757-food-grade-Anhyd-prod-info-sheet.pdf"},
{"n":"Cloruro di didecildimetilammonio (DDAC)","s":"https://www.sigmaaldrich.com/US/en/sds/sial/34466","t":"https://www.zxchem.com/wp-content/uploads/2021/11/TDS-DDAC-Didecyldimethylammonium-Chloride-Cas-No-7173-51-5-zxchem-group.pdf"},
{"n":"Cloruro di magnesio","s":"https://www.sigmaaldrich.com/US/en/sds/SIGMA/M8266","t":""},
{"n":"Cloruro di potassio","s":"https://www.sigmaaldrich.com/US/en/sds/sial/p9333","t":""},
{"n":"Cloruro di potassio (MOP)","s":"https://mosaicco.com/fileLibrary/publicFiles/0-MOP_SDS.pdf","t":"https://nutrien-prod-asset.s3.us-east-2.amazonaws.com/s3fs-public/products/datasheet/FERT_STD_Sask_Mar312021.pdf"},
{"n":"Cloruro di sodio industriale","s":"https://www.compassminerals.com/iceaway/wp-content/uploads/sites/11/2026/04/sodiumchloride_safetydatasheet_global_8.6.19.pdf","t":"https://www.cargill.com/doc/1432159963640/bulk-granulated-industrial-product-sheet.pdf"},
{"n":"Cloruro di vinile (VCM)","s":"https://www.westlake.com/safety_guidelines/Geismar_Safety_Guidelines/VCM%20Vinyl%20Chloride%20Monomer.pdf","t":"https://www.westlake.com/sites/default/files/VCM%20-%20Vinyl%20Chloride%20Monomer%20-%20Calvert%20City,%20KY%20Plant.pdf"},
{"n":"Cloruro ferrico","s":"https://download.basf.com/p1/000000000030042332_SDS_GEN_US/en/Ferric_Chloride_Anhydrous_Safety_Data_Sheet_English.pdf","t":""},
{"n":"Cocamide DEA","s":"https://www.parchem.com/siteimages/attachment/ghs%20cocamide%20dea%20msds.pdf","t":"https://www.stepan.com/content/dam/stepan-dot-com/webdam/website-product-documents/product-bulletins/surfactants/NINOL40CO.pdf"},
{"n":"Cocamidopropil betaina (CAPB)","s":"https://www.acme-hardesty.com/wp-content/uploads/Cocoamidopropyl-Betaine-CAPB-SDS.pdf","t":"https://www.acme-hardesty.com/wp-content/uploads/Cocoamidopropyl-Betaine-CAPB.pdf"},
{"n":"Colla vinilica (PVA)","s":"https://www.sigmaaldrich.com/US/en/sds/aldrich/387924","t":"https://scipoly.com/wp-content/uploads/2020/09/347-tds.pdf"},
{"n":"Colofonia (rosin)","s":"https://www.cdhfinechemical.com/images/product/msds/37_1403636662_GUMROSIN-CASNO-8050-09-7-MSDS.pdf","t":"https://nares.pt/wp-content/uploads/2024/03/Technical-Data-Sheet-gum-rosin-july-2023.pdf"},
{"n":"Colofonia (sizing)","s":"https://www.cdhfinechemical.com/images/product/msds/37_1403636662_GUMROSIN-CASNO-8050-09-7-MSDS.pdf","t":"https://nares.pt/wp-content/uploads/2024/03/Technical-Data-Sheet-gum-rosin-july-2023.pdf"},
{"n":"Cromo metallico","s":"https://www.americanelements.com/printpdf/chromium-metal-7440-47-3/sds","t":""},
{"n":"Curcumina","s":"https://www.sigmaaldrich.com/US/en/sds/sial/08511","t":""},
{"n":"Decyl glucoside","s":"https://www.carlroth.com/medias/SDB-302Y-MT-EN.pdf","t":"https://bioalkemia.com/pdf/iSurfDG816.pdf"},
{"n":"Destrina (adesivo da amido)","s":"https://www.sigmaaldrich.com/US/en/sds/sial/31405","t":""},
{"n":"Dicloroisocianurato di sodio (NaDCC)","s":"https://www.tcichemicals.com/BE/en/sds/D1003_EU_6N.pdf","t":"https://file.medchemexpress.com/batch_PDF/HY-B2180/Dichloroisocyanurate-sodium-DataSheet-MedChemExpress.pdf"},
{"n":"Diclorometano (DCM)","s":"https://www.sigmaaldrich.com/US/en/sds/sial/270997","t":""},
{"n":"Dimeticone","s":"https://www.ppe.com/msds/MRB01.PDF","t":"https://daltosur.com/media/documents/xiameter-pmx-200-silicone-fluid-50-1000-csttds052020_2.PDF"},
{"n":"Dimetilformammide (DMF)","s":"https://www.sigmaaldrich.com/US/en/sds/sial/227056","t":"http://www.kianresin.com/userfiles/files/eastman_Dimethylformamide%20(DMF).pdf"},
{"n":"Dimetilsolfossido (DMSO)","s":"https://www.sigmaaldrich.com/US/en/sds/SIGMA/D2650","t":"https://www.gaylordchemical.com/content/uploads/2020/08/SP-QA-006-DMSO-Industrial-Grade-Specification-1.pdf"},
{"n":"Distearildimonio cloruro","s":"https://www.fishersci.com/store/msds?partNumber=AAB2378818&productDescription=DIMETHLDI-N-OCTDECLAM+CLRI+50G&vendorId=VN00024248&countryCode=US&language=en","t":"https://www.essentialingredients.com/pdf/GenaminDSAPProductFactSheet.pdf"},
{"n":"Dolomite","s":"https://www.heidelbergmaterials.us/docs/default-source/safety-data-sheets/sds-dolomite.pdf","t":"https://www.mbfgfiles.co.uk/datasheets/microdol_1_Data%20Sheet.pdf"},
{"n":"EDTA tetrasodico","s":"https://northmetal.net/wp-content/uploads/Ethylenediaminetetraacetic-Acid-Tetrasodium-Salt-of-EDTA-Solution-EDTA-EDTA-39-Solution-Versene-100-NaO-CO-CH22-N-CH2-N-CH2-CO-NaO2-64-02-8-SDS.pdf","t":"https://northmetal.net/wp-content/uploads/Ethylenediaminetetraacetic-Acid-Tetrasodium-Salt-of-EDTA-Solution-EDTA-EDTA-39-Solution-Versene-100-NaO-CO-CH22-N-CH2-N-CH2-CO-NaO2-64-02-8-TDS-2.pdf"},
{"n":"Elio","s":"https://static.prd.echannel.linde.com/wcsstore/CA_LINDE_Store/datasheets/E-4602-Helium-SDS%20CA-EN-1.0.pdf","t":"https://static.prd.echannel.linde.com/wcsstore/DK_REN_Industrial_Gas_Store/pdf/Linde_Helium_product_datasheet_EN_tcm575-579338.pdf"},
{"n":"Esafluoruro di zolfo","s":"https://static.prd.echannel.linde.com/wcsstore/CA_LINDE_Store/datasheets/E-4657-Sulfur%20hexafluoride-SDS%20CA-EN-1.0.pdf","t":"https://static.prd.echannel.linde.com/wcsstore/DK_REN_Industrial_Gas_Store/pdf/Linde_Sulphur_Hexaflouride_product_datasheet_EN_tcm575-579351.pdf"},
{"n":"Esametafosfato di sodio (SHMP)","s":"https://www.hillbrothers.com/pdf/downloads/msds/sds/n/sodium-hexametaphosphate-sds.pdf","t":"https://www.cig-global.com/wp-content/uploads/2019/09/Sodium-Hexametaphosphate-TDS.pdf"},
{"n":"Essiccante al cobalto (cobalto octoato)","s":"https://www.pfaltzandbauer.com/Files/SDSFile?fileName=C23740++SDS++062123.pdf","t":"https://www.borchers.com/wp-content/uploads/2019/05/Octa-Soligen-Cobalt-6.pdf"},
{"n":"Etanolo industriale/denaturato","s":"https://www.sigmaaldrich.com/US/en/sds/sial/792780","t":"https://greenfield.com/wp-content/uploads/2018/11/Ethyl-Alcohol-96-966pc.pdf"},
{"n":"Ethylhexyl methoxycinnamate (octinoxate)","s":"https://cdn.caymanchem.com/cdn/msds/33401m.pdf","t":"https://promo.basf.com/campaign/Projetos/CaringForYou/Documentos/Protecci%C3%B3n%20Solar/Uvinul%C2%AE%20MC%2080.pdf"},
{"n":"Ethylhexylglycerin","s":"https://www.chempoint.com/products/download?grade=78127&doctype=sds","t":"https://www.chempoint.com/products/download?grade=78127&doctype=tds"},
{"n":"Etilcellulosa","s":"https://www.chempoint.com/products/download?grade=43078&type=msds","t":"https://www.chempoint.com/products/download?grade=43078&doctype=tds"},
{"n":"Etilene","s":"https://download.basf.com/p1/000000000030052901_SDS_GEN_US/en_US/ETHYLENE_30052901_SDS_GEN_US_en_3-1.pdf","t":"https://static.prd.echannel.linde.com/wcsstore/DK_REN_Industrial_Gas_Store/pdf/Linde_Ethene_product_datasheet_EN_tcm575-579337.pdf"},
{"n":"EVA (etilene-vinilacetato)","s":"https://b2b-safety-data-sheets.s3.us-east-2.amazonaws.com/Dow+Chemical/Elvax/DC_Elvax+3165_EN.PDF","t":"https://www.dow.com/content/dam/dcc/documents/en-us/productdatasheet/914/914-17601-01-elvax-3165-ethylene-vinyl-acetate-copolymer-tds.pdf"},
{"n":"Fenolo","s":"https://www.ineos.com/show-document/?grade=Phenol+synthetic+-+99.99%25&bu=INEOS+Phenol&documentType=SDS&docLanguage=US-EN&version=a43ab9dd1a012b85da756d2e9978a29e","t":"https://www.sigmaaldrich.com/deepweb/assets/sigmaaldrich/product/documents/405/033/p5566pis.pdf"},
{"n":"Filo di rame","s":"https://www.americanelements.com/print/view/pdf/products_sds/block_1?view_args[]=37162","t":"https://www.americanelements.com/print/view/pdf/product_datasheet/block_1?view_args[]=37162"},
{"n":"Formaldeide (formalina)","s":"https://www.sigmaaldrich.com/US/en/sds/sigma/f8775","t":"https://www.scharlabchina.com/documents/TDS/FO0010_TDS_EN.pdf"},
{"n":"Fosfato biammonico (DAP)","s":"https://www.cropnutrition.com/wp-content/uploads/2023/03/DAP_SDS.pdf","t":"https://www.cropnutrition.com/wp-content/uploads/2023/03/Diammonium_Phosphate_Technical_Data_Sheet.pdf"},
{"n":"Fosfato di zinco (anticorrosivo)","s":"https://www.sigmaaldrich.com/US/en/sds/aldrich/587583","t":"https://admin.heubach.com/wp-content/uploads/2022/08/Tds-ac_zp10-01_02-EU.pdf"},
{"n":"Fosfato monoammonico (MAP)","s":"https://www.innophos.com/-/media/innophos-com/customer-center-files/phosphates/public/unique/001/map-gran-sds.pdf","t":"https://www.valudor.com/wp-content/uploads/2022/04/Monoammonium-Phosphate-TDS.pdf"},
{"n":"Fruttosio","s":"https://www.sigmaaldrich.com/US/en/sds/sigma/f0127","t":"https://www.sigmaaldrich.com/US/en/product/sigma/f0127"},
{"n":"Ftalocianina blu","s":"https://www.fishersci.com/store/msds?partNumber=AC269150250&productDescription=COPPER+PHTHALOCYANINE+D+25GR&vendorId=VN00032119&countryCode=US&language=en","t":""},
{"n":"Ftalocianina verde","s":"https://shop.kremerpigments.com/elements/resources/products/files/23000_SDS.pdf","t":"https://vipulorganics.com/pdf/Suntone%20Green%20TDS/Suntone%20Pigment%20Green%207%20TDS.pdf"},
{"n":"Gelatina alimentare","s":"https://atpgroup.com/wp-content/uploads/2018/06/Gelatin-Rousselot-SDS.pdf","t":""},
{"n":"Gelatina enologica","s":"https://atpgroup.com/wp-content/uploads/2018/06/Gelatin-Rousselot-SDS.pdf","t":"https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/IT/TDS-IT-GreenGelatina.pdf"},
{"n":"Gesso agricolo (solfato di calcio)","s":"https://www.riccachemical.com/WebsiteDocuments/SDS/R1823000.pdf","t":"https://www.usg.com/content/dam/USG_Marketing_Communications/united_states/product_promotional_materials/finished_assets/usg-calcium-sulfate-feed-grade-tech-specs-en-IG1926.pdf"},
{"n":"Ghiaccio secco (CO2 solida)","s":"https://static.prd.echannel.linde.com/wcsstore/MY_RSE_Industrial_Ntl_Store/HCL%20-%20Images/MSDS/Dry%20Ice/Carbon%20dioxide,%20solid%20(Dry%20ice)_EN.pdf","t":""},
{"n":"Giallo di cadmio (solfuro di cadmio)","s":"https://www.kremer-pigmente.com/en/shop/pigments/21040-cadmium-yellow-no-6-medium.html","t":""},
{"n":"Giallo di cromo (cromato di piombo)","s":"https://www.kremer-pigmente.com/elements/resources/products/files/SA-Chromgelb_SHD_ENG.pdf","t":""},
{"n":"Giallo diarilide","s":"https://www.cncolorchem.com/upLoad/file/20170411/14919014378010344.pdf","t":"https://vipulorganics.com/pdf/Suntone%20Yellow%20TDS/Suntone%20Pigment%20Yellow%2012%20TDS.pdf"},
{"n":"Glicerina","s":"https://www.sigmaaldrich.com/US/en/sds/sial/g9012","t":"https://www.sigmaaldrich.com/US/en/product/sial/g9012"},
{"n":"Glicerina (glicerolo)","s":"https://www.sigmaaldrich.com/US/en/sds/sial/g9012","t":"https://www.sigmaaldrich.com/US/en/product/sial/g9012"},
{"n":"Glicole dietilenico (DEG)","s":"https://download.basf.com/p1/000000000030089540_SDS_GEN_US/en_US/Diethylene_glycol_MFG_30089540_SDS_GEN_US_en_3-0.pdf","t":"https://www.sigmaaldrich.com/US/en/product/sial/32160"},
{"n":"Glicole etilenico (MEG)","s":"https://www.meglobal.biz/wp-content/uploads/2020/07/MEG_SDS-Americas.pdf","t":"https://www.meglobal.biz/wp-content/uploads/2019/01/Monoethylene-Glycol-MEG-Technical-Product-Brochure-PDF.pdf"},
{"n":"Glicole propilenico (MPG)","s":"https://www.sigmaaldrich.com/US/en/sds/sial/p4347","t":"https://www.dow.com/content/dam/dcc/documents/en-us/productdatasheet/812/812-00307-01-dow-propylene-glycol-industrial-grade-tds.pdf"},
{"n":"Glicole propilenico metiletere (PGME)","s":"https://www.sigmaaldrich.com/US/en/sds/sial/484407","t":"https://www.dow.com/en-us/pdp.dowanol-pm-glycol-ether.22473z.html"},
{"n":"Glifosate tecnico","s":"https://sumichem.co.in/video/pdf/MSDS%20Glyphosate%20Technical.pdf","t":"https://www.fao.org/fileadmin/templates/agphome/documents/Pests_Pesticides/Specs/Glypho_2014.pdf"},
{"n":"Glucosio (destrosio)","s":"https://www.sigmaaldrich.com/US/en/sds/sigma/g8270","t":""},
{"n":"Glutammato monosodico (MSG)","s":"https://www.sigmaaldrich.com/US/en/product/aldrich/w275601","t":"https://ingreland.com/wp-content/uploads/2024/08/TDS_Monosodium-Glutamate-80-mesh.pdf"},
{"n":"Glutaraldeide","s":"https://www.chempoint.com/products/download?grade=2977&doctype=sds","t":"https://www.chempoint.com/products/download?grade=2977&doctype=tds"},
{"n":"Glutine di frumento","s":"https://www.chemicalbook.com/msds/gluten.pdf","t":"https://manildrausa.com/wp-content/uploads/2025/04/Product-Data-Sheet-Gem-of-the-West-Vital-Wheat-Gluten.pdf"},
{"n":"Glyceryl stearate","s":"https://www.fishersci.com/store/msds?partNumber=AA43883&productDescription=keyword&vendorId=VN00024248&countryCode=US&language=en","t":"https://rierdenchemical.com/uploads/files/SDS-TDS-Sheet/glyceryl-monostearate-rct-specification.pdf"},
{"n":"Gomma arabica","s":"https://www.12taste.com/wp-content/uploads/2025/03/SDS-Gum-Acacia-Senegal-Spray-dried-Gum-Arabic-rev1.pdf","t":""},
{"n":"Gomma di guar","s":"https://www.ingredion.com/content/dam/ingredion/sds-documents/USENG/TIC%20PRETESTED%20Gum%20Guar%208%2022%20Powder%2038330902%20-%2038330902%20(1832993).pdf","t":"https://www.ingredion.com/content/dam/ingredion/technical-documents/na/Product%20Information%20File%20-%20Guar%20Gum.pdf"},
{"n":"Gomma xantano","s":"https://sds.chemtel.net/docs/Asbury%20Carbons%20Inc-0001931/Site%20SDS/CP%20Kelco%20U.S.%20Inc_Kelzan%20(GHS)_Unknown_06-27-2017_English.pdf","t":"https://www.stobec.com/DATA/PRODUIT/2933~v~data.pdf"},
{"n":"HDPE riciclato (rHDPE)","s":"https://polymers.totalenergies.com/sites/g/files/wompnd1726/f/site_collection_documents/Safety%20Datasheet%20Documents/sds_us_polyethylene.pdf","t":"https://polymers.totalenergies.com/sites/g/files/wompnd5016/files/site_collection_documents/Technical%20Datasheets/rHDPE_57525.pdf"},
{"n":"Idrogeno","s":"https://docs.airliquide.com.au/msdsau/al073.pdf","t":"https://static.prd.echannel.linde.com/wcsstore/DK_REN_Industrial_Gas_Store/pdf/Linde_Hydrogen_product_datasheet_EN_2021-09_tcm575-579341.pdf"},
{"n":"Idrossietilcellulosa (HEC)","s":"https://www.sigmaaldrich.com/US/en/sds/ALDRICH/434965","t":"https://www.dkshdiscover.com/medias/TDS-Natrosol-250-HHR-Ashland.pdf"},
{"n":"Inulina","s":"https://www.sigmaaldrich.com/US/en/sds/SIGMA/I3754","t":"https://www.ingredion.com/content/dam/ingredion/technical-documents/na/Product%20Information%20File%20-%20Inulin.pdf"},
{"n":"Iodopovidone (PVP-iodio)","s":"https://www.riccachemical.com/WebsiteDocuments/SDS/R3955000.pdf","t":"https://www.amphray.com/uploads/product/specs/5_specs.pdf"},
{"n":"Ipoclorito di calcio","s":"https://www.sigmaaldrich.com/US/en/sds/sigald/211389","t":"https://aniq.org.mx/pqta/pdf/HTH%20Granular%20-%20Arch%20(Lit).pdf"},
{"n":"Ipoclorito di sodio","s":"https://download.basf.com/p1/000000000030042344_SDS_GEN_00/en_UN/Sodium_hypochlorite_solution_30042344_SDS_GEN_00_en_2-1.pdf","t":"https://prd.assets.hycommerce.schippers.cloud/public/product/2501575/brenntag-sodium-hypo-chloride-12-5-24-kg/6a94896b-ebf6-4b7b-a787-e7e981a8a94a.pdf"},
{"n":"Ipoclorito di sodio (candeggina)","s":"https://download.basf.com/p1/000000000030042344_SDS_GEN_00/en_UN/Sodium_hypochlorite_solution_30042344_SDS_GEN_00_en_2-1.pdf","t":"https://prd.assets.hycommerce.schippers.cloud/public/product/2501575/brenntag-sodium-hypo-chloride-12-5-24-kg/6a94896b-ebf6-4b7b-a787-e7e981a8a94a.pdf"},
{"n":"Isobutanolo","s":"https://download.basf.com/p1/000000000030034839_SDS_GEN_US/en_US/ISOBUTANOL_30034839_SDS_GEN_US_en_9-0.pdf","t":"https://www.dow.com/content/dam/dcc/documents/en-us/productdatasheet/327/327-00015-01-isobutanol-tds.pdf"},
{"n":"Isopropanolo (IPA)","s":"https://www.sigmaaldrich.com/US/en/sds/ALDRICH/W292907","t":"https://www.shell.com/content/dam/shell/assets/en/business-functions/product/helix/documents/ipa-s1111-na.pdf"},
{"n":"Krypton","s":"https://sg.airliquide.com/sites/al_sg/files/2020/08/06/2017321_krypton7439-90-9_r1.pdf","t":"https://www.airgas.com/airgascatalog/catalog/P33_Krypton_Pure_Gases.pdf"},
{"n":"Lattice naturale adesivo","s":"https://holdenslatex.com/content/sds/Centrifuged%20Latex%20SDS.pdf","t":"https://holdenslatex.com/content/tds/HX%20200%20TDS.pdf"},
{"n":"Lattosio","s":"https://www.sigmaaldrich.com/US/en/sds/sigma/l3625","t":""},
{"n":"Lecitina di soia","s":"https://www.fishersci.com/store/msds?partNumber=AA3648630&productDescription=LECITHIN+REFINED+250G&vendorId=VN00024248&countryCode=US&language=en","t":""},
{"n":"Lignina","s":"https://static.cymitquimica.com/products/IN/pdf/sds-DA00353H.pdf","t":""},
{"n":"Lisozima","s":"https://www.fishersci.com/content/dam/fishersci/en_US/documents/programs/education/regulatory-documents/sds/chemicals/chemicals-l/S25750.pdf","t":"https://www.sigmaaldrich.com/deepweb/assets/sigmaaldrich/product/documents/319/164/23193256rev0325-ms.pdf"},
{"n":"Litopone","s":"https://www.americanelements.com/print/view/pdf/products_sds/block_1?view_args[]=14985","t":"https://www.americanelements.com/print/view/pdf/product_datasheet/block_1?view_args[]=14985"},
{"n":"Magnesio (lingotti)","s":"https://www.americanelements.com/print/view/pdf/products_sds/block_1?view_args[]=48303","t":"https://www.americanelements.com/print/view/pdf/product_datasheet/block_1?view_args[]=48303"},
{"n":"Maltodestrina","s":"https://media.knowde.com/image/upload/v1731672952/Roquette_SDS_REC_GLUCIDEX17-MALTODEXTRIN_000000200663_EN.PDF20241115-1-9u9iyy.pdf","t":""},
{"n":"Maltosio","s":"https://www.fishersci.com/store/msds?partNumber=BP684500&productDescription=D-%28+%29-MALTOSE+500G&vendorId=VN00033897&countryCode=US&language=en","t":""},
{"n":"Manganese elettrolitico","s":"https://www.fishersci.com/store/msds?partNumber=AC317442500&productDescription=MANGANESE+POWDER+-325+M+250G&vendorId=VN00032119&countryCode=US&language=en","t":"https://www.americanelements.com/print/view/pdf/product_datasheet/block_1?view_args%5B%5D=31628"},
{"n":"Metabisolfito di potassio","s":"https://download.basf.com/p1/000000000030042359_SDS_GEN_US/en/Potassium_Metabisulfite_food_grade_(E224)_Safety_Data_Sheet_English.pdf","t":"https://www.murphyandson.co.uk/wp-content/uploads/2018/09/Potassium-Metabisulphite-TDS-2018.pdf"},
{"n":"Metabisolfito di sodio","s":"https://download.basf.com/p1/000000000030042375_SDS_GEN_US/en/Sodium_Metabisulfite_food_grade_(E223)_Safety_Data_Sheet_English.pdf","t":"https://www.essecousa.com/wp-content/uploads/2017/10/Sodium-Metabisulfite-Data-Pack-Combined-2024.pdf"},
{"n":"Metano (gas naturale)","s":"https://produkte.linde-gas.at/sdb_konform/CH4_10021692EN.pdf","t":"https://static.prd.echannel.linde.com/wcsstore/EE_REN_Industrial_Gas_Store/pdf/Downloadable%20files/Linde_Methane_product_datasheet_EN_tcm607-579343.pdf"},
{"n":"Metanolo","s":"https://www.methanex.com/wp-content/uploads/Metanol-CAS-67-56-1-SDS-EN-22NOV23.pdf","t":"https://methanol.org/wp-content/uploads/2016/06/Methanol-Technical-Data-Sheet.pdf"},
{"n":"Metilcellulosa","s":"https://www.sigmaaldrich.com/US/en/sds/sigma/m0512","t":"https://www.sigmaaldrich.com/content/dam/sigma-aldrich/docs/Sigma/Product_Information_Sheet/2/m0512pis.pdf"},
{"n":"Metiletilchetone (MEK)","s":"https://sasoltechdata.com/MSDS/MEK.pdf","t":"https://www.shell.com/business-customers/chemicals/our-products/solvents-chemical/ketones/_jcr_content/root/main/section_531678815/text.multi.stream/1647484075971/0aed85ee2ffb968a89f2e7b365096209d89e8921/mek-s1213-global.pdf"},
{"n":"Metilisobutilchetone (MIBK)","s":"https://sasoltechdata.com/MSDS/MIBK.pdf","t":"https://monumentchemical.com/uploads/files/TDS/MIBK_TDS.pdf"},
{"n":"Metilmetacrilato (MMA)","s":"https://download.basf.com/p1/000000000030041969_SDS_GEN_US/en_US/METHYLMETHACR._30041969_SDS_GEN_US_en_4-0.pdf","t":"https://www.dow.com/documents/884/884-02323-01-methyl-methacrylate-mma.pdf"},
{"n":"Mica","s":"https://micronized.com/wp-content/uploads/2020/04/MSDS-Mica.pdf","t":"https://www.onwardchem.com/pdf_f/FT-TDS%20MICRONIZED%20MICA%20325%20Mesh.pdf"},
{"n":"Molibdato di sodio","s":"https://www.sigmaaldrich.com/US/en/sds/sigald/243655","t":"https://northmetal.net/wp-content/uploads/Sodium-Molybdate-Anhydrous-Disodium-Molybdate-Dihydrate-Molybdic-Acid-Disodium-Salt-SMA-Na2MoO4-7631-95-0-TDS-5.pdf"},
{"n":"Mono e digliceridi degli acidi grassi","s":"","t":"https://shop.reire.com/_techsheet/docs/18003190_MONO-_E_DIGLICERIDI_DEGLI_ACIDI_GRASSI_E471.pdf"},
{"n":"Monossido di carbonio","s":"https://sg.airliquide.com/sites/al_sg/files/2025-06/carbon-monoxide-630-08-0-r1.pdf","t":"https://www.airgas.com/airgascatalog/catalog/P14_Carbon_Monoxide_Pure_Gases.pdf"},
{"n":"n-Butanolo","s":"https://www.sigmaaldrich.com/US/en/sds/sial/281549","t":"https://sasoltechdata.com/tds/BUTANOL.pdf"},
{"n":"n-Eptano","s":"https://www.sigmaaldrich.com/US/en/sds/sigald/h2198","t":"https://www.shell.com/content/dam/shell/assets/en/business-functions/product/chemical/documents/heptane-q1352.pdf"},
{"n":"n-Esano","s":"https://www.sigmaaldrich.com/US/en/sds/sial/296090","t":""},
{"n":"N-Metilpirrolidone (NMP)","s":"https://www.sigmaaldrich.com/US/en/sds/sial/328634","t":"https://www-prod.lyondellbasell.com/492c3f/globalassets/documents/chemicals-technical-literature/lyondellbasell-chemicals-technicalliterature-nmp-technical-datasheet-2313.pdf"},
{"n":"Natamicina","s":"https://cdn.caymanchem.com/cdn/msds/11634m.pdf","t":"https://www.iff.com/wp-content/uploads/2025/08/NATAMAX-Food-Antifungal.pdf"},
{"n":"Neon","s":"https://www.airgas.com/msds/001038.pdf","t":"https://www.airgas.com/airgascatalog/catalog/P36_Neon_Nitric_Oxide_Pure_Gases.pdf"},
{"n":"Nerofumo (carbon black)","s":"https://sds.chemtel.net/docs/Asbury%20Carbons%20Inc-0001931/Site%20SDS/Orion%20Engineered%20Carbons%20LLC_Carbon%20Black%20(GHS)_000001000049_11-29-2017_English.pdf","t":"https://orionshowlit.com/wp-content/uploads/2021/09/SCB-TD-Amer.pdf"},
{"n":"Niacinamide (vitamina B3)","s":"https://www.sigmaaldrich.com/US/en/sds/usp/1462006","t":"https://oxychemicals.com.vn/wp-content/uploads/2023/05/PDS_Niacinamide-PC.pdf"},
{"n":"Nichel (catodi)","s":"https://nornickel.com/files/en/business/products/SDS-Electrolytic-Nickel-NNH_14.06.2017_en.pdf","t":"https://nornickel.com/business/products/nickel/harjavalta/"},
{"n":"Nitrato ammonico di calcio (CAN)","s":"https://www.landor.ch/fileadmin/user_upload/Website/Downloads/Sicherheitsdatenblaetter/Duengemittel/Kalksalpeter_15_5_wasserloeslich_Yara_Tera_Calcinit_N0136_DE_GHS_6.pdf","t":"https://www.yara.us/contentassets/280676bbae1c466799e9d22b57225584/yarabela-can-27-pds/"},
{"n":"Nitrato di ammonio","s":"https://www.sigmaaldrich.com/US/en/sds/sigald/221244","t":"https://www.dynonobel.com/siteassets/product-hub/tech-info/1ammonium_nitrate_industrial.pdf"},
{"n":"Nitrato di calcio","s":"https://www.valudor.com/wp-content/uploads/2022/04/Calcium-Nitrate-Anhydrous-US-en-2021-1.pdf","t":"https://www.manuchar.com/sites/default/files/inline-files/TDS_M_Nitrates_Calcium_Manuchar%20Agro_REACH..pdf"},
{"n":"Nitrato di cellulosa","s":"https://assets.fishersci.com/TFS-Assets/CCG/EU/SDS/SDS_15259794_EN.pdf","t":"http://www.tnc.com.tw/en-global/Product/Product/Model/Coating_Raw_Materials_en/Nitrocellulose_en/e_TechnicalDataSheet_SS"},
{"n":"Nitrato di magnesio","s":"https://pim-resources.coleparmer.com/sds/13441.pdf","t":"https://www.americanelements.com/print/view/pdf/product_datasheet/block_1?view_args[]=48386"},
{"n":"Nitrato di potassio","s":"https://www.sigmaaldrich.com/US/en/sds/sigald/221295","t":"https://cms.sqmnutrition.com/wp-content/uploads/2025/01/Ficha-Tecnica-Ultrasol-K.pdf"},
{"n":"Nitrito di sodio","s":"https://www.sigmaaldrich.com/US/en/sds/aldrich/563218","t":"https://www.chemtradelogistics.com/wp-content/uploads/2020/10/PDS-Sodium_Nitrite_Solution_Technical_CHE-2022P.pdf"},
{"n":"Nitrocellulosa","s":"https://www.sigmaaldrich.com/US/en/sds/aldrich/435090","t":"https://www.ottokemi.com/specsheet/nitrocellulose-pure.aspx"},
{"n":"Nonilfenolo etossilato (NPE)","s":"https://redox.com/wp-content/sds/4067.pdf","t":"https://www.dow.com/documents/119/119-01919-01-tergitol-np9-surfactant-tds.pdf"},
{"n":"Nutriente per lieviti (fosfato biammonico)","s":"https://www.sigmaaldrich.com/US/en/sds/USP/1029986","t":"https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-AmmonioFosfatoBibasico.pdf"},
{"n":"Octenidina dicloridrato","s":"https://cdn.caymanchem.com/cdn/msds/34238m.pdf","t":""},
{"n":"Octocrylene","s":"https://www.sigmaaldrich.com/US/en/sds/sial/02343","t":"https://dps.com.mx/productos/hoja_tecnica316.pdf"},
{"n":"Olio di cocco","s":"https://www.sigmaaldrich.com/US/en/sds/aldrich/w530155","t":"https://ultrainternational.com/wp-content/uploads/2023/08/TDS-COCONUT-OIL.pdf"},
{"n":"Olio di colza","s":"https://www.spectrumchemical.com/media/sds/R2010_AGHS.pdf","t":"https://innbak.is/wp-content/uploads/2023/02/Refined-Rapeseedoil-full.pdf"},
{"n":"Olio di girasole","s":"https://spectrumchemical.com/MSDS/S1929_AGHS.pdf","t":"https://www.vigon.com/product/sunflower-oil/?doc=PACKET/502711packet.pdf&namee=SunflowerOilAllDocuments"},
{"n":"Olio di jojoba","s":"https://www.spectrumchemical.com/media/sds/J1052_AGHS.PDF","t":"https://www.ellementalpro.com/download/1059_TDSs.pdf"},
{"n":"Olio di palma","s":"https://www.spectrumchemical.com/media/sds/PA105_AGHS.pdf","t":"https://www.elburgglobal.nl/wp-content/uploads/2019/09/elburg-palm-oil-38-39-v8-2019.pdf"},
{"n":"Ortoftalaldeide (OPA)","s":"https://www.sigmaaldrich.com/US/en/sds/sial/p0657","t":"https://www.tcichemicals.com/US/en/p/P0280"},
{"n":"Ossido di cromo verde","s":"https://www.cdhfinechemical.com/images/product/msds/64_31381456_Chromium(III)OxideGreen-CASNO-1308-38-9-MSDS.pdf","t":"https://www.americanchromechemicals.com/media/Documents/ChromicOxide/CASQT4.4.12_G6099_TDS_03-2023.pdf"},
{"n":"Ossido di etilene","s":"https://produkte.linde-gas.at/sdb_konform/C2H4O_10021703EN.pdf","t":"https://www.nouryon.com/globalassets/inriver/resources/pds-ethylene-oxide-eo-en.pdf"},
{"n":"Ossido di ferro giallo","s":"https://redox.com/wp-content/sds/4524.pdf","t":"https://www.historiskmaling.no/users/historiskmali_mystore_no/images/00005673_000_BF-920-ENG.pdf"},
{"n":"Ossido di ferro nero","s":"https://www.georgeweil.com/wp-content/uploads/2019/11/pigment-black.pdf","t":"https://lanxess.com/api/products/filehandlertds?tdsId=00006815_000_BF-318-M&language=en-GB&clientId=50162"},
{"n":"Ossido di ferro rosso","s":"https://redox.com/wp-content/sds/612.pdf","t":"https://lanxess.com/api/products/filehandlertds?tdsId=00006211_000_BF-130-M&language=en-GB&clientId=50162"},
{"n":"Ossido di magnesio","s":"https://magnesiaspecialties.com/data-sheets/us/MagChem_200AD.pdf","t":"https://iclgroupv2.s3.amazonaws.com/ipsite/wp-content/uploads/sites/1009/2018/04/Product-Specification-Technical-Grade-KP.pdf"},
{"n":"Ossido di zinco","s":"https://www.sigmaaldrich.com/US/en/sds/sigald/14439","t":"https://www.zochem.com/wp-content/uploads/2018/04/Grade-104.pdf"},
{"n":"Ossigeno","s":"https://www.airgas.com/msds/001043.pdf","t":"https://static.prd.echannel.linde.com/wcsstore/DK_REN_Industrial_Gas_Store/pdf/Linde_Oxygen_product_datasheet_EN_tcm575-579349.pdf"},
{"n":"Pantenolo (provitamina B5)","s":"https://download.basf.com/p1/000000000030276997_SDS_GEN_00/en_UN/Dexpanthenol_Ph.Eur._30276997_SDS_GEN_00_en_3-0.pdf","t":"https://download.basf.com/p1/EN_StaticDocuments_6173/en/Technical_Information_Technical_Information_English.pdf"},
{"n":"PBT","s":"https://download.basf.com/p1/000000000030604480_SDS_GEN_US/en_US/ULD.B4520_UN_30604480_SDS_GEN_US_en_2-0.pdf","t":"https://download.basf.com/p1/8a8081c57fd4b609017fd62e21255407/en/ULTRADUR%3Csup%3E%C2%AE%3Csup%3E_B4520_Product_Data_Sheet_Asia_PacificEurope_English.pdf"},
{"n":"Pectina","s":"https://www.sigmaaldrich.com/US/en/sds/sial/p7536","t":"https://www.sigmaaldrich.com/US/en/product/sigma/p9135"},
{"n":"PEEK","s":"https://www.victrex.com/-/media/downloads/msds/victrex-peek-grades-unfilled/msds-victrex-peek-powder_granules-r3-en.pdf","t":"https://www.victrex.com/-/media/downloads/datasheets/victrex_tds_450g.pdf"},
{"n":"Perborato di sodio","s":"https://customercare.pptgroup.com/hubfs/706-731%20-%20Sodium%20Perborate%20Tetrahydrate.pdf","t":""},
{"n":"Percarbonato di sodio","s":"https://www.sigmaaldrich.com/US/en/sds/aldrich/371432","t":"https://www.solvay.com/sites/g/files/srpend616/files/2019-10/PCS%20Sodium%20Percarbonate%20Safety%20and%20Handling%20Information.pdf"},
{"n":"Percloroetilene","s":"https://www.sigmaaldrich.com/US/en/sds/sial/371696","t":"https://www.oxychem.com/siteassets/documents/chlorinated-organics/perchloroethylene-technical-grade.pdf"},
{"n":"Perfosfato triplo (TSP)","s":"https://americanplantfood.com/wp-content/uploads/2020/10/SDS-APF-0-46-0-Triple-Superphosphate.pdf","t":"https://evenspray.com/wp-content/uploads/2021/04/0-45-0-Tech-Sheet.pdf"},
{"n":"Permanganato di potassio","s":"https://www.sigmaaldrich.com/US/en/sds/sigald/223468","t":"https://alphachem.com.au/wp-content/uploads/2020/09/TDS-Potassium-Permanganate.pdf"},
{"n":"Perossido di idrogeno","s":"https://www.sigmaaldrich.com/US/en/sds/sigald/216763","t":"https://www.solvay.com/sites/g/files/srpend616/files/2019-10/H2O2%20Safety%20and%20Handling%20of%20Hydrogen%20Peroxide.pdf"},
{"n":"Perossimonosolfato di potassio (KMPS)","s":"https://www.sigmaaldrich.com/US/en/sds/sial/228036","t":"https://www.piscinasbenages.es/wp-content/uploads/2016/02/OXONE.pdf"},
{"n":"PET riciclato (rPET)","s":"https://www.phoenixtechnologies.net/media/998491/PHOENIX-SAFETY-DATA-SHEET-rev-8-2019.pdf","t":"https://www.indoramaventures.com/storage/downloads/product/recycled-product/Data-Sheet-RM7304.pdf"},
{"n":"Phenoxyethanol","s":"https://www.sigmaaldrich.com/US/en/sds/sial/77699","t":"https://cosmetics.specialchem.com/_/media/production/cosmetics/clariant-preservatives/tds-phenoxetol-english-~o~1~h~.pdf"},
{"n":"PHMB (poliesametilene biguanide)","s":"https://redox.com/wp-content/sds/3583.pdf","t":""},
{"n":"Piombo (lingotti)","s":"https://beta-static.fishersci.com/content/dam/fishersci/en_US/documents/programs/education/regulatory-documents/sds/gsc-lead-safety-data-sheet.pdf","t":"https://marsmetal.com/publications/MarsMetal_LeadIngot.pdf"},
{"n":"Plastificante DEHP (ftalato)","s":"https://www.sigmaaldrich.com/US/en/sds/aldrich/d201154","t":""},
{"n":"Plastificante DINP","s":"https://redox.com/wp-content/sds/2759.pdf","t":"https://www.exxonmobilchemical.com/en/products/plasticizers/dinp-plasticizers"},
{"n":"Plastificante non-ftalico (DOTP)","s":"https://media.knowde.com/image/upload/v1716271485/production/Collateral/580717/EASTMAN_168_PLASTICIZER_Safety_Data_Sheet_2022_Eastman.pdf","t":"https://www.eastman.com/content/dam/eastman/corporate/en/literature/p/pz128.pdf"},
{"n":"PMMA (acrilico)","s":"https://www.sigmaaldrich.com/US/en/sds/aldrich/182265","t":"https://www.ledil.com/wp-content/uploads/2021/08/Datasheet-Altuglas%C2%AE-V825T.pdf"},
{"n":"Poli-DADMAC","s":"https://www.sigmaaldrich.com/US/en/sds/aldrich/409014","t":"https://aniq.org.mx/pqta/pdf/FLOQUAT%20FL%204820_TDS_EN.pdf"},
{"n":"Poliacrilammide (flocculante)","s":"https://www.sigmaaldrich.com/US/en/sds/ALDRICH/738743","t":"https://www.snf.co.za/wp-content/uploads/2017/08/Flopaam.pdf"},
{"n":"Poliammide 6 (Nylon 6)","s":"https://www.sorbtech.com/msds/SDS%20Polyamide%206(080725).pdf","t":"https://www.albis.com/en/products/download/doc/en/SI/basf/UltramidB3S.pdf"},
{"n":"Poliammide 66 (PA66)","s":"https://plasticsgroup.com/wp-content/uploads/2020/07/SDS_Polifil_Nylon_66_natural_2014.pdf","t":"https://www.albis.com/en/products/download/doc/en/SI/basf/UltramidA3K.pdf"},
{"n":"Policarbonato (PC)","s":"https://www.sigmaaldrich.com/US/en/sds/aldrich/435139","t":"https://solutions.covestro.com/-/media/covestro/solution-center/brands/downloads/imported/1556888808.pdf"},
{"n":"Policloruro di alluminio (PAC)","s":"https://www.hillbrothers.com/pdf/downloads/msds/sds/n/pax-18.pdf","t":""},
{"n":"Polietilene alta densita (HDPE)","s":"https://www.sigmaaldrich.com/US/en/sds/aldrich/428019","t":"https://www.b2bpolymers.com/TDS/Braskem_HDF8000.pdf"},
{"n":"Polietilene bassa densita (LDPE)","s":"https://www.sigmaaldrich.com/US/en/sds/aldrich/428043","t":"https://doguspolimer.com/Uploads/Galeri_Pdf/BRASKEM-LDF2023S1-LDPE.pdf"},
{"n":"Polietilene tereftalato (PET)","s":"https://www.sigmaaldrich.com/US/en/sds/aldrich/429252","t":"https://www.indoramaventures.com/storage/downloads/product/pet/bottle-sheet/RAMAPET-N1-GRADE.pdf"},
{"n":"Polipropilene (PP)","s":"https://www.sigmaaldrich.com/US/en/sds/aldrich/428175","t":"https://www.b2bpolymers.com/TDS/LyondellBasell_Moplen%20HP400R.pdf"},
{"n":"Polisorbato 80 (Tween 80)","s":"https://www.sigmaaldrich.com/US/en/sds/aldrich/w291706","t":"https://www.crodapharma.com/en-gb/resources/resource-finder/resource/24456-tween-80-hp-data-sheet"},
{"n":"Polistirene (PS)","s":"https://www.sigmaaldrich.com/US/en/sds/aldrich/182427","t":"https://amsty.com/images/Technical-Data-Sheets/GPPS/STYRON-665.pdf"},
{"n":"Polistirene espandibile (EPS)","s":"https://download.basf.com/p1/000000000030230910_SDS_GEN_US/en_US/Styropor_P_226_C_30230910_SDS_GEN_US_en_2-0.pdf","t":"https://www.styropor.com/portal/api/entry/1224220/view"},
{"n":"Polivinilcloruro (PVC)","s":"https://www.sigmaaldrich.com/US/en/sds/aldrich/81387","t":"https://www.fpcusa.com/content/uploads/participants-database/622.pdf"},
{"n":"POM (acetalica)","s":"https://www.sigmaaldrich.com/US/en/sds/SIGMA/C7291","t":"https://www.phmolds.com/wp-content/uploads/2016/09/POM-DuPont-Delrin-500P-Black.pdf"},
{"n":"Potassa caustica","s":"https://www.sigmaaldrich.com/US/en/sds/sigald/484016","t":"https://www.itwreagents.com/download_file/tds/211514/en/tds_211514_en.pdf"},
{"n":"Profilati di alluminio","s":"https://www.sigmaaldrich.com/US/en/sds/aldrich/11009","t":"http://aluminum.yieh.com/Upfiles/EDUp/files/6000%20Series/TDS/AA6082/TDS-YIEH-6082-Profile.pdf"},
{"n":"Propano","s":"https://static.prd.echannel.linde.com/wcsstore/DK_REN_Industrial_Gas_Store/pdf/SDS_EN/Propane,%20pure%20substance.pdf","t":"https://static.prd.echannel.linde.com/wcsstore/DK_REN_Industrial_Gas_Store/pdf/Linde_Propane_product_datasheet_EN_tcm575-579350.pdf"},
{"n":"Propilene","s":"https://sg.airliquide.com/sites/al_sg/files/2024-10/sds-105_clp_propylene-115-07-1.pdf","t":"https://static.prd.echannel.linde.com/wcsstore/NO_REN_Industrial_Gas_Store/pdf/EN/Natural_refrigerant_R1270_CARE_45_Product_data_EN_tcm639-661326.pdf"},
{"n":"Proteasi (subtilisina)","s":"https://www.sigmaaldrich.com/US/en/sds/SIGMA/P1236","t":"https://www.megazyme.com/documents/Data_Sheets/E-BSPRT-100ML_DATA.pdf"},
{"n":"Proteine della soia (isolato)","s":"https://www.parchem.com/siteimages/attachment/ghs%20soy%20protein%20isolate%20msds.pdf","t":"https://www.adm.com/globalassets/products--services/human-nutrition/products/alternative-proteins/soy-protein/soy-protein-isolates/adm-soy-protein-isolates-product-sheet-eng-na-2025.pdf"},
{"n":"Protossido di azoto","s":"https://sg.airliquide.com/sites/al_sg/files/2025-04/2010491_nitrous-oxide-10024-97-2-r3.pdf","t":"https://static.prd.echannel.linde.com/wcsstore/REN_Industrial_Gas_Store/Linde_Nitrous_Oxide_product_datasheet_EN.11.12.2025.pdf"},
{"n":"PTFE (teflon)","s":"https://www.fishersci.com/store/msds?partNumber=AC178932500&productDescription=POLY%28TETRAFLUOROETHYLENE+250GR&vendorId=VN00032119&countryCode=US&language=en","t":"https://www.teflon.com/en/-/media/files/teflon/teflon-ptfe-resins-product-info.pdf"},
{"n":"PVPP","s":"https://www.fishersci.com/store/msds?partNumber=AC227485000&countryCode=US&language=en","t":""},
{"n":"Rame catodo","s":"https://kghm.com/sites/default/files/en_hml_msds_copper_cathodes.pdf","t":"https://kghm.com/sites/default/files/kghm_katody_en_0.pdf"},
{"n":"Refrigerante R134a","s":"https://www.climalife.co.uk/docs/Chemours-134a-MSDS-v8.PDF","t":"https://www.chemours.com/en/-/media/files/freon/freon-134a-product-information.pdf"},
{"n":"Refrigerante R32","s":"https://www.daikinchemicals.com/library/pb_common/pdf/sds/Refrigerants/sds-hfc-32-E_20191119.pdf","t":"https://www.honeywell-refrigerants.com/europe/?document=genetron-r-32-data-sheet&download=1"},
{"n":"Resina epossidica (base BPA)","s":"https://www.miller-stephenson.com/wp-content/uploads/sds/828.pdf","t":"https://www.westlakeepoxy.com/sites/default/files/downloads/gfqy40X24W.pdf"},
{"n":"Resina fenolica (PF)","s":"https://www.plenco.com/data/SDS/02567.PDF","t":"https://plenco.com/sheets/02000-General-Purpose-Phenolic-Materials-Plenco-June2018.pdf"},
{"n":"Resina melammina-formaldeide (MF)","s":"https://www.smooth-on.com/msds/files/940C_1.pdf","t":""},
{"n":"Resina urea-formaldeide (UF)","s":"https://www.safripol.com/wp-content/uploads/2018/07/WCH-SDS-01_Urea-Formaldehyde-Resin.pdf","t":""},
{"n":"Retinolo (vitamina A)","s":"https://www.fishersci.com/store/msds?partNumber=AC347072500&productDescription=ALL-TRANS-RETINOL+95%25+250MGAL&vendorId=VN00032119&countryCode=US&language=en","t":"https://www.skinident.world/fileadmin/img/spanish-pictures/pdf/BASF_Vitamin_A.pdf"},
{"n":"Riboflavina","s":"https://www.sigmaaldrich.com/US/en/sds/SIGMA/R4500","t":"https://www.asp-inc.com/products/documents/prodinfo/r/riboflavin.pdf"},
{"n":"Rosso naftolo","s":"https://www.sypigment.com/msds/Pigment-Red-170.pdf","t":"https://www.sypigment.com/tds/Pigment-Red-170.pdf"},
{"n":"Sabbia di quarzo (filtrazione)","s":"https://www.ussilica.com/sites/default/files/2019-05/Silica%20OSHA%20EU%20SDS%20(4-18).pdf","t":"https://carbo.tech/wp-content/uploads/2024/11/WATER_FILTRATION_SAND-TDS.pdf"},
{"n":"Saccarosio","s":"https://www.sigmaaldrich.com/sds/sigma/s8501","t":"https://www.sigmaaldrich.com/deepweb/assets/sigmaaldrich/product/documents/330/868/s8501pis.pdf"},
{"n":"Sale alimentare (cloruro di sodio)","s":"https://www.cdhfinechemical.com/images/product/msds/101_260540911_SodiumChloride-CASNO-7647-14-5-MSDS.pdf","t":"https://www.cargill.com/doc/1432109008609/salt-3903-hi-grade-information-sheet.pdf"},
{"n":"SAN","s":"https://en.fcfc-plastics.com/uploadfiles/216/SAN-resin/SDS_SAN_en.pdf","t":"https://s3.amazonaws.com/static.entecpolymers.com/v3/uploads/content/INEOS-Styrolution-Lustran-SAN-Product-Guide_2023-03-17-131856_xiaa.pdf"},
{"n":"Sciroppo di glucosio","s":"https://www.stobec.com/DATA/PRODUIT/2184~v~safety-sheet.PDF","t":"https://www.stobec.com/DATA/PRODUIT/2185~v~data-sheet.pdf"},
{"n":"Silicato di sodio","s":"https://www.pqcorp.com/docs/default-source/msds/pq-corporation/sodium-silicate-solids/gd/gd-sodium-silicate_msds_2015.pdf","t":"https://www.engnet.co.za/documents/pdfcatalog/PQS001_110412022009_Sodium%20Silicates%20-%20Liquids%20and%20Solids.pdf"},
{"n":"Silicato di sodio (vetro solubile)","s":"https://www.sigmaaldrich.com/US/en/sds/sigald/338443","t":"https://www.pqcorp.com/docs/default-source/recommended-literature/pq/sodium-silicate-liquids/oilfield2009.pdf"},
{"n":"Silicio metallico","s":"https://www.sigmaaldrich.com/US/en/sds/aldrich/215619","t":"https://www.ferroglobe.com/static-files/3977672b-4593-4fc7-99c0-4aa57aba613a"},
{"n":"Soda caustica","s":"https://www.sigmaaldrich.com/US/en/sds/SIGALD/795429","t":"https://media.laballey.com/specifications/Sodium-Hydroxide-Pellets-Product-Specification-Sheet.pdf"},
{"n":"Sodio alluminato","s":"https://cdn.prod.website-files.com/693728a89eadd0aa935e8b6c/69779c90eef45d7e8639f39b_SDS%20-%20Sodium%20Aluminate%2038%25%20-%20Usalco.pdf","t":"http://www.usalco.com/wp-content/uploads/2013/05/Sodium_Aluminate_38_Specification_USALCO.pdf"},
{"n":"Sodio citrato","s":"https://www.sigmaaldrich.com/US/en/sds/mm/1.11037","t":"https://www.jungbunzlauer.com/wp-content/uploads/2025/06/JBL-FL-PCAR-Product-Card-Trisodium-Citrate-2022-015.pdf"},
{"n":"Sodio cocoil isetionato (SCI)","s":"https://www.hekserij.nl/wp-content/uploads/2024/10/SDS-10110-Sodium-Cocoyl-Isethionate-SCI-2024-07.pdf","t":"https://s.cdnmpro.com/134664192/content/Tensida%20SCI%20M-1384_TDS.pdf"},
{"n":"Sodio gluconato","s":"https://www.sigmaaldrich.com/US/en/sds/sial/s2054","t":"https://www.jungbunzlauer.com/wp-content/uploads/2025/06/JBL-FL-PCAR-Product-Card-Sodium-Gluconate-2022-015.pdf"},
{"n":"Sodio laureth solfato (SLES)","s":"https://documents.basf.com/81527f0358ac61bfe9f7dc516222486abde45f26/MSDS_000000000030530360_en.pdf","t":"https://promo.basf.com/campaign/Projetos/CaringForYou/Documentos/Geral/Texapon%C2%AE%20N%2070.pdf"},
{"n":"Sodio lauril solfato (SLS)","s":"https://download.basf.com/p1/000000000030554762_SDS_GEN_US/en_US/Kolliphor_SLS_Fine_30554762_SDS_GEN_US_en_5-0.pdf","t":"https://download.basf.com/p1/EN_StaticDocuments_6494/en/Technical_Information_Technical_Information_English.pdf"},
{"n":"Sodio stearato (sapone)","s":"https://media.vwr.com/stibo/search/sds000001650_mt_en.pdf","t":""},
{"n":"Sodio tripolifosfato (STPP)","s":"https://www.innophos.com/-/media/innophos-com/customer-center-files/phosphates/public/unique/001/stpp-sds.pdf","t":""},
{"n":"Sodium hyaluronate (acido ialuronico)","s":"https://www.lifecore.com/wp-content/uploads/2023/09/SDS-Sodium-Hyaluronate.pdf","t":""},
{"n":"Sol di silice (Kieselsol)","s":"https://www.carlroth.com/medias/SDB-8025-CH-IT.pdf","t":"https://www.experti.it/wp-content/uploads/2025/01/tds-sol-di-silice.pdf"},
{"n":"Solfato di alluminio","s":"https://www.fishersci.com/store/msds?partNumber=AC192431000&countryCode=US&language=en","t":"https://www.cvear.com/wp-content/uploads/2016/07/USALCO_TDS_Dry_Aluminum_Sulfate_Purified_Grade.pdf"},
{"n":"Solfato di ammonio","s":"https://www.sigmaaldrich.com/US/en/sds/sial/901874","t":""},
{"n":"Solfato di bario (blanc fixe)","s":"https://www.elementalmicroanalysis.com/documents/product/sds/BARIUM-SULPHATE_20241113_EN.pdf","t":"https://www.tennantsdistribution.com/LinkClick.aspx?fileticket=-hSQ0pj0v5s%3D&portalid=0"},
{"n":"Solfato di magnesio","s":"https://www.spectrumchemical.com/media/sds/M1354_AGHS.pdf","t":"https://www.kpluss.com/shared/.downloads/technical-data-sheet/en-tds-solu-cms.pdf"},
{"n":"Solfato di magnesio (sale di Epsom)","s":"https://www.hillbrothers.com/pdf/downloads/msds/sds/n/magnesium-sulfate-sds.pdf","t":"https://ingredi.com/content/pdfs/Epsom_Salt_PDS.pdf"},
{"n":"Solfato di manganese","s":"https://redox.com/wp-content/sds/1187.pdf","t":"https://twinsbridge.com/wp-content/uploads/2022/05/TDS-Manganese-Sulfate-Fertilizer-Grade.pdf"},
{"n":"Solfato di potassio (SOP)","s":"https://www.sigmaaldrich.com/US/en/sds/sigald/p0772","t":"https://www.vaniperen.com/wp-content/uploads/dlm_uploads/2017/12/VII-TDS-EN-IN-Potassium-Sulphate-SOP-HG-19-6-2019-277-WM.pdf"},
{"n":"Solfato di rame","s":"https://www.sigmaaldrich.com/US/en/sds/sigma/c8027","t":"https://northmetal.net/wp-content/uploads/Copper-Sulfate-Pentahydrate_CopperSulfate_Copper-Sulfate_NorthChem2916_NorthChem_NorthQuest2916_7758-99-8_TDS.pdf"},
{"n":"Solfato di rame (pentaidrato)","s":"https://www.sigmaaldrich.com/US/en/sds/sigma/c8027","t":"https://northmetal.net/wp-content/uploads/Copper-Sulfate-Pentahydrate_CopperSulfate_Copper-Sulfate_NorthChem2916_NorthChem_NorthQuest2916_7758-99-8_TDS.pdf"},
{"n":"Solfato di sodio","s":"https://www.sigmaaldrich.com/US/en/sds/sigald/238597","t":"https://nugentec.com/content/tds/Sodium_Sulfate_Anhydrous_TDS.pdf"},
{"n":"Solfato di zinco","s":"https://www.valudor.com/wp-content/uploads/2022/04/Zinc-Sulfate-Granular-SDS-2019.pdf","t":"https://www.valudor.com/wp-content/uploads/2020/11/Zinc_Sulfate_Monohydrate-35_Granular.pdf"},
{"n":"Solfato ferrico","s":"https://www.fishersci.com/content/dam/fishersci/en_US/documents/programs/education/regulatory-documents/sds/chemicals/chemicals-f/S25322A.pdf","t":"https://iccorppr.com/wp-content/themes/industrialchemcorp/TDS/Ferric-Sulfate-Fe2-SO43-TDS.pdf"},
{"n":"Solfato ferroso","s":"https://www.fishersci.com/store/msds?partNumber=I146500&productDescription=FERROUS+SULFATE+CERT+ACS+500G&vendorId=VN00033897&countryCode=US&language=en","t":"https://iccorppr.com/wp-content/themes/industrialchemcorp/TDS/Ferrous-Sulfate-FeSO4-TDS.pdf"},
{"n":"Solfito di sodio","s":"https://download.basf.com/p1/000000000030042380_SDS_GEN_US/en/Sodium_Sulfite_anhydrous_photo_non_food_grade_Safety_Data_Sheet_USA_English.pdf","t":""},
{"n":"Solvente nafta aromatico (Solvesso)","s":"https://www.gcascc.com/wp-content/uploads/2018/09/Solvesso_EN.pdf","t":"https://www.exxonmobilchemical.com/en/chemicals/webapi/dps/v1/datasheets/130000102295/1/en"},
{"n":"Sorbato di potassio","s":"https://ingredi.com/content/pdfs/Potassium_Sorbate_SDS.pdf","t":"https://ingredi.com/content/pdfs/Potassium-Sorbate-Granular_TDS.pdf"},
{"n":"Sorbitano monostearato (Span 60)","s":"https://www.fishersci.com/store/msds?partNumber=AAL11435&productDescription=keyword&vendorId=VN00024248&countryCode=US&language=en","t":""},
{"n":"Sorbitolo","s":"https://www.fishersci.com/store/msds?partNumber=BP439500&productDescription=SORBITOL+500G&vendorId=VN00033897&countryCode=US&language=en","t":"https://tubanegin.com/wp-content/uploads/2021/07/Roquette_Quality_Specification-Sheet_NEOSORB-7070-B_50_421110_en.pdf"},
{"n":"Squalano","s":"https://www.fishersci.com/store/msds?partNumber=AC215355000&productDescription=SQUALANE+99%25+500ML&vendorId=VN00032119&countryCode=US&language=en","t":"https://www.makingcosmetics.com/on/demandware.static/-/Sites-makingcosmetics-master/default/dwe4589476/fact-sheets/fact-sheet-squalane.pdf"},
{"n":"Stagno (lingotti)","s":"https://www.fishersci.com/store/msds?partNumber=AA3664122&productDescription=TIN+SHT+3MM+99.99+%25+100G&vendorId=VN00024248&countryCode=US&language=en","t":""},
{"n":"Stearato di zinco","s":"https://www.fishersci.com/store/msds?partNumber=AC611515000&productDescription=ZINC+STEARATE+500GR&vendorId=VN00033901&countryCode=US&language=en","t":"https://bisleyinternational.com/wp-content/uploads/2021/10/Zinc-Stearate-TDS.pdf"},
{"n":"Stirene (monomero)","s":"https://www.sigmaaldrich.com/US/en/sds/sial/s4972","t":"https://www.cig-global.com/wp-content/uploads/2019/09/Styrene-Monomer-TDS.pdf"},
{"n":"Sucralosio","s":"https://www.tateandlyle.com/sites/default/files/2018-01/SPLENDA%20Sucralose%20Granular%20SDS.PDF","t":"https://www.tateandlyle.com/sites/default/files/2018-01/SPLENDA%20SUCRALOSE%20GRANULAR%20SPEC_0.pdf"},
{"n":"TAED (attivatore di candeggio)","s":"https://www.sigmaaldrich.com/US/en/sds/sial/387649","t":""},
{"n":"Talco","s":"https://www.fishersci.com/store/msds?partNumber=T2500&productDescription=TALC+USP+500GM&vendorId=VN00033897&countryCode=US&language=en","t":"https://avenalab.com/images/0001DOKUMENTACIJA/TDS/Talc_powder_TDS_ENG.pdf"},
{"n":"Tannini enologici","s":"https://www.sigmaaldrich.com/US/en/sds/sial/403040","t":"https://www.aeb-group.com/media/catalogo-unico/eb_xo-3019/docs/it/EB_XO_CDS_IT_2160420_OENO_IT.pdf"},
{"n":"Tartrato neutro di potassio","s":"https://www.fishersci.co.uk/chemicalProductData_uk/wercs?itemCode=P/7080/53","t":""},
{"n":"Tetraidrofurano (THF)","s":"https://www.fishersci.com/store/msds?partNumber=AC610450010&productDescription=TETRAHYDROFURAN+ANHYD&vendorId=VN00033901&countryCode=US&language=en","t":""},
{"n":"Tiosolfato di sodio","s":"https://www.fishersci.com/store/msds?partNumber=S446500&productDescription=SOD+THIOSULFATE+ANHYD+CRT+500G&vendorId=VN00033897&countryCode=US&language=en","t":""},
{"n":"Titanio (spugna o lingotti)","s":"https://www.fishersci.com/store/msds?partNumber=AA42459A1&productDescription=TITNM+SPNGE+3MM+DWN+99.9%25+1KG&vendorId=VN00024248&countryCode=US&language=en","t":""},
{"n":"Tocoferil acetato (vitamina E)","s":"https://download.basf.com/p1/000000000030041054_SDS_GEN_00/en/Vitamin_E-Acetate_(DL-alpha-tocopheryl_acetate)_Safety_Data_Sheet_United_Nations_English.pdf","t":"https://download.basf.com/p1/EN_StaticDocuments_6515/en/Technical_Information"},
{"n":"Toluene","s":"https://www.fishersci.com/store/msds?partNumber=AC326980010&productDescription=TOLUENE&vendorId=VN00033901&countryCode=US&language=en","t":""},
{"n":"Triclosan","s":"https://www.sigmaaldrich.com/US/en/sds/sigma/72779","t":""},
{"n":"Urea","s":"https://www.fishersci.com/store/msds?partNumber=U15500&productDescription=UREA+CERTIFIED+500G&vendorId=VN00033897&countryCode=US&language=en","t":""},
{"n":"White spirit / ragia minerale","s":"https://www.tupras.com.tr/assets/img/article/newsletters/tupras-white-spirit-safety-data-sheet.pdf","t":"https://www.vivaenergy.com.au/ArticleDocuments/942/1856_108855_16Jun2025150910_White%20Spirit%20200001730%20TDS%20-%202025-6-16.pdf.aspx"},
{"n":"Xilene (miscela)","s":"https://www.fishersci.com/store/msds?partNumber=S25629&productDescription=XYLENES+500ML+RG&vendorId=VN00115888&countryCode=US&language=en","t":""},
{"n":"Zeolite A","s":"https://www.pqcorp.com/docs/default-source/msds/pq-corporation/zeolites/valfor/valfor-100_msds_2015.pdf","t":""},
{"n":"Zinco (lingotti)","s":"https://www.nyrstar.com/cdn/3f3724f6-76fb-440a-bf56-203e2235f2e6/msds-special-high-grade-shg-zinc.pdf","t":"https://www.nyrstar.com/cdn/1a734162-6ad6-48c8-8fac-b41a983ff656/technical-datasheet-shg-budel-2020.pdf"},
{"n":"Zolfo elementare","s":"https://www.fishersci.com/store/msds?partNumber=AC201250025&productDescription=SULFUR%2C+SUBLIMED%2C+99.5%25+2.5KG&vendorId=VN00032119&countryCode=US&language=en","t":""}]$j$::jsonb) as x(n text, s text, t text);
  select md5(string_agg(h, '' order by h collate "C")) into got from (select md5(n||chr(31)||s||chr(31)||t) as h from _stg_sds) q;
  if got is distinct from expected then
    raise exception 'SDS payload integrity check failed: expected % got %', expected, got;
  end if;
  update public.products p
  set scheda_sicurezza_url = coalesce(nullif(btrim(s.s), ''), p.scheda_sicurezza_url),
      scheda_tecnica_url   = coalesce(nullif(btrim(s.t), ''), p.scheda_tecnica_url)
  from _stg_sds s
  where lower(btrim(p.canonical_name)) = lower(btrim(s.n));
  get diagnostics n_upd = row_count;
  raise notice 'SDS/TDS resync: staged=%, products updated=%', (select count(*) from _stg_sds), n_upd;
end
$mig$;
