-- Part B (batch 4/4): import specifiche in public.product_specs. Match SOLO per nome.
-- 'ordine' 0-based per prodotto (precalcolato). Righe 'Nessun dato' escluse. Integrity guard MD5.
do $mig$
declare
  expected text := '6704327caf56c95f638807e6c8579878';
  got text;
  n_ins int;
begin
  create temp table _stg_specs on commit drop as select n, f, v, (o)::int as o from jsonb_to_recordset($j$[{"n":"POM (acetalica)","f":"Descrizione prodotto","v":"Omopolimero acetalico a viscosità media per stampaggio a iniezione","o":0},
{"n":"POM (acetalica)","f":"Caratteristica","v":"Migliorata stabilità termica di processo rispetto a Delrin 500 standard","o":1},
{"n":"Potassa caustica","f":"Aspetto","v":"Grumi bianchi, pellet o scaglie, traslucide, deliquescenti","o":0},
{"n":"Potassa caustica","f":"Assay (titolo, acidimetrico)","v":"90%","o":1},
{"n":"Potassa caustica","f":"Materia insolubile in acqua","v":"0,05%","o":2},
{"n":"Potassa caustica","f":"Cloruri (Cl)","v":"0,05%","o":3},
{"n":"Potassa caustica","f":"Solfati (SO4)","v":"0,05%","o":4},
{"n":"Potassa caustica","f":"Arsenico (As)","v":"0,0003%","o":5},
{"n":"Potassa caustica","f":"Ferro (Fe)","v":"0,005%","o":6},
{"n":"Potassa caustica","f":"Metalli pesanti (come Pb)","v":"0,005%","o":7},
{"n":"Potassa caustica","f":"Punto di fusione","v":"360 °C","o":8},
{"n":"Potassa caustica","f":"Punto di ebollizione","v":"1327 °C","o":9},
{"n":"Potassa caustica","f":"Solubilità in acqua (20°C)","v":"1120 g/l","o":10},
{"n":"Profilati di alluminio","f":"Composizione chimica (Si)","v":"0,7-1,3%","o":0},
{"n":"Profilati di alluminio","f":"Composizione chimica (Mg)","v":"0,6-1,2%","o":1},
{"n":"Profilati di alluminio","f":"Composizione chimica (Mn)","v":"0,4-1,0%","o":2},
{"n":"Profilati di alluminio","f":"Resistenza a trazione (T6)","v":"290-310 MPa","o":3},
{"n":"Profilati di alluminio","f":"Resistenza a snervamento (T6)","v":"250-260 MPa","o":4},
{"n":"Profilati di alluminio","f":"Allungamento (T6)","v":"8-10%","o":5},
{"n":"Profilati di alluminio","f":"Durezza Vickers","v":"95-105 HV","o":6},
{"n":"Profilati di alluminio","f":"Durezza Brinell","v":"91-100 HB","o":7},
{"n":"Profilati di alluminio","f":"Densità","v":"2,7 g/cm³","o":8},
{"n":"Profilati di alluminio","f":"Conducibilità termica","v":"150-180 W/m·K","o":9},
{"n":"Propano","f":"Punto di ebollizione","v":"-42,1 °C (1,013 hPa)","o":0},
{"n":"Propano","f":"Pressione di vapore (25°C)","v":"953,25 kPa","o":1},
{"n":"Propilene","f":"Purezza (grado refrigerante R1270/CARE 45)","v":"≥99,5%","o":0},
{"n":"Propilene","f":"Caratteristiche","v":"Non tossico, ODP zero, GWP molto basso, infiammabile","o":1},
{"n":"Proteasi (subtilisina)","f":"Attività specifica","v":"~6 U/mg proteina (40°C, pH 8,0 su caseina)","o":0},
{"n":"Proteasi (subtilisina)","f":"Definizione unità","v":"1U = 1 µmole (181 µg) tirosina/min, pH 7,0, 40°C (Folin-Ciocalteu)","o":1},
{"n":"Proteasi (subtilisina)","f":"Formulazione","v":"50% (v/v) glicerolo","o":2},
{"n":"Proteasi (subtilisina)","f":"Shelf life (stabilità)","v":">4 anni a 4°C","o":3},
{"n":"Proteine della soia (isolato)","f":"Proteine (N x 6,25), minimo (esempio grado ADM)","v":"90%","o":0},
{"n":"Proteine della soia (isolato)","f":"pH (dispersione 1:10 in acqua)","v":"6,8-7,3","o":1},
{"n":"Protossido di azoto","f":"Purezza","v":">99% v/v","o":0},
{"n":"Protossido di azoto","f":"Punto di ebollizione","v":"-88,5 °C","o":1},
{"n":"Protossido di azoto","f":"Punto di fusione","v":"-90,8 °C","o":2},
{"n":"Protossido di azoto","f":"Densità di vapore (20°C)","v":"1,841","o":3},
{"n":"PTFE (teflon)","f":"Composizione","v":"Politetrafluoroetilene (PTFE) 100%","o":0},
{"n":"PTFE (teflon)","f":"Aspetto/Stato fisico","v":"Polvere solida, colore bianco, inodore","o":1},
{"n":"PTFE (teflon)","f":"Punto di fusione","v":"327 °C / 620,6 °F","o":2},
{"n":"PTFE (teflon)","f":"Densità (peso specifico)","v":"2,000","o":3},
{"n":"PTFE (teflon)","f":"Solubilità in acqua","v":"Nessuna informazione disponibile","o":4},
{"n":"PTFE (teflon)","f":"Conformità normativa","v":"Sostanza classificata come PFAS (OECD, EPA, ECHA, UK HSE); soggetta a restrizione REACH Allegato XVII voce 78 (restrizione microplastiche)","o":5},
{"n":"PVPP","f":"Composizione","v":"Poli[1-(2-osso-1-pirrolidinil)-1,2-etandiile] (PVPP) 100%","o":0},
{"n":"PVPP","f":"Aspetto/Stato fisico","v":"Polvere solida, colore bianco sporco (off-white), inodore","o":1},
{"n":"PVPP","f":"Punto di fusione","v":"300 °C / 572 °F","o":2},
{"n":"PVPP","f":"pH","v":"5,0-8,0","o":3},
{"n":"PVPP","f":"Solubilità in acqua","v":"Insolubile","o":4},
{"n":"PVPP","f":"Conformità normativa","v":"Soggetta a restrizione REACH Allegato XVII voce 78 (restrizione microplastiche)","o":5},
{"n":"Rame catodo","f":"Purezza del metallo","v":"Contenuto minimo di rame 99,99%","o":0},
{"n":"Rame catodo","f":"Conformità normativa","v":"Conforme allo standard BS EN 1978:1998; grado A LME (London Metal Exchange) e quotato su SHFE (Shanghai Futures Exchange)","o":1},
{"n":"Rame catodo","f":"Certificazioni","v":"ISO 9001, ISO 14001, OHSAS 18001/PN-N 18001; Certificato AEO (Customs Simplifications/Security and Safety)","o":2},
{"n":"Rame catodo","f":"Dimensioni catodo (Głogów I - HMG-S)","v":"Circa 910 x 910 x 14 mm","o":3},
{"n":"Rame catodo","f":"Peso catodo (Głogów I - HMG-S)","v":"Media 112 kg (80-145 kg)","o":4},
{"n":"Rame catodo","f":"Dimensioni catodo (Głogów II - HMG-B)","v":"Circa 1030 x 1030 x 16 mm","o":5},
{"n":"Rame catodo","f":"Peso catodo (Głogów II - HMG-B)","v":"Media 115 kg (80-130 kg)","o":6},
{"n":"Rame catodo","f":"Dimensioni catodo (Legnica - HML)","v":"Circa 910 x 780 x 15 mm","o":7},
{"n":"Rame catodo","f":"Peso catodo (Legnica - HML)","v":"Media 100 kg (90-110 kg)","o":8},
{"n":"Rame catodo","f":"Packaging disponibile","v":"Fasci (bundles) di 15-23 catodi legati con 1-3 reggette, peso fascio circa 1900-2200 kg","o":9},
{"n":"Refrigerante R134a","f":"Composizione","v":"1,1,1,2-Tetrafluoroetano (HFC-134a) 100%","o":0},
{"n":"Refrigerante R134a","f":"Formula molecolare","v":"1,1,1,2-Tetrafluoroetano","o":1},
{"n":"Refrigerante R134a","f":"Aspetto","v":"Gas liquefatto, incolore, odore leggero eterico","o":2},
{"n":"Refrigerante R134a","f":"Punto di congelamento","v":"-108 °C a 1013 hPa","o":3},
{"n":"Refrigerante R134a","f":"Punto di ebollizione","v":"-26 °C a 1013 hPa","o":4},
{"n":"Refrigerante R134a","f":"Temperatura di autoaccensione","v":"743 °C a 1013 hPa","o":5},
{"n":"Refrigerante R134a","f":"Tensione di vapore","v":"5700 hPa a 20 °C","o":6},
{"n":"Refrigerante R134a","f":"Densità relativa","v":"4,24 a 20 °C","o":7},
{"n":"Refrigerante R134a","f":"Solubilità in acqua","v":"1 g/l a 25 °C","o":8},
{"n":"Refrigerante R134a","f":"Coefficiente di ripartizione n-ottanolo/acqua","v":"Pow: 1,06 a 25 °C","o":9},
{"n":"Refrigerante R134a","f":"Potenziale di riscaldamento globale (GWP)","v":"1300","o":10},
{"n":"Refrigerante R134a","f":"Potenziale di riduzione dell'ozono (ODP)","v":"0","o":11},
{"n":"Refrigerante R32","f":"Formula molecolare (notazione chimica)","v":"CH2F2","o":0},
{"n":"Refrigerante R32","f":"Classe","v":"HFC","o":1},
{"n":"Refrigerante R32","f":"Peso molecolare relativo","v":"52,02 g/mol","o":2},
{"n":"Refrigerante R32","f":"Punto di ebollizione","v":"-52 °C","o":3},
{"n":"Refrigerante R32","f":"Temperatura critica","v":"78,11 °C","o":4},
{"n":"Refrigerante R32","f":"Pressione critica","v":"57,82 bar","o":5},
{"n":"Refrigerante R32","f":"Densità liquida (a 0 °C)","v":"961 kg/m³","o":6},
{"n":"Refrigerante R32","f":"Densità vapore (a 25 °C)","v":"47,34 kg/m³","o":7},
{"n":"Refrigerante R32","f":"Potenziale di riscaldamento globale (GWP, IPCC AR4)","v":"675","o":8},
{"n":"Refrigerante R32","f":"Potenziale di riduzione dell'ozono (ODP)","v":"Non lesivo per l'ozono (non-ozone depleting)","o":9},
{"n":"Refrigerante R32","f":"Classificazione ANSI/ASHRAE","v":"A2L (mildly flammable)","o":10},
{"n":"Refrigerante R32","f":"Temperature Glide","v":"0 K","o":11},
{"n":"Refrigerante R32","f":"Limiti di infiammabilità (LFL/UFL)","v":"13,6% vol / 28,4% vol","o":12},
{"n":"Refrigerante R32","f":"Temperatura di autoaccensione","v":"648 °C","o":13},
{"n":"Refrigerante R32","f":"Lubrificante tipico","v":"POE","o":14},
{"n":"Refrigerante R32","f":"Conformità normativa","v":"REACH Approved; categoria PED (Direttiva Attrezzature a Pressione) Cat 1","o":15},
{"n":"Refrigerante R32","f":"Refrigerante sostituito","v":"R-410A","o":16},
{"n":"Resina epossidica (base BPA)","f":"Descrizione prodotto","v":"Resina epossidica liquida difunzionale bisfenolo A/epicloridrina non diluita (EPON Resin 828)","o":0},
{"n":"Resina epossidica (base BPA)","f":"Colore","v":"Max 1 Gardner (ASTM D1544)","o":1},
{"n":"Resina epossidica (base BPA)","f":"Viscosità (a 25 °C)","v":"110-150 Poise (ASTM D445)","o":2},
{"n":"Resina epossidica (base BPA)","f":"Peso per epossido (Equivalent Weight)","v":"185-192 g/eq (ASTM D-1652)","o":3},
{"n":"Resina epossidica (base BPA)","f":"Densità (a 25 °C)","v":"9,7 lb/gal (ASTM D1475)","o":4},
{"n":"Resina epossidica (base BPA)","f":"Densità","v":"1,16 g/mL","o":5},
{"n":"Resina epossidica (base BPA)","f":"Indice di rifrazione (a 25 °C)","v":"1,573","o":6},
{"n":"Resina epossidica (base BPA)","f":"Calore specifico","v":"0,5 BTU/lb/°F","o":7},
{"n":"Resina epossidica (base BPA)","f":"Tensione di vapore (a 25 °C)","v":"0,03 mmHg","o":8},
{"n":"Resina epossidica (base BPA)","f":"Packaging disponibile","v":"Sfuso (autocisterne/carri cisterna) e fusti da 500 libbre","o":9},
{"n":"Resina epossidica (base BPA)","f":"Conformità normativa","v":"Idonea per contatto alimentare secondo 21 CFR 175.300 (FDA), se formulata, applicata e curata correttamente","o":10},
{"n":"Resina fenolica (PF)","f":"Peso specifico","v":"1,37 - 1,43 (ASTM D792)","o":0},
{"n":"Resina fenolica (PF)","f":"Ritiro allo stampaggio","v":"0,0033 - 0,011 in/in (ASTM D955)","o":1},
{"n":"Resina fenolica (PF)","f":"Resistenza a flessione","v":"10.200 - 14.100 psi (ASTM D790)","o":2},
{"n":"Resina fenolica (PF)","f":"Modulo a flessione","v":"1,0 - 1,3 msi","o":3},
{"n":"Resina fenolica (PF)","f":"Resistenza a trazione","v":"7.100 - 9.100 psi","o":4},
{"n":"Resina fenolica (PF)","f":"Resistenza a compressione","v":"26.700 - 33.200 psi","o":5},
{"n":"Resina fenolica (PF)","f":"Temperatura di deflessione al calore (HDT, 1,82 MPa)","v":"285 - 370 °F (ASTM D648)","o":6},
{"n":"Resina fenolica (PF)","f":"Densità apparente","v":"36,0 - 45,3 lb/ft3","o":7},
{"n":"Resina fenolica (PF)","f":"Metodi di lavorazione disponibili","v":"Stampaggio a compressione, transfer e iniezione","o":8},
{"n":"Resina fenolica (PF)","f":"Colore disponibile","v":"Nero","o":9},
{"n":"Resina fenolica (PF)","f":"Conformità normativa","v":"UL recognized component, file E40654","o":10},
{"n":"Resina melammina-formaldeide (MF)","f":"Aspetto","v":"Polvere bianco sporco (off-white)","o":0},
{"n":"Resina melammina-formaldeide (MF)","f":"Odore","v":"Leggermente irritante","o":1},
{"n":"Resina melammina-formaldeide (MF)","f":"pH","v":"8-10 (soluzione al 50% in acqua)","o":2},
{"n":"Resina melammina-formaldeide (MF)","f":"Punto di fusione/congelamento","v":"221-239°F (105-115°C)","o":3},
{"n":"Resina melammina-formaldeide (MF)","f":"Punto di infiammabilità","v":">200°F (>93°C)","o":4},
{"n":"Resina melammina-formaldeide (MF)","f":"Solubilità in acqua","v":"Leggermente solubile","o":5},
{"n":"Resina melammina-formaldeide (MF)","f":"Tensione di vapore","v":"Nessuna (resina polimerica)","o":6},
{"n":"Resina melammina-formaldeide (MF)","f":"Densità di vapore (Aria=1)","v":">1","o":7},
{"n":"Resina melammina-formaldeide (MF)","f":"Velocità di evaporazione","v":"0,65","o":8},
{"n":"Resina urea-formaldeide (UF)","f":"Composizione (grado UF Resin 1.2)","v":"Urea 47,43%; Formaldeide 28,46%; Acqua 23,81%; Borace 0,04%; Soda caustica 0,13%; Acido formico 0,13%","o":0},
{"n":"Resina urea-formaldeide (UF)","f":"Composizione (grado UF Resin 1.4)","v":"Urea 44,64%; Formaldeide 31,25%; Acqua 23,81%; Borace 0,04%; Soda caustica 0,13%; Acido formico 0,13%","o":1},
{"n":"Resina urea-formaldeide (UF)","f":"pH","v":"7,7 - 8,5","o":2},
{"n":"Resina urea-formaldeide (UF)","f":"Densità relativa","v":"1,285 - 1,300 g/cm3","o":3},
{"n":"Resina urea-formaldeide (UF)","f":"Punto di infiammabilità","v":"Il prodotto non sostiene la combustione","o":4},
{"n":"Resina urea-formaldeide (UF)","f":"Solubilità","v":"Facilmente solubile in acqua calda e fredda fino a un rapporto di 2 parti acqua per 1 parte resina","o":5},
{"n":"Resina urea-formaldeide (UF)","f":"Impieghi identificati","v":"Produzione di pannelli truciolari (chipboard) e MDF; impiego in accendifuoco e in miscele a rilascio lento come fertilizzante","o":6},
{"n":"Retinolo (vitamina A)","f":"Titolo (Assay, grado Retinol 50 C)","v":"Circa 50%; attività vitamina A 42,75-49,50% (1.425.000-1.650.000 UI/g)","o":0},
{"n":"Retinolo (vitamina A)","f":"Purezza","v":"All-trans-Retinolo minimo 95,0 Area-%; cis-isomeri massimo 5,0 Area-%","o":1},
{"n":"Retinolo (vitamina A)","f":"Sistema stabilizzante","v":"BHT 31,5-35,0 mg/g; BHA 9,0-11,0 mg/g","o":2},
{"n":"Retinolo (vitamina A)","f":"Aspetto","v":"Olio giallo, con formazione di cristalli a basse temperature","o":3},
{"n":"Retinolo (vitamina A)","f":"Solubilità","v":"Solubile in Polisorbato 20","o":4},
{"n":"Retinolo (vitamina A)","f":"Shelf life (Retinol 50 C)","v":"Almeno 24 mesi in confezione originale sigillata, a temperatura inferiore a 20°C","o":5},
{"n":"Retinolo (vitamina A)","f":"Shelf life (Retinol 15 D / 10 S)","v":"Almeno 18 mesi in confezione originale sigillata, a temperatura inferiore a 15°C","o":6},
{"n":"Retinolo (vitamina A)","f":"Stabilità in formulazione cosmetica","v":"Almeno 6 mesi se prodotta in atmosfera inerte e confezionata in tubetti di alluminio, conservata a 20°C","o":7},
{"n":"Riboflavina","f":"Contenuto di riboflavina (Assay)","v":"Minimo 80% (as is)","o":0},
{"n":"Riboflavina","f":"Aspetto","v":"Polvere da giallo-arancio a bruno-giallastro","o":1},
{"n":"Riboflavina","f":"Forma fisica","v":"Granuli (beadlets) sferici e uniformi, ottenuti per essiccazione a spruzzo con maltodestrina","o":2},
{"n":"Riboflavina","f":"Solubilità in acqua","v":"Leggermente solubile","o":3},
{"n":"Riboflavina","f":"Stabilità","v":"Discretamente stabile all'aria se protetta dalla luce","o":4},
{"n":"Riboflavina","f":"Shelf life","v":"Almeno 36 mesi dalla data di produzione, in confezione originale chiusa, a temperatura inferiore a 25°C","o":5},
{"n":"Rosso naftolo","f":"Formula molecolare","v":"C26H22N4O4","o":0},
{"n":"Rosso naftolo","f":"Peso molecolare","v":"454,48","o":1},
{"n":"Rosso naftolo","f":"Famiglia chimica","v":"Monoazoico","o":2},
{"n":"Rosso naftolo","f":"Indice colore (Colour Index)","v":"C.I. Pigment Red 170 (C.I. 12475)","o":3},
{"n":"Rosso naftolo","f":"Resistenza alla luce","v":"5","o":4},
{"n":"Rosso naftolo","f":"Resistenza al calore","v":"180°C","o":5},
{"n":"Rosso naftolo","f":"Resistenza all'acqua","v":"5","o":6},
{"n":"Rosso naftolo","f":"Resistenza all'olio","v":"4","o":7},
{"n":"Rosso naftolo","f":"Resistenza agli acidi","v":"5","o":8},
{"n":"Rosso naftolo","f":"Resistenza agli alcali","v":"5","o":9},
{"n":"Rosso naftolo","f":"Resistenza all'alcol","v":"4-5","o":10},
{"n":"Rosso naftolo","f":"Residuo al setaccio","v":"Massimo 1000 ppm","o":11},
{"n":"Rosso naftolo","f":"Assorbimento olio","v":"55-70 g/100g","o":12},
{"n":"Rosso naftolo","f":"Densità apparente","v":"0,20-0,35 g/ml","o":13},
{"n":"Rosso naftolo","f":"Granulometria (dimensione particelle)","v":"0,18-0,22 μm","o":14},
{"n":"Rosso naftolo","f":"Applicazioni","v":"Inchiostri a base acqua, offset e solvente; materie plastiche; vernici; stampa tessile","o":15},
{"n":"Sabbia di quarzo (filtrazione)","f":"SiO2 (contenuto)","v":"99,64%","o":0},
{"n":"Sabbia di quarzo (filtrazione)","f":"Ossidi minori (composizione chimica)","v":"CaO 0,12%, Al2O3 0,09%, Fe2O3 0,06%, K2O 0,02%, MgO 0,01%, Na2O 0,01%","o":1},
{"n":"Sabbia di quarzo (filtrazione)","f":"Granulometria disponibile","v":"0,45 - 0,62 mm","o":2},
{"n":"Sabbia di quarzo (filtrazione)","f":"Diametro mediano D50","v":"581 - 751 µm a seconda della granulometria","o":3},
{"n":"Sabbia di quarzo (filtrazione)","f":"Dimensione effettiva D10","v":"453 - 622 µm","o":4},
{"n":"Sabbia di quarzo (filtrazione)","f":"Coefficiente di uniformità (D60/D10)","v":"1,24 - 1,35","o":5},
{"n":"Sabbia di quarzo (filtrazione)","f":"Durezza Mohs","v":"7","o":6},
{"n":"Sabbia di quarzo (filtrazione)","f":"Densità apparente (bulk density)","v":"1,53 - 1,56 g/cm3 (95 - 97 lb/ft3)","o":7},
{"n":"Sabbia di quarzo (filtrazione)","f":"Densità reale","v":"2,65 g/cm3","o":8},
{"n":"Sabbia di quarzo (filtrazione)","f":"Rotondità / Sfericità","v":"0,8 / 0,8","o":9},
{"n":"Sabbia di quarzo (filtrazione)","f":"Solubilità in acido cloridrico (AWWA B-100)","v":"<0,1%","o":10},
{"n":"Sabbia di quarzo (filtrazione)","f":"Conformità normativa","v":"ANSI/AWWA B100-16","o":11},
{"n":"Saccarosio","f":"Formula molecolare","v":"C12H22O11","o":0},
{"n":"Saccarosio","f":"Peso molecolare","v":"342,3 g/mol","o":1},
{"n":"Saccarosio","f":"Aspetto","v":"Solido cristallino di colore bianco","o":2},
{"n":"Saccarosio","f":"Punto di fusione","v":"185 - 187 °C","o":3},
{"n":"Saccarosio","f":"Punto di ebollizione","v":"697,11 °C (a 1013,3 hPa)","o":4},
{"n":"Saccarosio","f":"Temperatura di decomposizione","v":"160 - 165 °C","o":5},
{"n":"Saccarosio","f":"Densità","v":"1,59 g/cm3 (25 °C)","o":6},
{"n":"Saccarosio","f":"pH","v":"5,5 - 7,5 (soluzione 342 g/L, 25 °C)","o":7},
{"n":"Saccarosio","f":"Solubilità in acqua","v":"0,5 g/mL, completamente solubile","o":8},
{"n":"Saccarosio","f":"Composizione (Sezione 3 SDS)","v":"80 - 100% (range dichiarato, trade secret)","o":9},
{"n":"Saccarosio","f":"Conservazione","v":"Temperatura ambiente, contenitore ben chiuso, in luogo asciutto","o":10},
{"n":"Sale alimentare (cloruro di sodio)","f":"NaCl (purezza)","v":"min 99,7% - target 99,8% - max 100%","o":0},
{"n":"Sale alimentare (cloruro di sodio)","f":"Calcio e Magnesio (come Ca)","v":"target 0,04%","o":1},
{"n":"Sale alimentare (cloruro di sodio)","f":"Solfati (come SO4)","v":"target 0,2%","o":2},
{"n":"Sale alimentare (cloruro di sodio)","f":"Insolubili in acqua","v":"0 - 0,002 - 0,02%","o":3},
{"n":"Sale alimentare (cloruro di sodio)","f":"Umidità superficiale","v":"0 - 0,03 - 0,1%","o":4},
{"n":"Sale alimentare (cloruro di sodio)","f":"Densità apparente (bulk density)","v":"65 - 84 lb/ft3 (1040 - 1345 g/L)","o":5},
{"n":"Sale alimentare (cloruro di sodio)","f":"Granulometria (distribuzione al vaglio)","v":"Trattenuto: USS 40 mesh 3%, USS 50 mesh 56%, USS 70 mesh 38%, fondo 0-10%","o":6},
{"n":"Sale alimentare (cloruro di sodio)","f":"Additivi","v":"Prodotto senza additivi (additive free)","o":7},
{"n":"Sale alimentare (cloruro di sodio)","f":"Conformità normativa","v":"USDA, FDA, Food Chemicals Codex (FCC); Kosher for Passover (OU-P)","o":8},
{"n":"Sale alimentare (cloruro di sodio)","f":"Shelf life","v":"5 anni in condizioni ottimali di stoccaggio","o":9},
{"n":"Sale alimentare (cloruro di sodio)","f":"Condizioni di stoccaggio","v":"Luogo asciutto e coperto, umidità <75%","o":10},
{"n":"Sale alimentare (cloruro di sodio)","f":"Packaging disponibile","v":"Sacchi da 25 lb e 50 lb, tote da 2000-2400 lb, sfuso","o":11},
{"n":"SAN","f":"Densità (ASTM D792)","v":"1,08 g/cm3 (tutti i gradi)","o":0},
{"n":"SAN","f":"Melt Volume Rate 220°C/10kg (ASTM D1238)","v":"5 - 122 cm3/10min a seconda del grado","o":1},
{"n":"SAN","f":"Resistenza a trazione a rottura (ASTM D638)","v":"9.000 - 11.000 psi","o":2},
{"n":"SAN","f":"Modulo a trazione (ASTM D638)","v":"470.000 - 552.000 psi","o":3},
{"n":"SAN","f":"Modulo a flessione (ASTM D790)","v":"495.000 - 520.000 psi","o":4},
{"n":"SAN","f":"Resistenza a flessione (ASTM D790)","v":"11.000 - 19.000 psi","o":5},
{"n":"SAN","f":"Durezza Rockwell M (ASTM D785)","v":"75 - 83","o":6},
{"n":"SAN","f":"Resilienza Izod con intaglio, 23°C (ASTM D256)","v":"0,3 - 0,4 ft-lb/in","o":7},
{"n":"SAN","f":"Resilienza Izod senza intaglio, 23°C (ASTM D256)","v":"3 - 6 ft-lb/in","o":8},
{"n":"SAN","f":"HDT a 264 psi, non ricotto/ricotto (ASTM D648)","v":"200 - 205 °F / 216 - 219 °F","o":9},
{"n":"SAN","f":"Temperatura di rammollimento Vicat B/1, 120°C/hr, 10N (ASTM D1525)","v":"217 - 232 °F (103 - 111 °C)","o":10},
{"n":"SAN","f":"Indice di rifrazione (ASTM D542)","v":"1,57","o":11},
{"n":"SAN","f":"Trasmissione luce a 550 nm (ASTM D1003)","v":"86 - 90%","o":12},
{"n":"SAN","f":"Haze (ASTM D1003)","v":"0,7 - 2%","o":13},
{"n":"SAN","f":"Contenuto d'umidità raccomandato (essiccazione)","v":"0,04 - 0,08%","o":14},
{"n":"SAN","f":"Condizioni di essiccamento consigliate","v":"175 °F per 2-4 ore","o":15},
{"n":"SAN","f":"Intervallo temperatura cilindro (stampaggio a iniezione)","v":"390 - 480 °F","o":16},
{"n":"SAN","f":"Intervallo temperatura di fusione (stampaggio a iniezione)","v":"430 - 500 °F","o":17},
{"n":"SAN","f":"Conformità normativa (gradi selezionati)","v":"USP Class VI, FDA Modified ISO 10993-1, UL94 HB a 1,5 mm","o":18},
{"n":"Sciroppo di glucosio","f":"Aspetto","v":"Liquido sciropposo da incolore a giallastro, sapore dolce, odore neutro","o":0},
{"n":"Sciroppo di glucosio","f":"pH","v":"4,0 - 6,0 (Ph. Eur.)","o":1},
{"n":"Sciroppo di glucosio","f":"Acidità","v":"0,6 mL max/5g (NaOH 0.1N, USP)","o":2},
{"n":"Sciroppo di glucosio","f":"SO2/Solfiti","v":"20 ppm max (Ph. Eur.)","o":3},
{"n":"Sciroppo di glucosio","f":"Metalli pesanti","v":"10 ppm max (USP)","o":4},
{"n":"Sciroppo di glucosio","f":"Sostanza secca (dry substance)","v":"79,9 - 80,9%","o":5},
{"n":"Sciroppo di glucosio","f":"Perdita all'essiccamento","v":"30% max (Ph. Eur.)","o":6},
{"n":"Sciroppo di glucosio","f":"Contenuto d'acqua","v":"21% max (USP)","o":7},
{"n":"Sciroppo di glucosio","f":"Destrosio equivalente (DE)","v":"40 - 43","o":8},
{"n":"Sciroppo di glucosio","f":"Ceneri solfatate","v":"0,5% max (Ph. Eur./USP)","o":9},
{"n":"Sciroppo di glucosio","f":"Amido","v":"Conforme (USP)","o":10},
{"n":"Sciroppo di glucosio","f":"Solventi residui","v":"Conforme (USP)","o":11},
{"n":"Sciroppo di glucosio","f":"Conteggio microbico totale","v":"max 1000/g","o":12},
{"n":"Sciroppo di glucosio","f":"Lieviti e muffe","v":"max 100/g","o":13},
{"n":"Sciroppo di glucosio","f":"E. coli","v":"Assente in 1 g","o":14},
{"n":"Sciroppo di glucosio","f":"Salmonella","v":"Assente in 10 g","o":15},
{"n":"Sciroppo di glucosio","f":"Conformità normativa","v":"Ph. Eur. (EP), USP","o":16},
{"n":"Silicato di sodio","f":"Rapporto SiO2/Na2O (forma liquida)","v":"da 1,60 a 3,25 a seconda del grado","o":0},
{"n":"Silicato di sodio","f":"Rapporto SiO2/Na2O (forma solida)","v":"da 2,00 a 3,22 a seconda del grado","o":1},
{"n":"Silicato di sodio","f":"Contenuto Na2O (forma liquida)","v":"8,60 - 16,35%","o":2},
{"n":"Silicato di sodio","f":"Contenuto SiO2 (forma liquida)","v":"26,2 - 33,2%","o":3},
{"n":"Silicato di sodio","f":"Contenuto Na2O (forma solida)","v":"23,50 - 33,00%","o":4},
{"n":"Silicato di sodio","f":"Contenuto SiO2 (forma solida)","v":"66,0 - 75,7%","o":5},
{"n":"Silicato di sodio","f":"Densità (forma liquida, 20°C)","v":"1,38 - 1,56 g/cm3 (35 - 59 °Bé)","o":6},
{"n":"Silicato di sodio","f":"Densità approssimata (forma solida)","v":"1,40 - 1,41 g/cm3 (88 lb/gal)","o":7},
{"n":"Silicato di sodio","f":"pH (soluzioni liquide)","v":"11,3 - 13,4","o":8},
{"n":"Silicato di sodio","f":"Viscosità (forma liquida, 20°C)","v":"60 - 2100 cP a seconda del grado","o":9},
{"n":"Silicato di sodio","f":"Forma fisica (solidi)","v":"Grumi grossi (coarse lumps) / polveri idrate o anidre","o":10},
{"n":"Silicato di sodio","f":"Certificazione stabilimenti","v":"Impianti PQ certificati ISO","o":11},
{"n":"Silicato di sodio (vetro solubile)","f":"Formula (SDS)","v":"Na2O7Si3","o":0},
{"n":"Silicato di sodio (vetro solubile)","f":"Sinonimi","v":"Water glass; Sodium trisilicate solution","o":1},
{"n":"Silicato di sodio (vetro solubile)","f":"Aspetto","v":"Liquido, incolore","o":2},
{"n":"Silicato di sodio (vetro solubile)","f":"pH","v":"12,5","o":3},
{"n":"Silicato di sodio (vetro solubile)","f":"Densità relativa","v":"1,39 g/cm3 a 25°C","o":4},
{"n":"Silicato di sodio (vetro solubile)","f":"Composizione (Sezione 3 SDS)","v":"Disodio metasilicato (CAS 6834-92-0) 50-70%; Biossido di silicio (CAS 7631-86-9) 10-20%","o":5},
{"n":"Silicio metallico","f":"Contenuto Si (grado SILMIL MG)","v":">99%","o":0},
{"n":"Silicio metallico","f":"Contenuto Si (grado SILMIL HP)","v":">99,9%","o":1},
{"n":"Silicio metallico","f":"Contenuto Si (grado SILMIL Pristine)","v":">99,99%","o":2},
{"n":"Silicio metallico","f":"Fe (impurità max)","v":"MG <0,50%; HP <0,05%; Pristine <0,005%","o":3},
{"n":"Silicio metallico","f":"Al (impurità max)","v":"MG <0,20%; HP <0,01%; Pristine <0,001%","o":4},
{"n":"Silicio metallico","f":"Ca (impurità max)","v":"MG <0,05%; HP <0,01%; Pristine <0,001%","o":5},
{"n":"Silicio metallico","f":"Ti (impurità max)","v":"MG <0,02%; HP <0,005%; Pristine <5 ppmw","o":6},
{"n":"Silicio metallico","f":"Granulometria","v":"Disponibile in diverse granulometrie (grain sizes) su richiesta","o":7},
{"n":"Silicio metallico","f":"Certificazioni stabilimento produttivo","v":"ISO 9001, ISO 14001, ISO 50001, OHSAS 18001","o":8},
{"n":"Soda caustica","f":"Grado","v":"ACS, USP, FCC","o":0},
{"n":"Soda caustica","f":"Aspetto","v":"Solido bianco","o":1},
{"n":"Soda caustica","f":"Titolo (Assay come NaOH)","v":"97,00-100,50%","o":2},
{"n":"Soda caustica","f":"Carbonato (come Na2CO3)","v":"<1,0%","o":3},
{"n":"Soda caustica","f":"Cloruro (Cl)","v":"<0,005%","o":4},
{"n":"Soda caustica","f":"Arsenico","v":"<3,0 ppm","o":5},
{"n":"Soda caustica","f":"Piombo","v":"<2,0 ppm","o":6},
{"n":"Soda caustica","f":"Composti azotati","v":"<0,001%","o":7},
{"n":"Soda caustica","f":"Fosfato (PO4)","v":"<0,001%","o":8},
{"n":"Soda caustica","f":"Solfato (SO4)","v":"<0,003%","o":9},
{"n":"Soda caustica","f":"Metalli pesanti (come Ag)","v":"<0,002%","o":10},
{"n":"Soda caustica","f":"Ferro (Fe)","v":"<0,001%","o":11},
{"n":"Soda caustica","f":"Nichel (Ni)","v":"<0,001%","o":12},
{"n":"Soda caustica","f":"Mercurio (Hg)","v":"<0,1 ppm","o":13},
{"n":"Soda caustica","f":"Calcio (Ca)","v":"<0,005%","o":14},
{"n":"Soda caustica","f":"Magnesio (Mg)","v":"<0,002%","o":15},
{"n":"Soda caustica","f":"Potassio (K)","v":"<0,02%","o":16},
{"n":"Sodio alluminato","f":"Aspetto","v":"Liquido, da limpido a leggermente torbido","o":0},
{"n":"Sodio alluminato","f":"Colore","v":"Ambra","o":1},
{"n":"Sodio alluminato","f":"Odore","v":"Nessun odore apprezzabile","o":2},
{"n":"Sodio alluminato","f":"pH","v":"~14","o":3},
{"n":"Sodio alluminato","f":"Punto di fusione/congelamento","v":"< -32,2°C (< -26°F)","o":4},
{"n":"Sodio alluminato","f":"Punto di ebollizione","v":"116°C (241°F)","o":5},
{"n":"Sodio alluminato","f":"Densità relativa","v":"1,4 - 1,6","o":6},
{"n":"Sodio alluminato","f":"Densità liquido","v":"11,6 - 13,3 lbs/gal","o":7},
{"n":"Sodio alluminato","f":"Viscosità dinamica","v":"200 - 400 cps (Brookfield @ 25°C)","o":8},
{"n":"Sodio alluminato","f":"Solubilità in acqua","v":"Completa","o":9},
{"n":"Sodio alluminato","f":"Composizione (Sezione 3 SDS)","v":"Acqua (7732-18-5) ~60%; Sodio alluminato/ossido di sodio-alluminio (1302-42-7) ~32%; Idrossido di sodio (1310-73-2) ~8%","o":10},
{"n":"Sodio citrato","f":"Nome INCI","v":"Sodium Citrate","o":0},
{"n":"Sodio citrato","f":"Formula molecolare","v":"C6H5Na3O7","o":1},
{"n":"Sodio citrato","f":"Peso molecolare","v":"258,07 g/mol","o":2},
{"n":"Sodio citrato","f":"Conformità normativa","v":"USP, FCC, E331","o":3},
{"n":"Sodio citrato","f":"Forma/Aspetto","v":"Cristalli granulari bianchi o polvere cristallina bianca, sapore leggermente salato","o":4},
{"n":"Sodio citrato","f":"pH","v":"7,5-9,0 (20°C, 10 g/L in H2O)","o":5},
{"n":"Sodio citrato","f":"Punto di fusione","v":"150°C (decomposizione)","o":6},
{"n":"Sodio citrato","f":"Solubilità","v":"425 g/L in acqua; praticamente insolubile in etanolo 96%","o":7},
{"n":"Sodio citrato","f":"Densità","v":"1,76 g/cm3 a 18°C","o":8},
{"n":"Sodio citrato","f":"Temperatura di stoccaggio","v":"2-30°C","o":9},
{"n":"Sodio citrato","f":"Dosaggio tipico (funzione tampone)","v":"0,1% - 2,0%","o":10},
{"n":"Sodio citrato","f":"Dosaggio tipico (funzione chelante)","v":"0,2% - 0,6%","o":11},
{"n":"Sodio cocoil isetionato (SCI)","f":"Nome INCI","v":"Sodium cocoyl isethionate (SCI)","o":0},
{"n":"Sodio cocoil isetionato (SCI)","f":"Nome chimico","v":"Fatty acid isethionate sodium salt","o":1},
{"n":"Sodio cocoil isetionato (SCI)","f":"Origine materia prima","v":"Vegetale, a base di olio di cocco purificato","o":2},
{"n":"Sodio cocoil isetionato (SCI)","f":"Categoria","v":"Tensioattivo anionico attivo >84%","o":3},
{"n":"Sodio cocoil isetionato (SCI)","f":"Aspetto","v":"Polvere solida granulare","o":4},
{"n":"Sodio cocoil isetionato (SCI)","f":"Colore","v":"Da bianco a bianco sporco","o":5},
{"n":"Sodio cocoil isetionato (SCI)","f":"Odore","v":"Caratteristico","o":6},
{"n":"Sodio cocoil isetionato (SCI)","f":"Attività (PM 343)","v":"min. 84,0%","o":7},
{"n":"Sodio cocoil isetionato (SCI)","f":"Solubilità","v":"Solubile in acqua","o":8},
{"n":"Sodio cocoil isetionato (SCI)","f":"Indice di acidità","v":"14,5 mg KOH/g","o":9},
{"n":"Sodio cocoil isetionato (SCI)","f":"Sodio isetionato","v":"max. 4,0%","o":10},
{"n":"Sodio cocoil isetionato (SCI)","f":"Acidi grassi liberi","v":"3,0 - 10,0%","o":11},
{"n":"Sodio cocoil isetionato (SCI)","f":"Contenuto acido stearico libero","v":"0%","o":12},
{"n":"Sodio cocoil isetionato (SCI)","f":"Umidità","v":"<0,3%","o":13},
{"n":"Sodio cocoil isetionato (SCI)","f":"Conta microbica totale","v":"<100 cfu/g","o":14},
{"n":"Sodio cocoil isetionato (SCI)","f":"1,4-Diossano","v":"<1 ppm","o":15},
{"n":"Sodio cocoil isetionato (SCI)","f":"Ossido di etilene","v":"<1 ppm","o":16},
{"n":"Sodio cocoil isetionato (SCI)","f":"Metalli pesanti (Ni, Cr, Co, Cd, Hg, Pb, As, Sb)","v":"<1 ppm ciascuno","o":17},
{"n":"Sodio cocoil isetionato (SCI)","f":"Composizione acidi grassi (C8:C18:1)","v":"C8:0 5,0%; C10:0 6,0%; C12:0 50,0%; C14:0 19,0%; C16:0 10,0%; C18:0 10,0%; C18:1 <0,1%","o":18},
{"n":"Sodio cocoil isetionato (SCI)","f":"Shelf life","v":"36 mesi in adeguate condizioni di stoccaggio","o":19},
{"n":"Sodio cocoil isetionato (SCI)","f":"EINECS","v":"263-052-5","o":20},
{"n":"Sodio gluconato","f":"Nome INCI","v":"Sodium Gluconate","o":0},
{"n":"Sodio gluconato","f":"Funzione INCI","v":"Chelante, agente condizionante per la pelle","o":1},
{"n":"Sodio gluconato","f":"Aspetto","v":"Polvere cristallina da bianca a marrone chiaro, granulare o fine, praticamente inodore","o":2},
{"n":"Sodio gluconato","f":"Solubilità","v":"Molto solubile in acqua; poco solubile in alcol; insolubile in etere","o":3},
{"n":"Sodio gluconato","f":"Processo produttivo","v":"Fermentazione di sciroppo di glucosio (mais); cristallizzato, centrifugato, essiccato, setacciato","o":4},
{"n":"Sodio laureth solfato (SLES)","f":"Descrizione chimica","v":"Sodium Laureth Sulfate + 2 EO (2 moli di ossido di etilene)","o":0},
{"n":"Sodio laureth solfato (SLES)","f":"Peso molecolare","v":"382 g/mol","o":1},
{"n":"Sodio laureth solfato (SLES)","f":"Nome INCI","v":"Sodium Laureth Sulfate","o":2},
{"n":"Sodio laureth solfato (SLES)","f":"Contenuto principio attivo (label)","v":"Sodium Laureth Sulfate 68 - 73%","o":3},
{"n":"Sodio laureth solfato (SLES)","f":"Aspetto","v":"Pasta fluida, da trasparente a giallastra","o":4},
{"n":"Sodio laureth solfato (SLES)","f":"Comportamento in soluzione acquosa","v":"Soluzioni liquide stabili fino al 28% di sostanza attiva; oltre tale soglia il prodotto diventa pastoso","o":5},
{"n":"Sodio laureth solfato (SLES)","f":"Additivi stabilizzanti","v":"Prodotto non conservato (privo di conservanti aggiunti)","o":6},
{"n":"Sodio lauril solfato (SLS)","f":"Chimica","v":"Sodium Lauryl Sulfate, a base di alcol grasso naturale primario a catena lineare satura","o":0},
{"n":"Sodio lauril solfato (SLS)","f":"Forma fisica","v":"Polvere fine libera scorrevole (grado Fine) o granuli (grado standard)","o":1},
{"n":"Sodio lauril solfato (SLS)","f":"Aspetto","v":"Da bianco a biancastro, odore leggero caratteristico","o":2},
{"n":"Sodio lauril solfato (SLS)","f":"Punto di fusione","v":"204 – 207 °C","o":3},
{"n":"Sodio lauril solfato (SLS)","f":"CMC (concentrazione micellare critica)","v":"2,365 g/l (8,2 mmol/l) a 20 °C","o":4},
{"n":"Sodio lauril solfato (SLS)","f":"Solubilità","v":"Solubile in acqua calda e fredda; scarsamente solubile in etanolo","o":5},
{"n":"Sodio lauril solfato (SLS)","f":"Densità apparente (bulk density)","v":"Grado standard: 0,61 g/mL; Grado Fine: 0,28 g/mL","o":6},
{"n":"Sodio lauril solfato (SLS)","f":"Densità dopo compattazione (tapped density)","v":"Grado standard: 0,70 g/mL; Grado Fine: 0,30 g/mL","o":7},
{"n":"Sodio lauril solfato (SLS)","f":"Conformità farmacopea","v":"Ph.Eur.: Sodium Laurilsulfate; USP/NF: Sodium Lauryl Sulfate; JP: Sodium Lauryl Sulfate","o":8},
{"n":"Sodio lauril solfato (SLS)","f":"Packaging disponibile","v":"Grado standard: 25 kg / 600 kg; Grado Fine: 15 kg","o":9},
{"n":"Sodio lauril solfato (SLS)","f":"Shelf life","v":"Almeno 2 anni in contenitori originali sigillati, protetto dall'umidità, conservato a meno di 30 °C","o":10},
{"n":"Sodio lauril solfato (SLS)","f":"Origine materie prime","v":"Materie prime vegetali e sintetiche","o":11},
{"n":"Sodio tripolifosfato (STPP)","f":"Composizione","v":"Triphosphoric acid, sodium salt (1:5) [STPP] >94% (CAS 7758-29-4); Diphosphoric acid, sodium salt (1:4) [pirofosfato di sodio] <6% (CAS 7722-88-5)","o":0},
{"n":"Sodio tripolifosfato (STPP)","f":"Aspetto","v":"Solido granulare bianco, inodore","o":1},
{"n":"Sodio tripolifosfato (STPP)","f":"pH","v":"9,5 – 10,2","o":2},
{"n":"Sodio tripolifosfato (STPP)","f":"Punto di fusione/congelamento","v":"> 622 °C (> 1151,6 °F)","o":3},
{"n":"Sodium hyaluronate (acido ialuronico)","f":"Formula molecolare","v":"(C14H20O11N1Na1)n","o":0},
{"n":"Sodium hyaluronate (acido ialuronico)","f":"Aspetto","v":"Polvere bianca","o":1},
{"n":"Sodium hyaluronate (acido ialuronico)","f":"Odore","v":"Inodore","o":2},
{"n":"Sodium hyaluronate (acido ialuronico)","f":"Solubilità","v":"100% solubile in acqua","o":3},
{"n":"Sodium hyaluronate (acido ialuronico)","f":"Condizioni di conservazione","v":"Conservare a temperatura < -15°C; evitare la luce solare diretta","o":4},
{"n":"Sol di silice (Kieselsol)","f":"Aspetto","v":"Soluzione opalescente di colore bianco-grigio, inodore","o":0},
{"n":"Sol di silice (Kieselsol)","f":"Composizione","v":"Particelle di biossido di silicio (SiO2) in sospensione colloidale","o":1},
{"n":"Sol di silice (Kieselsol)","f":"Granulometria particelle","v":"100-150 Å, dimensione costante, controllata e omogenea","o":2},
{"n":"Sol di silice (Kieselsol)","f":"Carica superficiale","v":"Elevata carica negativa al pH del vino","o":3},
{"n":"Sol di silice (Kieselsol)","f":"Dosi di impiego","v":"Mosti bianchi e succhi di frutta: 40-100 g/hl; Vini e filtrati dolci: 25-75 g/hl","o":4},
{"n":"Sol di silice (Kieselsol)","f":"Packaging disponibile","v":"Confezioni da 25 kg e da 1200 kg","o":5},
{"n":"Sol di silice (Kieselsol)","f":"Shelf life","v":"Almeno 24 mesi dalla data di produzione (confezione chiusa)","o":6},
{"n":"Sol di silice (Kieselsol)","f":"Conservazione (confezione chiusa)","v":"Luogo fresco (T < 25°C), asciutto, ventilato","o":7},
{"n":"Sol di silice (Kieselsol)","f":"Conservazione (confezione aperta)","v":"Richiudere accuratamente, luogo fresco (T < 15°C), utilizzare in tempi brevi","o":8},
{"n":"Solfato di alluminio","f":"% Al2O3","v":"17.0 - 17.5%","o":0},
{"n":"Solfato di alluminio","f":"% Fe","v":"0.001 - 0.03%","o":1},
{"n":"Solfato di alluminio","f":"% Insolubile","v":"< 0.5%","o":2},
{"n":"Solfato di alluminio","f":"Granulometria","v":"Passante a 4 mesh: 0%; Passante a 10 mesh: ≥ 90%","o":3},
{"n":"Solfato di alluminio","f":"Conformità normativa","v":"AWWA Standard B403-09; NSF/ANSI Standard 60 (dosaggio massimo 150 mg/L)","o":4},
{"n":"Solfato di alluminio","f":"Packaging disponibile","v":"Sacchi da 50 lb, big bag (FIBC), sfuso (autocisterna pneumatica)","o":5},
{"n":"Solfato di alluminio","f":"Purezza/Assay","v":"> 95% (aluminum sulfate)","o":6},
{"n":"Solfato di alluminio","f":"Formula molecolare","v":"Al2O12S3","o":7},
{"n":"Solfato di alluminio","f":"Peso molecolare","v":"342.13 g/mol","o":8},
{"n":"Solfato di alluminio","f":"Aspetto","v":"Polvere solida di colore bianco","o":9},
{"n":"Solfato di alluminio","f":"Punto di fusione","v":"770°C / 1418°F","o":10},
{"n":"Solfato di alluminio","f":"Solubilità","v":"Solubile in acqua","o":11},
{"n":"Solfato di ammonio","f":"Denominazione/Grado","v":"Ammonium sulfate, anhydrous, Redi-Dri, ReagentPlus, ≥ 99.0%","o":0},
{"n":"Solfato di ammonio","f":"Assay/Composizione","v":"Ammonium sulphate ≥ 90 - ≤ 100% (w/w)","o":1},
{"n":"Solfato di ammonio","f":"Peso molecolare","v":"132.14 g/mol","o":2},
{"n":"Solfato di ammonio","f":"Aspetto","v":"Cristallino, incolore","o":3},
{"n":"Solfato di ammonio","f":"Odore","v":"Inodore","o":4},
{"n":"Solfato di ammonio","f":"pH","v":"5.0 - 6 (soluzione 132 g/l, 25°C)","o":5},
{"n":"Solfato di ammonio","f":"Punto di fusione","v":"280°C / 536°F","o":6},
{"n":"Solfato di ammonio","f":"Temperatura di decomposizione","v":"> 235°C / > 455°F","o":7},
{"n":"Solfato di ammonio","f":"Densità","v":"1.77 g/cm3 (25°C)","o":8},
{"n":"Solfato di ammonio","f":"Tensione di vapore","v":"< 0.1 hPa (25°C)","o":9},
{"n":"Solfato di ammonio","f":"Solubilità in acqua","v":"767 g/l (25°C)","o":10},
{"n":"Solfato di ammonio","f":"Solubilità in altri solventi","v":"Insolubile in etanolo e in acetone","o":11},
{"n":"Solfato di bario (blanc fixe)","f":"Formula molecolare","v":"BaSO4","o":0},
{"n":"Solfato di bario (blanc fixe)","f":"Peso molecolare","v":"233 g/mol","o":1},
{"n":"Solfato di bario (blanc fixe)","f":"Purezza (BaSO4, DIN 55911)","v":"> 99 %","o":2},
{"n":"Solfato di bario (blanc fixe)","f":"Granulometria media (Sedigraph)","v":"1,7 μm","o":3},
{"n":"Solfato di bario (blanc fixe)","f":"Densità","v":"4,4 g/cm3","o":4},
{"n":"Solfato di bario (blanc fixe)","f":"Densità apparente (tapped density)","v":"1,4 kg/l","o":5},
{"n":"Solfato di bario (blanc fixe)","f":"Superficie specifica (BET)","v":"1,4 m2/g","o":6},
{"n":"Solfato di bario (blanc fixe)","f":"Colore (Lightness L*, ISO 7724)","v":"98 %","o":7},
{"n":"Solfato di bario (blanc fixe)","f":"Indice assorbimento olio (ISO 787/5)","v":"13 g/100g","o":8},
{"n":"Solfato di bario (blanc fixe)","f":"pH (ISO 787/9)","v":"9","o":9},
{"n":"Solfato di bario (blanc fixe)","f":"Residuo al setaccio >45μm (DIN 53195)","v":"< 0,01 %","o":10},
{"n":"Solfato di bario (blanc fixe)","f":"Conducibilità elettrica (ISO 787/14)","v":"100 μS/cm","o":11},
{"n":"Solfato di bario (blanc fixe)","f":"Solubilità in acqua (ISO 787/3)","v":"0,05 %","o":12},
{"n":"Solfato di bario (blanc fixe)","f":"Cloruri (ISO 787/13)","v":"0,0005 %","o":13},
{"n":"Solfato di bario (blanc fixe)","f":"Sostanze volatili (ISO 787/2)","v":"0,05 %","o":14},
{"n":"Solfato di bario (blanc fixe)","f":"Aspetto","v":"Polvere cristallina bianca, inodore","o":15},
{"n":"Solfato di bario (blanc fixe)","f":"Temperatura di decomposizione","v":"> 1.600 °C (non fonde, decompone)","o":16},
{"n":"Solfato di bario (blanc fixe)","f":"Packaging disponibile","v":"Sacchi di carta da 25 kg; big bags da 1000 kg","o":17},
{"n":"Solfato di magnesio","f":"Denominazione prodotto","v":"Magnesium Sulphate Anhydrous (garanzia 32,5% MgO e 65% SO3)","o":0},
{"n":"Solfato di magnesio","f":"Aspetto","v":"Sale quasi bianco, igroscopico","o":1},
{"n":"Solfato di magnesio","f":"Contenuto MgSO4","v":"98,4 % (tipico)","o":2},
{"n":"Solfato di magnesio","f":"Altri solfati (K2SO4, CaSO4)","v":"1,1 % (tipico)","o":3},
{"n":"Solfato di magnesio","f":"Acqua di cristallizzazione","v":"0,5 % (tipico)","o":4},
{"n":"Solfato di magnesio","f":"Granulometria","v":"0,09-0,8 mm: 85 %; d50 0,33 mm","o":5},
{"n":"Solfato di magnesio","f":"Densità apparente (bulk density)","v":"ca. 1.300 kg/m3","o":6},
{"n":"Solfato di magnesio","f":"Angolo di riposo","v":"ca. 31°","o":7},
{"n":"Solfato di magnesio","f":"Solubilità in acqua","v":"26,3 % a 20 °C","o":8},
{"n":"Solfato di magnesio","f":"Materiale insolubile in acqua","v":"tipicamente 1,5 %","o":9},
{"n":"Solfato di magnesio (sale di Epsom)","f":"Formula molecolare","v":"MgSO4·7H2O","o":0},
{"n":"Solfato di magnesio (sale di Epsom)","f":"Peso molecolare","v":"246,48 g/mol","o":1},
{"n":"Solfato di magnesio (sale di Epsom)","f":"Composizione","v":"Magnesium Sulfate Heptahydrate 100%","o":2},
{"n":"Solfato di magnesio (sale di Epsom)","f":"Aspetto","v":"Cristalli o polvere incolore/bianca, inodore","o":3},
{"n":"Solfato di magnesio (sale di Epsom)","f":"pH","v":"7 (soluzione 35% a 20 °C)","o":4},
{"n":"Solfato di magnesio (sale di Epsom)","f":"Punto di fusione","v":"48,1 °C (118,4 °F)","o":5},
{"n":"Solfato di magnesio (sale di Epsom)","f":"Solubilità in acqua","v":"34 g/100 mL a 20 °C","o":6},
{"n":"Solfato di magnesio (sale di Epsom)","f":"Densità relativa","v":"1,7 (acqua=1)","o":7},
{"n":"Solfato di magnesio (sale di Epsom)","f":"Granulometria","v":"Standard 0,1-2 mm; cristalli fini: 0,8 mm","o":8},
{"n":"Solfato di magnesio (sale di Epsom)","f":"Densità apparente","v":"0,92 g/cm3","o":9},
{"n":"Solfato di magnesio (sale di Epsom)","f":"Tensione di vapore","v":"8 mm Hg a 68 °F (20 °C)","o":10},
{"n":"Solfato di manganese","f":"Aspetto","v":"Polvere da bianca a rosa chiaro","o":0},
{"n":"Solfato di manganese","f":"Manganese (Mn)","v":"32,0 % min","o":1},
{"n":"Solfato di manganese","f":"Purezza","v":"98,7 % min","o":2},
{"n":"Solfato di manganese","f":"Ferro","v":"2 ppm max","o":3},
{"n":"Solfato di manganese","f":"Piombo","v":"50 ppm max","o":4},
{"n":"Solfato di manganese","f":"Arsenico","v":"10 ppm max","o":5},
{"n":"Solfato di manganese","f":"Mercurio","v":"2 ppm max","o":6},
{"n":"Solfato di manganese","f":"Cadmio","v":"0,1 ppm max","o":7},
{"n":"Solfato di manganese","f":"Materiale insolubile in acqua (a pH 5)","v":"0,1 % max","o":8},
{"n":"Solfato di manganese","f":"Umidità (w/w)","v":"0,30 % max","o":9},
{"n":"Solfato di manganese","f":"Densità apparente","v":"0,90-1,70 g/cm3","o":10},
{"n":"Solfato di manganese","f":"Granulometria","v":"80 % min passante a 200 BSS (mesh)","o":11},
{"n":"Solfato di manganese","f":"Packaging disponibile","v":"Sacchi da 25 kg, sacchi da 50 lb, big bags/totes","o":12},
{"n":"Solfato di potassio (SOP)","f":"Formula chimica","v":"K₂SO₄","o":0},
{"n":"Solfato di potassio (SOP)","f":"Aspetto","v":"Cristalli bianchi","o":1},
{"n":"Solfato di potassio (SOP)","f":"Ossido di potassio (K₂O)","v":"> 51% w/w","o":2},
{"n":"Solfato di potassio (SOP)","f":"Potassio (K)","v":"> 42% w/w","o":3},
{"n":"Solfato di potassio (SOP)","f":"Triossido di zolfo (SO₃)","v":"> 45% w/w","o":4},
{"n":"Solfato di potassio (SOP)","f":"Zolfo (S)","v":"> 18% w/w","o":5},
{"n":"Solfato di potassio (SOP)","f":"Arsenico (As)","v":"< 1 mg/kg","o":6},
{"n":"Solfato di potassio (SOP)","f":"Cadmio (Cd)","v":"< 1 mg/kg","o":7},
{"n":"Solfato di potassio (SOP)","f":"Cromo (Cr)","v":"< 4 mg/kg","o":8},
{"n":"Solfato di potassio (SOP)","f":"Mercurio (Hg)","v":"< 0.1 mg/kg","o":9},
{"n":"Solfato di potassio (SOP)","f":"Piombo (Pb)","v":"< 10 mg/kg","o":10},
{"n":"Solfato di potassio (SOP)","f":"Densità","v":"1.3 ± 0.1 g/cm³","o":11},
{"n":"Solfato di potassio (SOP)","f":"pH","v":"2.8 ± 0.5 (soluzione 1%); 4 ± 1 (soluzione 10%)","o":12},
{"n":"Solfato di potassio (SOP)","f":"Conducibilità elettrica (EC)","v":"1.8 ± 0.3 mS/cm (sol. 0.1%); 13 ± 1 mS/cm (sol. 1%)","o":13},
{"n":"Solfato di potassio (SOP)","f":"Solubilità","v":"120 g/L","o":14},
{"n":"Solfato di potassio (SOP)","f":"Insolubili","v":"< 0.05%","o":15},
{"n":"Solfato di potassio (SOP)","f":"Umidità","v":"< 0.05%","o":16},
{"n":"Solfato di potassio (SOP)","f":"Conformità normativa","v":"REACH Reg. 01-2119489441-34; EC Fertiliser","o":17},
{"n":"Solfato di rame","f":"Formula chimica","v":"CuSO₄ x 5H₂O","o":0},
{"n":"Solfato di rame","f":"Aspetto","v":"Cristallo blu","o":1},
{"n":"Solfato di rame","f":"Solfato di rame (assay)","v":"99% min","o":2},
{"n":"Solfato di rame","f":"Rame (Cu)","v":"25.2% min","o":3},
{"n":"Solfato di rame","f":"Piombo (Pb)","v":"< 0.003%","o":4},
{"n":"Solfato di rame","f":"Cromo (Cr)","v":"< 0.001%","o":5},
{"n":"Solfato di rame","f":"Packaging disponibile","v":"Sacchi da 50 lb, 40 sacchi per pallet","o":6},
{"n":"Solfato di rame","f":"Shelf life","v":"Almeno 3 anni in confezione integra e correttamente conservata","o":7},
{"n":"Solfato di rame (pentaidrato)","f":"Formula chimica","v":"CuSO₄ x 5H₂O","o":0},
{"n":"Solfato di rame (pentaidrato)","f":"Aspetto","v":"Cristallo blu","o":1},
{"n":"Solfato di rame (pentaidrato)","f":"Solfato di rame (assay)","v":"99% min","o":2},
{"n":"Solfato di rame (pentaidrato)","f":"Rame (Cu)","v":"25.2% min","o":3},
{"n":"Solfato di rame (pentaidrato)","f":"Piombo (Pb)","v":"< 0.003%","o":4},
{"n":"Solfato di rame (pentaidrato)","f":"Cromo (Cr)","v":"< 0.001%","o":5},
{"n":"Solfato di rame (pentaidrato)","f":"Packaging disponibile","v":"Sacchi da 50 lb, 40 sacchi per pallet","o":6},
{"n":"Solfato di rame (pentaidrato)","f":"Shelf life","v":"Almeno 3 anni in confezione integra e correttamente conservata","o":7},
{"n":"Solfato di sodio","f":"Formula molecolare","v":"Na₂SO₄","o":0},
{"n":"Solfato di sodio","f":"Peso molecolare","v":"142.04","o":1},
{"n":"Solfato di sodio","f":"Aspetto","v":"Polvere cristallina bianca","o":2},
{"n":"Solfato di sodio","f":"Grado","v":"ACS","o":3},
{"n":"Solfato di sodio","f":"Punto di fusione","v":"884 °C","o":4},
{"n":"Solfato di sodio","f":"Punto di ebollizione","v":"1429 °C","o":5},
{"n":"Solfato di sodio","f":"Punto di infiammabilità","v":"Nessuno","o":6},
{"n":"Solfato di sodio","f":"Indice di rifrazione","v":"1.468","o":7},
{"n":"Solfato di sodio","f":"Densità","v":"2.664 g/cc","o":8},
{"n":"Solfato di sodio","f":"Densità apparente","v":"8.7 lb/gal","o":9},
{"n":"Solfato di sodio","f":"pH (soluzione 5% a 25°C)","v":"Neutro","o":10},
{"n":"Solfato di sodio","f":"Solubilità in acqua","v":"Completa","o":11},
{"n":"Solfato di sodio","f":"Purezza/Assay","v":"99.0% min","o":12},
{"n":"Solfato di sodio","f":"Materia insolubile","v":"0.01% max","o":13},
{"n":"Solfato di sodio","f":"Cloruri (Cl)","v":"10 ppm max","o":14},
{"n":"Solfato di sodio","f":"Composti azotati (come N)","v":"5 ppm max","o":15},
{"n":"Solfato di sodio","f":"Arsenico (As)","v":"1 ppm max","o":16},
{"n":"Solfato di sodio","f":"Calcio, Magnesio e precipitati R₂O₃","v":"200 ppm max","o":17},
{"n":"Solfato di sodio","f":"Metalli pesanti (come Pb)","v":"5 ppm max","o":18},
{"n":"Solfato di sodio","f":"Ferro (Fe)","v":"10 ppm max","o":19},
{"n":"Solfato di sodio","f":"Packaging disponibile","v":"Fusti in fibra da 50 kg con doppio rivestimento","o":20},
{"n":"Solfato di zinco","f":"Zinco (Zn)","v":"33.8% tipico; specifica ≥ 33.5%","o":0},
{"n":"Solfato di zinco","f":"Piombo (Pb)","v":"6 ppm tipico; specifica ≤ 10 ppm","o":1},
{"n":"Solfato di zinco","f":"Cadmio (Cd)","v":"5 ppm tipico; specifica ≤ 10 ppm","o":2},
{"n":"Solfato di zinco","f":"Arsenico (As)","v":"4 ppm tipico; specifica ≤ 5 ppm","o":3},
{"n":"Solfato ferrico","f":"Stato fisico","v":"Liquido","o":0},
{"n":"Solfato ferrico","f":"Colore","v":"Rosso bruno","o":1},
{"n":"Solfato ferrico","f":"Odore","v":"Acido","o":2},
{"n":"Solfato ferrico","f":"pH","v":"< 2","o":3},
{"n":"Solfato ferrico","f":"Densità relativa (Specific Gravity)","v":"1.38 – 1.59","o":4},
{"n":"Solfato ferrico","f":"Shelf life","v":"3 anni (condizioni controllate)","o":5},
{"n":"Solfato ferrico","f":"Packaging disponibile","v":"Fusti plastica 55 gal / Tote bin 250 gal / Autocisterne bulk","o":6},
{"n":"Solfato ferroso","f":"Stato fisico","v":"Liquido","o":0},
{"n":"Solfato ferroso","f":"Colore","v":"Verde chiaro limpido","o":1},
{"n":"Solfato ferroso","f":"Odore","v":"Acido","o":2},
{"n":"Solfato ferroso","f":"pH","v":"< 2","o":3},
{"n":"Solfato ferroso","f":"Densità relativa (Specific Gravity)","v":"1.08 – 1.28","o":4},
{"n":"Solfato ferroso","f":"Shelf life","v":"3 anni (condizioni controllate)","o":5},
{"n":"Solfato ferroso","f":"Packaging disponibile","v":"Fusti plastica 55 gal / Tote bin 250 gal","o":6},
{"n":"Solfito di sodio","f":"Formula molecolare","v":"Na2SO3","o":0},
{"n":"Solfito di sodio","f":"Purezza/Assay (sodio solfito, W/W)","v":"> 80.0 – ≤ 100.0%","o":1},
{"n":"Solfito di sodio","f":"Stato fisico","v":"Solido, polvere cristallina","o":2},
{"n":"Solfito di sodio","f":"Odore","v":"Inodore","o":3},
{"n":"Solfito di sodio","f":"Colore","v":"Bianco a leggermente giallo","o":4},
{"n":"Solfito di sodio","f":"pH","v":"8.5 – 10.5 (soluzione 5% m/m, 20°C)","o":5},
{"n":"Solfito di sodio","f":"Punto di fusione","v":"Il prodotto si decompone (non fonde)","o":6},
{"n":"Solfito di sodio","f":"Densità","v":"2.633 g/cm3 (20°C)","o":7},
{"n":"Solfito di sodio","f":"Densità apparente","v":"1.400 – 1.600 kg/m3","o":8},
{"n":"Solfito di sodio","f":"Decomposizione termica","v":"500°C","o":9},
{"n":"Solfito di sodio","f":"Solubilità in acqua","v":"220 g/l (20°C)","o":10},
{"n":"Solfito di sodio","f":"Granulometria (D50)","v":"257 μm (ISO 13320-1)","o":11},
{"n":"Solvente nafta aromatico (Solvesso)","f":"Descrizione prodotto","v":"Solvesso 100 - Fluido aromatico C9 ad alta solvenza","o":0},
{"n":"Solvente nafta aromatico (Solvesso)","f":"Contenuto aromatico","v":"Min. 98 wt% (metodo GC)","o":1},
{"n":"Solvente nafta aromatico (Solvesso)","f":"Contenuto di benzene","v":"Max. 10 ppm (metodo GCMS)","o":2},
{"n":"Solvente nafta aromatico (Solvesso)","f":"Colore Saybolt","v":"Min. 30 (ASTM D156 / ASTM D6045)","o":3},
{"n":"Solvente nafta aromatico (Solvesso)","f":"Punto di infiammabilità","v":"Min. 42 °C (ASTM D56)","o":4},
{"n":"Solvente nafta aromatico (Solvesso)","f":"Densità (Specific Gravity 15.6/15.6°C)","v":"0,868 - 0,878 (ASTM D4052)","o":5},
{"n":"Solvente nafta aromatico (Solvesso)","f":"Distillazione - Punto iniziale di ebollizione (IBP)","v":"Min. 154 °C (ASTM D86)","o":6},
{"n":"Solvente nafta aromatico (Solvesso)","f":"Distillazione - Punto secco (Dry Point)","v":"Max. 174 °C (ASTM D86)","o":7},
{"n":"Solvente nafta aromatico (Solvesso)","f":"Contenuto HAP (Hazardous Air Pollutants)","v":"≤ 3,4 wt%","o":8},
{"n":"Solvente nafta aromatico (Solvesso)","f":"Additivo BHT","v":"Circa 25 ppm","o":9},
{"n":"Sorbato di potassio","f":"Qualità","v":"FCC","o":0},
{"n":"Sorbato di potassio","f":"Funzione","v":"Agente antimicrobico; conservante","o":1},
{"n":"Sorbato di potassio","f":"Shelf life","v":"2 anni","o":2},
{"n":"Sorbato di potassio","f":"Nome chimico","v":"Potassio (E,E)-esa-2,4-dienoato","o":3},
{"n":"Sorbato di potassio","f":"Formula molecolare","v":"C6H7KO2","o":4},
{"n":"Sorbato di potassio","f":"Peso molecolare","v":"150,22","o":5},
{"n":"Sorbato di potassio","f":"Aspetto","v":"Granulare bianco o polvere bianca","o":6},
{"n":"Sorbato di potassio","f":"Stabilità al calore","v":"Nessun cambiamento di colore dopo riscaldamento per 90 minuti a 105 °C","o":7},
{"n":"Sorbato di potassio","f":"Assay (titolo)","v":"99,0 - 101,0%","o":8},
{"n":"Sorbato di potassio","f":"Perdita all'essiccamento (Loss on Drying)","v":"NMT 1,0%","o":9},
{"n":"Sorbato di potassio","f":"Alcalinità (come K2CO3)","v":"NMT 1,0%","o":10},
{"n":"Sorbato di potassio","f":"Acidità (come acido sorbico)","v":"NMT 1,0%","o":11},
{"n":"Sorbato di potassio","f":"Aldeidi","v":"NMT 0,1%","o":12},
{"n":"Sorbato di potassio","f":"Metalli pesanti (come Pb)","v":"NMT 10 mg/kg","o":13},
{"n":"Sorbato di potassio","f":"Piombo","v":"NMT 2 mg/kg","o":14},
{"n":"Sorbato di potassio","f":"Mercurio","v":"NMT 1 mg/kg","o":15},
{"n":"Sorbato di potassio","f":"Arsenico","v":"NMT 2 mg/kg","o":16},
{"n":"Sorbitano monostearato (Span 60)","f":"Composizione (SDS Sez. 3)","v":"Sorbitan monooctadecanoate, CAS 1338-41-6, ≤100%","o":0},
{"n":"Sorbitano monostearato (Span 60)","f":"Stato fisico","v":"Solido","o":1},
{"n":"Sorbitano monostearato (Span 60)","f":"Colore","v":"Crema chiaro","o":2},
{"n":"Sorbitano monostearato (Span 60)","f":"Punto di fusione","v":"53 - 57 °C (127,4 - 134,6 °F)","o":3},
{"n":"Sorbitano monostearato (Span 60)","f":"Punto di infiammabilità","v":"> 149 °C (> 300,2 °F)","o":4},
{"n":"Sorbitano monostearato (Span 60)","f":"Formula molecolare","v":"C24H46O6","o":5},
{"n":"Sorbitano monostearato (Span 60)","f":"Peso molecolare","v":"430,63","o":6},
{"n":"Sorbitano monostearato (Span 60)","f":"Densità","v":"1 g/cm3 @ 20 °C","o":7},
{"n":"Sorbitano monostearato (Span 60)","f":"Solubilità in acqua","v":"Insolubile in acqua","o":8},
{"n":"Sorbitolo","f":"D-Sorbitolo (tal quale)","v":"45.0% min","o":0},
{"n":"Sorbitolo","f":"Contenuto d'acqua","v":"28.5 - 31.5%","o":1},
{"n":"Sorbitolo","f":"Residuo all'incenerimento","v":"0.1% max","o":2},
{"n":"Sorbitolo","f":"Nichel","v":"1 mg/kg max","o":3},
{"n":"Sorbitolo","f":"Zuccheri riducenti (su sostanza secca)","v":"0.3% max","o":4},
{"n":"Sorbitolo","f":"pH","v":"5.0 - 7.5","o":5},
{"n":"Sorbitolo","f":"Shelf life","v":"data di produzione + 3 anni in confezione integra","o":6},
{"n":"Sorbitolo","f":"Conformità normativa","v":"Farmacopea NF","o":7},
{"n":"Squalano","f":"Formula molecolare","v":"C30H62","o":0},
{"n":"Squalano","f":"Peso molecolare","v":"422.83 g/mol","o":1},
{"n":"Squalano","f":"Purezza","v":">92%","o":2},
{"n":"Squalano","f":"Aspetto","v":"Liquido limpido, odore impercettibile","o":3},
{"n":"Squalano","f":"Densità","v":"0.81","o":4},
{"n":"Squalano","f":"Viscosità","v":"35.5 cP","o":5},
{"n":"Squalano","f":"Origine","v":"100% vegetale (derivato da zucchero di canna)","o":6},
{"n":"Stagno (lingotti)","f":"Purezza","v":">99.99% (base metalli)","o":0},
{"n":"Stagno (lingotti)","f":"Punto di fusione","v":"231.9 °C","o":1},
{"n":"Stagno (lingotti)","f":"Punto di ebollizione","v":"2507 °C","o":2},
{"n":"Stagno (lingotti)","f":"Densità","v":"7.31 g/cm³ (25 °C)","o":3},
{"n":"Stearato di zinco","f":"Contenuto di zinco","v":"10.5 - 12.0%","o":0},
{"n":"Stearato di zinco","f":"Acidi grassi liberi","v":"max 1.0% (come oleico)","o":1},
{"n":"Stearato di zinco","f":"Punto di fusione","v":"120 - 124 °C","o":2},
{"n":"Stearato di zinco","f":"Densità apparente","v":"0.27 - 0.32 g/cm³","o":3},
{"n":"Stearato di zinco","f":"Indice di acidità","v":"max 2.0 mg KOH/g","o":4},
{"n":"Stearato di zinco","f":"Umidità e sostanze volatili","v":"max 0.5%","o":5},
{"n":"Stirene (monomero)","f":"Formula molecolare","v":"C8H8","o":0},
{"n":"Stirene (monomero)","f":"Peso molecolare","v":"104.1 g/mol","o":1},
{"n":"Stirene (monomero)","f":"Purezza","v":"99.9423% peso","o":2},
{"n":"Stirene (monomero)","f":"Etilbenzene","v":"< 10 ppm","o":3},
{"n":"Stirene (monomero)","f":"Benzene","v":"0 ppm","o":4},
{"n":"Stirene (monomero)","f":"Toluene","v":"0 ppm","o":5},
{"n":"Stirene (monomero)","f":"Polimero","v":"1 ppm","o":6},
{"n":"Stirene (monomero)","f":"Colore (APHA)","v":"8.1","o":7},
{"n":"Stirene (monomero)","f":"Aldeidi (come benzaldeide)","v":"0.0% peso","o":8},
{"n":"Stirene (monomero)","f":"Cloruri totali (come Cl)","v":"< 1 ppm","o":9},
{"n":"Stirene (monomero)","f":"Zolfo totale (come S)","v":"< 1 ppm","o":10},
{"n":"Stirene (monomero)","f":"Perossidi (come H2O2)","v":"10 ppm","o":11},
{"n":"Stirene (monomero)","f":"Inibitore (TBC)","v":"40 ppm","o":12},
{"n":"Stirene (monomero)","f":"Peso specifico","v":"0.908","o":13},
{"n":"Sucralosio","f":"Assay (base anidra, HPLC)","v":"98.0 - 102.0%","o":0},
{"n":"Sucralosio","f":"Rotazione ottica specifica (base anidra)","v":"+84.0 / +87.5°","o":1},
{"n":"Sucralosio","f":"Contenuto d'acqua (Karl Fischer)","v":"≤ 2.0%","o":2},
{"n":"Sucralosio","f":"Arsenico (come As, ICP)","v":"< 3 ppm","o":3},
{"n":"Sucralosio","f":"Conformità normativa","v":"Reg. UE 231/2012 (E955)","o":4},
{"n":"Talco","f":"Aspetto","v":"Polvere bianca, odore terroso leggero","o":0},
{"n":"Talco","f":"Granulometria media","v":"5.5 micron (97.7% passante a 325 mesh)","o":1},
{"n":"Talco","f":"Solubilità","v":"Insolubile in acqua, alcoli e oli","o":2},
{"n":"Talco","f":"Processo di purificazione","v":"Flottazione e macinazione fine","o":3},
{"n":"Tannini enologici","f":"Composizione","v":"Tannino ellagico","o":0},
{"n":"Tannini enologici","f":"Dosaggio (formulazione liquida)","v":"3 - 10 mL/hL","o":1},
{"n":"Tannini enologici","f":"Modalità di preparazione","v":"Diluire in 10 parti di vino prima dell'aggiunta","o":2},
{"n":"Tannini enologici","f":"Funzione tecnica","v":"Stabilizzazione del colore e protezione aromatica del vino","o":3},
{"n":"Tartrato neutro di potassio","f":"Formula molecolare","v":"K2C4H4O6","o":0},
{"n":"Tartrato neutro di potassio","f":"Peso molecolare","v":"226.27 g/mol","o":1},
{"n":"Tartrato neutro di potassio","f":"Punto di fusione","v":"Decompone a 200 - 220 °C (senza fusione netta)","o":2},
{"n":"Tartrato neutro di potassio","f":"Solubilità in acqua","v":"~0.8 g/100 mL (25 °C); 6.1 g/100 mL (100 °C)","o":3},
{"n":"Tartrato neutro di potassio","f":"Densità","v":"~1.98 g/cm³","o":4},
{"n":"Tartrato neutro di potassio","f":"pH (soluzione 0.1%)","v":"7 - 9 (20 °C)","o":5},
{"n":"Tartrato neutro di potassio","f":"Aspetto","v":"Cristalli o polvere bianca/incolore","o":6},
{"n":"Tetraidrofurano (THF)","f":"Aspetto","v":"Liquido incolore","o":0},
{"n":"Tetraidrofurano (THF)","f":"Densità","v":"0.8800 g/mL","o":1},
{"n":"Tetraidrofurano (THF)","f":"Punto di infiammabilità","v":"-14 °C","o":2},
{"n":"Tiosolfato di sodio","f":"Punto di fusione (forma anidra)","v":"47.8 °C","o":0},
{"n":"Tiosolfato di sodio","f":"Solubilità in acqua","v":"20.9 g/100 mL (20 °C); 231 g/100 mL (100 °C)","o":1},
{"n":"Tiosolfato di sodio","f":"Densità relativa","v":"1.667","o":2},
{"n":"Tiosolfato di sodio","f":"pH (soluzione acquosa)","v":"6.5 - 8","o":3},
{"n":"Tiosolfato di sodio","f":"Aspetto","v":"Solido bianco, inodore, igroscopico","o":4},
{"n":"Titanio (spugna o lingotti)","f":"Punto di fusione","v":"~1660 °C","o":0},
{"n":"Titanio (spugna o lingotti)","f":"Punto di ebollizione","v":"3287 °C","o":1},
{"n":"Titanio (spugna o lingotti)","f":"Densità","v":"4.5 g/cm³ (25 °C)","o":2},
{"n":"Tocoferil acetato (vitamina E)","f":"Assay","v":"98.0 - 102.0% (980 - 1020 mg/g vitamina E)","o":0},
{"n":"Tocoferil acetato (vitamina E)","f":"Indice di rifrazione (20 °C)","v":"1.503 - 1.507","o":1},
{"n":"Tocoferil acetato (vitamina E)","f":"Solubilità","v":"Solubile in idrocarburi, alcoli, grassi e oli; insolubile in acqua","o":2},
{"n":"Tocoferil acetato (vitamina E)","f":"Stabilità","v":"Stabile al calore e all'ossigeno (a differenza del tocoferolo libero)","o":3},
{"n":"Toluene","f":"Aspetto","v":"Liquido limpido incolore","o":0},
{"n":"Toluene","f":"Punto di infiammabilità","v":"4 °C","o":1},
{"n":"Toluene","f":"Punto di ebollizione","v":"110.6 °C","o":2},
{"n":"Toluene","f":"Punto di fusione/congelamento","v":"-95 °C","o":3},
{"n":"Toluene","f":"Tensione di vapore","v":"10 mmHg","o":4},
{"n":"Toluene","f":"Densità di vapore (aria=1)","v":"3.1","o":5},
{"n":"Toluene","f":"Viscosità (20 °C)","v":"0.59 cP","o":6},
{"n":"Triclosan","f":"Formula molecolare","v":"C12H7Cl3O2","o":0},
{"n":"Triclosan","f":"Purezza (grado, GC)","v":"97.0 - 103.0%","o":1},
{"n":"Triclosan","f":"Punto di fusione","v":"55 - 59 °C","o":2},
{"n":"Triclosan","f":"Aspetto","v":"Polvere o cristalli","o":3},
{"n":"Triclosan","f":"Solubilità","v":"5% in NaOH 1M (25 °C), da leggermente torbido a limpido, incolore","o":4},
{"n":"Urea","f":"Aspetto","v":"Solido bianco, odore di ammoniaca","o":0},
{"n":"Urea","f":"Punto di fusione/congelamento","v":"131 - 135 °C","o":1},
{"n":"Urea","f":"pH (soluzione acquosa 10%)","v":"7.5 - 9.5","o":2},
{"n":"Urea","f":"Tensione di vapore (25 °C)","v":"1.25 mmHg","o":3},
{"n":"Urea","f":"Grado","v":"Certified ACS","o":4},
{"n":"White spirit / ragia minerale","f":"Colore Saybolt","v":"+30 (tipico)","o":0},
{"n":"White spirit / ragia minerale","f":"Densità a 15 °C","v":"0.783 kg/L (tipico); spec 0.775 - 0.790 kg/L","o":1},
{"n":"White spirit / ragia minerale","f":"Distillazione - Punto iniziale (PIE)","v":"149 °C (tipico); spec 145 - 155 °C","o":2},
{"n":"White spirit / ragia minerale","f":"Distillazione - 10% v/v","v":"155 °C (tipico); spec 150 - 160 °C","o":3},
{"n":"White spirit / ragia minerale","f":"Distillazione - 50% v/v","v":"163 °C (tipico); spec 160 - 170 °C","o":4},
{"n":"White spirit / ragia minerale","f":"Distillazione - 95% v/v","v":"182 °C (tipico); spec 180 - 190 °C","o":5},
{"n":"White spirit / ragia minerale","f":"Distillazione - Punto finale (PF)","v":"194 °C (tipico); spec max 200 °C","o":6},
{"n":"White spirit / ragia minerale","f":"Contenuto aromatici","v":"20% m/m (tipico)","o":7},
{"n":"White spirit / ragia minerale","f":"Contenuto paraffine","v":"55% m/m (tipico)","o":8},
{"n":"White spirit / ragia minerale","f":"Contenuto nafteni","v":"25% m/m (tipico)","o":9},
{"n":"White spirit / ragia minerale","f":"Punto di infiammabilità (metodo Abel)","v":"36 °C","o":10},
{"n":"White spirit / ragia minerale","f":"Conformità normativa","v":"Australian Standard AS 3530","o":11},
{"n":"Xilene (miscela)","f":"Aspetto","v":"Liquido limpido incolore","o":0},
{"n":"Xilene (miscela)","f":"Punto di ebollizione","v":"137 - 140 °C","o":1},
{"n":"Xilene (miscela)","f":"Punto di infiammabilità (vaso chiuso)","v":"22.8 °C","o":2},
{"n":"Xilene (miscela)","f":"Densità","v":"0.865 g/cm³","o":3},
{"n":"Xilene (miscela)","f":"Punto di congelamento","v":"-34 °C","o":4},
{"n":"Xilene (miscela)","f":"Composizione isomeri","v":"Miscela orto-, meta-, para-xilene","o":5},
{"n":"Zeolite A","f":"Composizione (peso)","v":"~17% Na2O, 28% Al2O3, 33% SiO2, 22% acqua","o":0},
{"n":"Zeolite A","f":"Granulometria media","v":"3 - 6 micron","o":1},
{"n":"Zeolite A","f":"Capacità di scambio cationico (CER, 2 min, 10 °C)","v":"160 - 190 mg CaCO3/g (anidro)","o":2},
{"n":"Zeolite A","f":"Capacità di scambio cationico (acqua fredda)","v":"fino a ~250 mg CaCO3/g","o":3},
{"n":"Zeolite A","f":"Densità apparente","v":"0.19 - 0.35 g/mL","o":4},
{"n":"Zeolite A","f":"Aspetto","v":"Polvere fluida, cristalli cubici uniformi","o":5},
{"n":"Zinco (lingotti)","f":"Grado/Purezza","v":"Special High Grade (SHG) 99.995% Zn","o":0},
{"n":"Zinco (lingotti)","f":"Piombo (Pb)","v":"0.0018% (tipico)","o":1},
{"n":"Zinco (lingotti)","f":"Cadmio (Cd)","v":"0.0002% (tipico)","o":2},
{"n":"Zinco (lingotti)","f":"Ferro (Fe)","v":"0.0002% (tipico)","o":3},
{"n":"Zinco (lingotti)","f":"Stagno (Sn)","v":"0.0002% (tipico)","o":4},
{"n":"Zinco (lingotti)","f":"Rame (Cu)","v":"0.0001% (tipico)","o":5},
{"n":"Zinco (lingotti)","f":"Conformità normativa","v":"Grado Z1 approvato LME (London Metal Exchange)","o":6},
{"n":"Zolfo elementare","f":"Purezza","v":"99.5 - 100.5%","o":0},
{"n":"Zolfo elementare","f":"Punto di fusione","v":"~114 - 120 °C","o":1},
{"n":"Zolfo elementare","f":"Aspetto","v":"Polvere gialla","o":2},
{"n":"Zolfo elementare","f":"Solubilità","v":"Praticamente insolubile in acqua; solubile in solfuro di carbonio; leggermente solubile in oli vegetali","o":3},
{"n":"Zolfo elementare","f":"Ceneri","v":"max 0.2%","o":4}]$j$::jsonb) as x(n text, f text, v text, o int);
  select md5(string_agg(rh, '' order by rh collate "C")) into got from (select md5(n||chr(31)||f||chr(31)||v||chr(31)||o::text) as rh from _stg_specs) q;
  if got is distinct from expected then
    raise exception 'specs batch 4 integrity check failed: expected % got %', expected, got;
  end if;
  insert into public.product_specs (product_id, campo, valore, ordine)
  select p.id, s.f, s.v, s.o from _stg_specs s join public.products p on lower(btrim(p.canonical_name)) = lower(btrim(s.n));
  get diagnostics n_ins = row_count;
  raise notice 'specs batch 4: staged=%, inserted=%', (select count(*) from _stg_specs), n_ins;
end
$mig$;
